<a href="https://colab.research.google.com/github/AmyMugeni/cognilens/blob/ML-dataset-processing/Cognilens_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import os

drive.mount('/content/drive')

project_path = '/content/drive/MyDrive/Cognilens_MLtraining'
os.makedirs(project_path, exist_ok=True)
os.chdir(project_path)

print(f"Working directory set to: {os.getcwd()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Working directory set to: /content/drive/MyDrive/Cognilens_MLtraining

## 1. Imports and Setup

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, GridSearchCV, train_test_split
from sklearn.metrics import classification_report, roc_auc_score, f1_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBClassifier

## 2. Data Loading and Initial Cleaning

In [ ]:
import pandas as pd

# 1. Load Primary Dataset from the current working directory (which is your Drive folder)
df_student_activities = pd.read_csv("SocialMediaUse_export (4).csv")

cols_to_drop = [
    'notification_count', 'triggered_by_notification',
    'scroll_count', 'scroll_speed_estimate', 'avg_scroll_delta_px',
    'micro_scrolls', 'normal_scrolls', 'macro_scrolls',
    'scroll_behavior', 'detected_format'
]
df_student_activities = df_student_activities.drop(columns=[c for c in cols_to_drop if c in df_student_activities.columns], errors='ignore')

print("Initial data loaded and cleaned.")
display(df_student_activities.head())

Initial data loaded and cleaned.

,user_id,session_start,session_end,date,day_of_week,session_hour,time_of_day,app_label,duration_minutes,tap_count,minutes_since_last_session,day_asi_score,day_intensity_score,day_fragmentation_score,day_compulsion_score,day_disruption_score
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790281329502,1790281593063,2026-09-24,Thursday,23,night,Instagram,4.39,0,28.47,48,45,68,32,49
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790279631154,1790279723216,2026-09-24,Thursday,22,night,YouTube,1.53,0,33.34,48,45,68,32,49
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790279484659,1790279621543,2026-09-24,Thursday,22,night,Instagram,2.28,0,7.95,48,45,68,32,49
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790278804601,1790279007621,2026-09-24,Thursday,22,night,Instagram,3.38,2,2.64,48,45,68,32,49
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790278538451,1790278646464,2026-09-24,Thursday,22,night,Instagram,1.80,0,0.00,48,45,68,32,49

In [ ]:
from google.colab import files

# Save the initially cleaned DataFrame to a new CSV file
cleaned_output_filename = "cleaned_student_activities.csv"
df_student_activities.to_csv(cleaned_output_filename, index=False)

print(f"File '{cleaned_output_filename}' saved successfully. Downloading...")

# Trigger the download
files.download(cleaned_output_filename)

File 'cleaned_student_activities.csv' saved successfully. Downloading...

In [ ]:
!pip install pdfplumber pandas

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.4 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 62.3 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 52.8 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 64.7 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0

PDF TIMETABLE CONVERSION TO CSV USING API KEY

In [ ]:
from google.colab import files
import pdfplumber
import re
import pandas as pd
from datetime import datetime

In [ ]:
!pip install google-genai pdf2image pydantic pandas
!apt-get install -y poppler-utils

Requirement already satisfied: google-genai in /usr/local/lib/python3.13/dist-packages (2.12.1)
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (2.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (4.15.1)
Requirement already satisfied: google-auth<2.56.0,>=2.48.1 in /usr/local/lib/python3.13/dist-packages (from google-auth[requests]<2.56.0,>=2.48.1->google-genai) (2.49.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.13/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.13/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from google-genai) (1.3.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from pdf2image) (12.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic) (0.4.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.19)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (50.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (2.1.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (0.6.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai) (3.0)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 212 kB of archives.
After this operation, 735 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 poppler-utils amd64 24.02.0-1ubuntu9.9 [212 kB]
Fetched 212 kB in 1s (215 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack .../poppler-utils_24.02.0-1ubuntu9.9_amd64.deb ...
Unpacking poppler-utils (24.02.0-1ubuntu9.9) ...
Setting up poppler-utils (24.02.0-1ubuntu9.9) ...
Processing triggers for man-db (2.12.0-4build2) ...

In [ ]:
from google.colab import userdata
userdata.get('secretName')

SecretNotFoundError: Secret secretName does not exist.

I'm broke right now but this will help with model training for now till I pay for API keys for to do pdf to csv that makes sense

In [ ]:
import pandas as pd

rows = [
    ["Monday", "08:15", "10:15", "ICS 4106",
     "Computer Simulation and Modelling", "C Ouma", "STM-B F2-05"],
    ["Monday", "10:15", "12:15", "ICS 4102",
     "Machine Learning", "J Wekesa", ""],
    ["Monday", "13:15", "14:15", "ICS 4103",
     "Cloud Computing", "V Ochango", ""],
    ["Monday", "15:15", "17:15", "ICS 3105",
     "Multimedia Applications", "Z Muti", ""],

    ["Tuesday", "08:15", "10:15", "ICS 4101",
     "ICS Project II", "K Omondi", ""],
    ["Tuesday", "10:15", "11:15", "",
     "Maisha Program 7 - Gents 4A", "P Neri", "RM B"],
    ["Tuesday", "11:15", "12:15", "",
     "Maisha Program 7 - Ladies ICS 4A", "R Bunde", "RM 10"],
    ["Tuesday", "13:15", "15:15", "ICS 4104",
     "Distributed Systems", "H Talo", "STM-B F2-05"],

    ["Wednesday", "08:15", "10:15", "ICS 4111",
     "Embedded Systems and Internet of Things", "A Vikiru", ""],
    ["Wednesday", "11:15", "12:15", "ICS 4106",
     "Computer Simulation and Modelling", "C Ouma", ""],
    ["Wednesday", "13:15", "15:15", "ICS 4104",
     "Distributed Systems", "H Talo", ""],
    ["Wednesday", "15:15", "17:15", "ICS 4103",
     "Cloud Computing", "V Ochango", "MSB 13"],

    ["Thursday", "08:15", "10:15", "ICS 4101",
     "ICS Project II", "K Omondi", "LT 6"],
    ["Thursday", "11:15", "13:15", "ICS 4111",
     "Embedded Systems and Internet of Things", "A Vikiru", "Masinga Lab"],
    ["Thursday", "15:15", "17:15", "ICS 3105",
     "Multimedia Applications", "Z Muti", "LT 6"],

    ["Friday", "08:15", "10:15", "ICS 4102",
     "Machine Learning", "J Wekesa", "LT 2"],
    ["Friday", "14:15", "17:15", "",
     "Sports/Clubs", "", ""],
]

columns = [
    "day", "start_time", "end_time",
    "unit_code", "unit_name", "lecturer", "venue"
]

timetable_df = pd.DataFrame(rows, columns=columns)

# Create an 'activity' column by combining 'unit_code' and 'unit_name'
def get_activity_name(row):
    if row['unit_code'].strip():
        if row['unit_name'].strip():
            return f"{row['unit_code']} - {row['unit_name']}"
        else:
            return row['unit_code']
    else:
        return row['unit_name']

timetable_df['activity'] = timetable_df.apply(get_activity_name, axis=1)

# put weekdays in calendar order
weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
timetable_df["day"] = pd.Categorical(
    timetable_df["day"],
    categories=weekday_order,
    ordered=True
)
timetable_df = timetable_df.sort_values(["day", "start_time"])

# Select only the desired 4 columns for the final CSV
df_final_csv = timetable_df[["day", "start_time", "end_time", "activity"]]

# Save the structured timetable
df_final_csv.to_csv("bics_4a_apr_jul_2026.csv", index=False)

Feature engineering - Timetable part

In [ ]:
import pandas as pd
import numpy as np

# 1. Load your generated timetable CSV
df_timetable = pd.read_csv("bics_4a_apr_jul_2026.csv")

# 2. Convert string time "HH:MM" to 24-hour decimal hours (e.g., "08:15" -> 8.25)
def time_to_decimal(time_str):
    if pd.isna(time_str):
        return np.nan
    hours, minutes = map(int, str(time_str).strip().split(":"))
    return hours + (minutes / 60.0)

df_timetable["start_decimal"] = df_timetable["start_time"].apply(time_to_decimal)
df_timetable["end_decimal"] = df_timetable["end_time"].apply(time_to_decimal)

# 3. Map day strings to standard numerical weekdays (Monday=0, Tuesday=1, ..., Sunday=6)
day_mapping = {
    "Monday": 0, "Tuesday": 1, "Wednesday": 2,
    "Thursday": 3, "Friday": 4, "Saturday": 5, "Sunday": 6
}
df_timetable["day_of_week"] = df_timetable["day"].map(day_mapping)

# 4. Binary Indicator: Flag scheduled commitments
df_timetable["is_scheduled_commitment"] = 1

print("=== PROCESSED TIMETABLE FEATURE MAP ===")
display(df_timetable[["day", "day_of_week", "start_decimal", "end_decimal", "activity", "is_scheduled_commitment"]])

=== PROCESSED TIMETABLE FEATURE MAP ===

,day,day_of_week,start_decimal,end_decimal,activity,is_scheduled_commitment
0,Monday,0,8.25,10.25,ICS 4106 - Computer Simulation and Modelling,1
1,Monday,0,10.25,12.25,ICS 4102 - Machine Learning,1
2,Monday,0,13.25,14.25,ICS 4103 - Cloud Computing,1
3,Monday,0,15.25,17.25,ICS 3105 - Multimedia Applications,1
4,Tuesday,1,8.25,10.25,ICS 4101 - ICS Project II,1
5,Tuesday,1,10.25,11.25,Maisha Program 7 - Gents 4A,1
6,Tuesday,1,11.25,12.25,Maisha Program 7 - Ladies ICS 4A,1
7,Tuesday,1,13.25,15.25,ICS 4104 - Distributed Systems,1
8,Wednesday,2,8.25,10.25,ICS 4111 - Embedded Systems and Internet of Th...,1
9,Wednesday,2,11.25,12.25,ICS 4106 - Computer Simulation and Modelling,1
10,Wednesday,2,13.25,15.25,ICS 4104 - Distributed Systems,1
11,Wednesday,2,15.25,17.25,ICS 4103 - Cloud Computing,1
12,Thursday,3,8.25,10.25,ICS 4101 - ICS Project II,1
13,Thursday,3,11.25,13.25,ICS 4111 - Embedded Systems and Internet of Th...,1
14,Thursday,3,15.25,17.25,ICS 3105 - Multimedia Applications,1
15,Friday,4,8.25,10.25,ICS 4102 - Machine Learning,1
16,Friday,4,14.25,17.25,Sports/Clubs,1

Mapping Timetable features to Cognilens student logs

In [ ]:
import pandas as pd

# ---------------------------------------------------------
# 1. Use the existing student dataset
# ---------------------------------------------------------

df_student_activities = df_student_activities.copy()

# Create a 'timestamp' column from 'session_start' (Unix milliseconds)
df_student_activities["timestamp_utc"] = pd.to_datetime(
    df_student_activities["session_start"],
    unit="ms",
    utc=True
)

df_student_activities["timestamp_local"] = (
    df_student_activities["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# ---------------------------------------------------------
# 2. Make sure timetable times are represented in minutes
# ---------------------------------------------------------

def time_to_minutes(time_str):
    if pd.isna(time_str):
        return None

    hours, minutes = map(int, str(time_str).strip().split(":"))
    return hours * 60 + minutes


df_timetable["start_minute"] = (
    df_timetable["start_time"].apply(time_to_minutes)
)

df_timetable["end_minute"] = (
    df_timetable["end_time"].apply(time_to_minutes)
)

# ---------------------------------------------------------
# 3. Match each session against the shared timetable
# ---------------------------------------------------------

def evaluate_schedule_conflict(timestamp, timetable_df):

    if pd.isna(timestamp):
        return 0

    event_day = timestamp.weekday()

    event_minute = (
        timestamp.hour * 60
        + timestamp.minute
    )

    day_classes = timetable_df[
        timetable_df["day_of_week"] == event_day
    ]

    conflict = day_classes[
        (day_classes["start_minute"] <= event_minute) &
        (event_minute < day_classes["end_minute"])
    ]

    return int(not conflict.empty)


# ---------------------------------------------------------
# 4. Apply the timetable mapping
# ---------------------------------------------------------

df_student_activities["is_schedule_conflict"] = (
    df_student_activities["timestamp_local"].apply(
        lambda ts: evaluate_schedule_conflict(
            ts,
            df_timetable
        )
    )
)
# ---------------------------------------------------------
# 5. Inspect results
# ---------------------------------------------------------

print("Schedule conflict mapping complete.")

print("\nConflict distribution:")
print(
    df_student_activities["is_schedule_conflict"]
    .value_counts()
)

print("\nFirst 10 mapped sessions:")
display(
    df_student_activities[
        [
            "user_id",
            "timestamp_local",
            "day_of_week",
            "session_hour",
            "app_label",
            "duration_minutes",
            "is_schedule_conflict"
        ]
    ].head(10)
)

Schedule conflict mapping complete.

Conflict distribution:
is_schedule_conflict
0    398
1    104
Name: count, dtype: int64

First 10 mapped sessions:

,user_id,timestamp_local,day_of_week,session_hour,app_label,duration_minutes,is_schedule_conflict
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 23:22:09.502000+03:00,Thursday,23,Instagram,4.39,0
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:53:51.154000+03:00,Thursday,22,YouTube,1.53,0
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:51:24.659000+03:00,Thursday,22,Instagram,2.28,0
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:40:04.601000+03:00,Thursday,22,Instagram,3.38,0
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:35:38.451000+03:00,Thursday,22,Instagram,1.80,0
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:30:19.366000+03:00,Thursday,22,Instagram,5.32,0
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:26:02.199000+03:00,Thursday,22,Instagram,2.01,0
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:18:54.137000+03:00,Thursday,22,YouTube,1.61,0
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:13:01.561000+03:00,Thursday,22,Instagram,5.69,0
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:00:38.696000+03:00,Thursday,22,Instagram,0.92,0

In [ ]:
from google.colab import files

# Save the DataFrame to a new CSV file
output_filename = "student_activities_with_conflicts.csv"
df_student_activities.to_csv(output_filename, index=False)

print(f"File '{output_filename}' saved successfully. Downloading...")

# Trigger the download
files.download(output_filename)

File 'student_activities_with_conflicts.csv' saved successfully. Downloading...

Noticed an issue with the timezone, UTC/ East African time

In [ ]:
# Compare the existing session_hour with the actual timestamp hour

df_student_activities["timestamp_hour_check"] = (
    df_student_activities["timestamp"].dt.hour
)

comparison = df_student_activities[
    ["timestamp", "session_hour", "timestamp_hour_check"]
].head(20)

display(comparison)

# Count mismatches
mismatch_count = (
    df_student_activities["session_hour"]
    != df_student_activities["timestamp_hour_check"]
).sum()

print(f"Total rows: {len(df_student_activities)}")
print(f"Hour mismatches: {mismatch_count}")
print(
    f"Mismatch percentage: "
    f"{mismatch_count / len(df_student_activities) * 100:.2f}%"
)

KeyError: 'timestamp'

In [ ]:
df_student_activities["timestamp_utc"] = pd.to_datetime(
    df_student_activities["session_start"],
    unit="ms",
    utc=True
)

df_student_activities["timestamp_local"] = (
    df_student_activities["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

In [ ]:
display(
    df_student_activities[
        [
            "session_start",
            "timestamp_utc",
            "timestamp_local",
            "session_hour"
        ]
    ].head(10)
)

Feature Engineering of selected features

In [ ]:

# ---------------------------------------------------------
# CogniLens: Initial behavioural feature engineering
# ---------------------------------------------------------

import pandas as pd
import numpy as np

# Work on a copy
df_features = df_student_activities.copy()

# Ensure records are chronologically ordered per user
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# ---------------------------------------------------------
# 1. TEMPORAL FEATURES
# ---------------------------------------------------------

df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

df_features["local_hour"] = (
    df_features["timestamp_local"].dt.hour
)

df_features["day_of_week"] = (
    df_features["timestamp_local"].dt.dayofweek
)

# ---------------------------------------------------------
# 2. COMPULSIVE-USE INDICATORS
# ---------------------------------------------------------

# Calculate gap from the previous session for the same user.
# This is derived from timestamps rather than assuming
# missing gaps represent a fixed duration.


# Convert session_end from Unix milliseconds to local time
df_features["session_end_utc"] = pd.to_datetime(
    df_features["session_end"],
    unit="ms",
    utc=True
)

df_features["session_end_local"] = (
    df_features["session_end_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# Sort chronologically within each user
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# Previous session's end time for each user
df_features["previous_session_end"] = (
    df_features.groupby("user_id")["session_end_local"].shift(1)
)

# Actual time between the previous session ending
# and the current session starting
df_features["session_gap_minutes"] = (
    (
        df_features["timestamp_local"]
        - df_features["previous_session_end"]
    ).dt.total_seconds() / 60
)

# Count sessions per user per local day
df_features["daily_session_count"] = (
    df_features.groupby(["user_id", "local_date"])
    ["timestamp_local"]
    .transform("count")
)

# ---------------------------------------------------------
# 3. SCHEDULE DISRUPTION
# ---------------------------------------------------------

# This is contextual, not proof of neglected responsibility.
df_features["is_schedule_conflict"] = pd.to_numeric(
    df_features["is_schedule_conflict"],
    errors="coerce"
)

# ---------------------------------------------------------
# 4. DURATION AND DAILY USAGE
# ---------------------------------------------------------

df_features["duration_minutes"] = pd.to_numeric(
    df_features["duration_minutes"],
    errors="coerce"
)

# Sum of session durations per user per local day
df_features["daily_usage_minutes"] = (
    df_features.groupby(["user_id", "local_date"])
    ["duration_minutes"]
    .transform("sum")
)

INDIVIDUAL BASELINE CALCULATION

In [ ]:

# Ensure chronological order
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# Calculate median duration from previous sessions only
df_features["previous_median_duration"] = (
    df_features.groupby("user_id")["duration_minutes"]
    .transform(
        lambda s: s.shift(1).expanding(min_periods=5).median()
    )
)

# Current duration minus historical median
df_features["duration_baseline_deviation"] = (
    df_features["duration_minutes"]
    - df_features["previous_median_duration"]
)

# Current duration relative to historical median
df_features["duration_baseline_ratio"] = (
    df_features["duration_minutes"]
    / df_features["previous_median_duration"].replace(0, np.nan)
)

# Inspect the first 15 sessions
display(
    df_features[
        [
            "timestamp_local",
            "duration_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(15)
)

In [ ]:
# ---------------------------------------------------------
# Recalculate real-time daily usage features
# ---------------------------------------------------------

# Make sure records are chronologically ordered
df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Local date
df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

# Number of previous sessions by this user on the same day
df_features["prior_daily_session_count"] = (
    df_features
    .groupby(["user_id", "local_date"])
    .cumcount()
)

# Previous sessions' duration
# Shift BEFORE calculating the cumulative sum so that
# the current session is never included.
df_features["prior_daily_usage_minutes"] = (
    df_features
    .groupby(["user_id", "local_date"])["duration_minutes"]
    .transform(
        lambda s: s.shift(1).fillna(0).cumsum()
    )
)

# ---------------------------------------------------------
# Verify
# ---------------------------------------------------------

print("Real-time feature columns created successfully.")

display(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes"
        ]
    ].head(15)
)

In [ ]:

print("Negative session gaps:")
print(
    (df_features["session_gap_minutes"] < 0).sum()
)

print("\nMissing session gaps:")
print(
    df_features["session_gap_minutes"].isna().sum()
)

print("\nGap statistics:")
display(
    df_features["session_gap_minutes"].describe()
)

print("\nReal-time features:")
display(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "session_gap_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(15)
)

Check for duplicate sessions

In [ ]:

# ---------------------------------------------------------
# Session data quality checks
# ---------------------------------------------------------

# 1. Duplicate sessions
duplicates = df_features.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("Duplicate session records:", duplicates.sum())

# 2. Negative session durations
print(
    "Negative durations:",
    (df_features["duration_minutes"] < 0).sum()
)

# 3. Overlapping sessions
print(
    "Overlapping session gaps:",
    (df_features["session_gap_minutes"] < 0).sum()
)

# 4. Zero-duration sessions
print(
    "Zero-duration sessions:",
    (df_features["duration_minutes"] == 0).sum()
)

# 5. Missing values in key features
key_features = [
    "duration_minutes",
    "session_gap_minutes",
    "is_schedule_conflict",
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio"
]

print("\nMissing values:")
display(df_features[key_features].isna().sum().to_frame("missing_count"))

# 6. Duration and gap distributions
print("\nDuration statistics:")
display(df_features["duration_minutes"].describe())

print("\nSession gap statistics:")
display(df_features["session_gap_minutes"].describe())

In [ ]:
print("Unique users:", df_features["user_id"].nunique())

print("\nSessions longer than 30 minutes:")
display(
    df_features.loc[
        df_features["duration_minutes"] > 30,
        ["user_id", "timestamp_local", "duration_minutes", "app_label"]
    ].sort_values("duration_minutes", ascending=False)
)

print("\nLongest session gaps:")
display(
    df_features.nlargest(
        10, "session_gap_minutes"
    )[[
        "user_id",
        "timestamp_local",
        "session_gap_minutes"
    ]]
)

INDIVIDUAL DATASET PROCESSING

In [ ]:
import pandas as pd
import os
import glob

files = glob.glob("/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export*.csv")

for file in sorted(files):
    temp = pd.read_csv(file)

    print(f"\nFile: {os.path.basename(file)}")
    print("Rows:", len(temp))

    if "user_id" in temp.columns:
        print("Unique users:", temp["user_id"].nunique())
        print("User IDs:")
        print(temp["user_id"].value_counts().to_string())
    else:
        print("No user_id column")

    print("Columns:", temp.columns.tolist())

In [ ]:
import pandas as pd
import glob
import os

files = glob.glob("/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export*.csv")

for file in sorted(files):
    temp = pd.read_csv(file)

    print(f"\n{'='*70}")
    print(os.path.basename(file))
    print(f"Rows: {len(temp)}")

    if "user_id" in temp.columns:
        print(f"Users: {temp['user_id'].nunique(dropna=True)}")
        print("User IDs:")
        print(temp["user_id"].dropna().unique())

    if "date" in temp.columns:
        print(f"Date range: {temp['date'].min()} → {temp['date'].max()}")

    if "session_start" in temp.columns:
        print(
            "Session start range:",
            temp["session_start"].min(),
            "→",
            temp["session_start"].max()
        )

    print("Missing user_id:", temp["user_id"].isna().sum())

In [ ]:
import pandas as pd
import os

candidate_files = [
    "SocialMediaUse_export (2).csv",
    "SocialMediaUse_export (4).csv",
    "SocialMediaUse_export.csv",
    "SocialMediaUse_export 5.csv",
    "SocialMediaUse_export 6.csv",
    "SocialMediaUse_export 7.csv"
]

for file in candidate_files:

    temp = pd.read_csv(f"/content/drive/MyDrive/Cognilens_MLtraining/{file}")

    print("\n" + "=" * 70)
    print(file)

    # Duplicate session records
    if "session_start" in temp.columns and "user_id" in temp.columns:
        duplicates = temp.duplicated(
            subset=["user_id", "session_start"],
            keep=False
        )

        print("Duplicate user/session-start records:", duplicates.sum())

    # Missingness
    print("Rows:", len(temp))
    print("Missing user_id:", temp["user_id"].isna().sum())

    # User distribution
    print("\nUsers:")
    print(temp["user_id"].value_counts(dropna=False))

    # Date range
    if "date" in temp.columns:
        print(
            "\nDate range:",
            temp["date"].min(),
            "→",
            temp["date"].max()
        )

======================================================================
SocialMediaUse_export (2).csv
Duplicate user/session-start records: 0
Rows: 708
Missing user_id: 0

Users:
user_id
85bfc215-c24f-4814-aa00-6794f1a7278a    708
Name: count, dtype: int64

Date range: 2026-04-09 → 2026-07-12

======================================================================
SocialMediaUse_export (4).csv
Duplicate user/session-start records: 0
Rows: 502
Missing user_id: 0

Users:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    502
Name: count, dtype: int64

Date range: 2026-09-02 → 2026-09-24

======================================================================
SocialMediaUse_export.csv
Duplicate user/session-start records: 0
Rows: 3712
Missing user_id: 0

Users:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    3540
d5a62f7a-97c9-481c-83be-f0a06b70cad9     172
Name: count, dtype: int64

Date range: 2026-04-16 → 2026-09-29

======================================================================
SocialMediaUse_export 5.csv
Duplicate user/session-start records: 0
Rows: 183
Missing user_id: 0

Users:
user_id
e7642be3-461d-4c8e-98cd-0eccc76764ec    183
Name: count, dtype: int64

Date range: 2026-09-22 → 2026-09-29

======================================================================
SocialMediaUse_export 6.csv
Duplicate user/session-start records: 0
Rows: 307
Missing user_id: 0

Users:
user_id
f5e00193-6fb8-4767-ba5e-5c824dc24c89    307
Name: count, dtype: int64

Date range: 2026-09-23 → 2026-09-29

======================================================================
SocialMediaUse_export 7.csv
Duplicate user/session-start records: 0
Rows: 519
Missing user_id: 0

Users:
user_id
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67    519
Name: count, dtype: int64

Date range: 9/23/2026 → 9/30/2026

COMBINED PARTICIPANT DATASET

In [ ]:
import pandas as pd

# Load canonical source files
df_user_1 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export (2).csv"
)

df_user_2 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export (4).csv"
)

df_users_3_4 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export.csv"
)

df_user_5 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export 5.csv"
)

df_user_6 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export 6.csv"
)
df_user_7 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export 7.csv"
)

# Combine
df_all = pd.concat(
    [
        df_user_1,
        df_user_2,
        df_users_3_4,
        df_user_5,
        df_user_6,
        df_user_7
    ],
    ignore_index=True
)

print("Total sessions:", len(df_all))
print("Unique users:", df_all["user_id"].nunique())

print("\nSessions per user:")
display(
    df_all.groupby("user_id")
    .size()
    .reset_index(name="session_count")
)

# Global duplicate check
duplicates = df_all.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("\nDuplicate user/session-start records:", duplicates.sum())

Total sessions: 5931
Unique users: 7

Sessions per user:

                                user_id  session_count
0  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4            502
1  85bfc215-c24f-4814-aa00-6794f1a7278a            708
2  8cf97b0c-76c9-4d72-b617-759a955f969f           3540
3  9d9e9be2-c5aa-406b-a5a4-e5546f00cb67            519
4  d5a62f7a-97c9-481c-83be-f0a06b70cad9            172
5  e7642be3-461d-4c8e-98cd-0eccc76764ec            183
6  f5e00193-6fb8-4767-ba5e-5c824dc24c89            307

Duplicate user/session-start records: 0

DATASET AUDIT AND INTEGRITY

In [ ]:
# ============================================
# DATASET INTEGRITY AUDIT
# ============================================

print("========== DATASET OVERVIEW ==========")
print("Total sessions:", len(df_all))
print("Unique users:", df_all["user_id"].nunique())

print("\n========== DUPLICATES ==========")

duplicate_pairs = df_all.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("Duplicate user/session-start records:",
      duplicate_pairs.sum())

print("\n========== MISSING VALUES ==========")

missing_summary = (
    df_all.isna()
    .sum()
    .reset_index()
)

missing_summary.columns = ["column", "missing_count"]

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"] / len(df_all) * 100
)

display(
    missing_summary[
        missing_summary["missing_count"] > 0
    ].sort_values("missing_percentage", ascending=False)
)

print("\n========== DATA TYPES ==========")
print(df_all.dtypes)

print("\n========== SESSION DURATION ==========")

print(
    df_all["duration_minutes"].describe()
)

print("\n========== USERS ==========")

display(
    df_all.groupby("user_id")
    .agg(
        sessions=("user_id", "size"),
        mean_duration=("duration_minutes", "mean"),
        median_duration=("duration_minutes", "median"),
        total_usage_minutes=("duration_minutes", "sum")
    )
    .reset_index()
)

print("\n========== DATE RANGE ==========")

print("Earliest date:", df_all["date"].min())
print("Latest date:", df_all["date"].max())

========== DATASET OVERVIEW ==========
Total sessions: 5931
Unique users: 7

========== DUPLICATES ==========
Duplicate user/session-start records: 0

========== MISSING VALUES ==========

                        column  missing_count  missing_percentage
17             scroll_behavior           5713           96.324397
20  minutes_since_last_session             23            0.387793

========== DATA TYPES ==========
user_id                        object
session_start                   int64
session_end                     int64
date                           object
day_of_week                    object
session_hour                    int64
time_of_day                    object
app_label                      object
detected_format                object
duration_minutes              float64
scroll_count                    int64
tap_count                       int64
scroll_speed_estimate         float64
avg_scroll_delta_px             int64
micro_scrolls                   int64
normal_scrolls                  int64
macro_scrolls                   int64
scroll_behavior                object
notification_count              int64
triggered_by_notification        bool
minutes_since_last_session    float64
day_asi_score                   int64
day_intensity_score             int64
day_fragmentation_score         int64
day_compulsion_score            int64
day_disruption_score            int64
dtype: object

========== SESSION DURATION ==========
count    5931.000000
mean        6.226695
std        12.495288
min         0.500000
25%         1.050000
50%         2.420000
75%         6.375000
max       380.280000
Name: duration_minutes, dtype: float64

========== USERS ==========

,user_id,sessions,mean_duration,median_duration,total_usage_minutes
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,502,6.865976,2.285,3446.72
1,85bfc215-c24f-4814-aa00-6794f1a7278a,708,9.351935,3.790,6621.17
2,8cf97b0c-76c9-4d72-b617-759a955f969f,3540,5.798130,2.385,20525.38
3,9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,519,4.788863,2.200,2485.42
4,d5a62f7a-97c9-481c-83be-f0a06b70cad9,172,6.233140,2.115,1072.10
5,e7642be3-461d-4c8e-98cd-0eccc76764ec,183,11.288251,7.050,2065.75
6,f5e00193-6fb8-4767-ba5e-5c824dc24c89,307,2.325700,1.210,713.99

========== DATE RANGE ==========
Earliest date: 2026-04-09
Latest date: 9/30/2026

In [ ]:
print("========== TIMESTAMP CHECK ==========")

print("Missing session_start:",
      df_all["session_start"].isna().sum())

print("Missing session_end:",
      df_all["session_end"].isna().sum())

print("\nSession start data type:")
print(df_all["session_start"].dtype)

print("\nSession end data type:")
print(df_all["session_end"].dtype)

print("\nSample timestamps:")
display(
    df_all[
        ["user_id", "session_start", "session_end", "date", "session_hour"]
    ].head(10)
)

========== TIMESTAMP CHECK ==========
Missing session_start: 0
Missing session_end: 0

Session start data type:
int64

Session end data type:
int64

Sample timestamps:

,user_id,session_start,session_end,date,session_hour
0,85bfc215-c24f-4814-aa00-6794f1a7278a,1783889909076,1783890023674,2026-07-12,23
1,85bfc215-c24f-4814-aa00-6794f1a7278a,1783889342907,1783889898338,2026-07-12,23
2,85bfc215-c24f-4814-aa00-6794f1a7278a,1783887454981,1783888072008,2026-07-12,23
3,85bfc215-c24f-4814-aa00-6794f1a7278a,1783882413067,1783883571231,2026-07-12,21
4,85bfc215-c24f-4814-aa00-6794f1a7278a,1783882027872,1783882405234,2026-07-12,21
5,85bfc215-c24f-4814-aa00-6794f1a7278a,1783881837402,1783882015997,2026-07-12,21
6,85bfc215-c24f-4814-aa00-6794f1a7278a,1783880117282,1783880483307,2026-07-12,21
7,85bfc215-c24f-4814-aa00-6794f1a7278a,1783879842467,1783880091939,2026-07-12,21
8,85bfc215-c24f-4814-aa00-6794f1a7278a,1783878863089,1783879666339,2026-07-12,20
9,85bfc215-c24f-4814-aa00-6794f1a7278a,1783878306397,1783878812562,2026-07-12,20

In [ ]:
# ============================================
# TIMESTAMP VALIDATION
# ============================================

import pandas as pd

# Convert timestamps without modifying df_all yet
start_utc = pd.to_datetime(
    df_all["session_start"],
    unit="ms",
    utc=True,
    errors="coerce"
)

end_utc = pd.to_datetime(
    df_all["session_end"],
    unit="ms",
    utc=True,
    errors="coerce"
)

print("Invalid session_start timestamps:", start_utc.isna().sum())
print("Invalid session_end timestamps:", end_utc.isna().sum())

print("\nEarliest session start:")
print(start_utc.min())

print("\nLatest session start:")
print(start_utc.max())

print("\nEarliest session end:")
print(end_utc.min())

print("\nLatest session end:")
print(end_utc.max())


# ============================================
# SESSION DURATION CONSISTENCY
# ============================================

calculated_duration = (
    end_utc - start_utc
).dt.total_seconds() / 60

timestamp_duration_difference = (
    calculated_duration - df_all["duration_minutes"]
)

print("\n========== DURATION VALIDATION ==========")

print(
    "Negative timestamp durations:",
    (calculated_duration < 0).sum()
)

print(
    "Zero timestamp durations:",
    (calculated_duration == 0).sum()
)

print(
    "Duration differences > 1 second:",
    (timestamp_duration_difference.abs() > (1 / 60)).sum()
)

print("\nCalculated duration statistics:")
print(calculated_duration.describe())

print("\nRecorded duration statistics:")
print(df_all["duration_minutes"].describe())


# ============================================
# OVERLAPPING SESSIONS
# ============================================

temp = df_all.copy()

temp["start_utc"] = start_utc
temp["end_utc"] = end_utc

temp = temp.sort_values(
    ["user_id", "start_utc"]
).reset_index(drop=True)

temp["previous_end_utc"] = (
    temp.groupby("user_id")["end_utc"].shift(1)
)

temp["session_gap_minutes"] = (
    temp["start_utc"] - temp["previous_end_utc"]
).dt.total_seconds() / 60

print("\n========== SESSION OVERLAPS ==========")

print(
    "Overlapping sessions:",
    (temp["session_gap_minutes"] < 0).sum()
)

print(
    "Zero-gap sessions:",
    (temp["session_gap_minutes"] == 0).sum()
)

print("\nSession gap statistics:")
print(temp["session_gap_minutes"].describe())

Invalid session_start timestamps: 0
Invalid session_end timestamps: 0

Earliest session start:
2026-04-09 05:53:43.406000+00:00

Latest session start:
2026-09-30 07:57:44.112000+00:00

Earliest session end:
2026-04-09 05:59:04.446000+00:00

Latest session end:
2026-09-30 08:05:30.638000+00:00

========== DURATION VALIDATION ==========
Negative timestamp durations: 0
Zero timestamp durations: 0
Duration differences > 1 second: 0

Calculated duration statistics:
count    5931.000000
mean        6.226700
std        12.495346
min         0.500000
25%         1.054083
50%         2.416583
75%         6.374708
max       380.283333
dtype: float64

Recorded duration statistics:
count    5931.000000
mean        6.226695
std        12.495288
min         0.500000
25%         1.050000
50%         2.420000
75%         6.375000
max       380.280000
Name: duration_minutes, dtype: float64

========== SESSION OVERLAPS ==========
Overlapping sessions: 246
Zero-gap sessions: 16

Session gap statistics:
count     5924.000000
mean        69.000958
std       1071.879253
min        -81.203117
25%          0.252554
50%          2.212967
75%         19.272079
max      62586.002650
Name: session_gap_minutes, dtype: float64

INSPECT OVERLAPPING SESSIONS

In [ ]:
# ============================================
# INSPECT OVERLAPPING SESSIONS
# ============================================

overlaps = temp[
    temp["session_gap_minutes"] < 0
].copy()

print("Overlapping records:", len(overlaps))

display(
    overlaps[
        [
            "user_id",
            "start_utc",
            "end_utc",
            "previous_end_utc",
            "session_gap_minutes",
            "app_label",
            "duration_minutes"
        ]
    ]
    .sort_values(
        ["user_id", "start_utc"]
    )
    .head(30)
)

Overlapping records: 246

,user_id,start_utc,end_utc,previous_end_utc,session_gap_minutes,app_label,duration_minutes
797,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-03 19:11:38+00:00,2026-05-03 19:12:10+00:00,2026-05-03 19:12:54.043000+00:00,-1.267383,Instagram,0.53
801,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-03 19:23:42+00:00,2026-05-03 19:24:31+00:00,2026-05-03 19:57:31.607000+00:00,-33.826783,Instagram,0.82
810,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-04 03:30:54+00:00,2026-05-04 09:51:11+00:00,2026-05-04 03:31:00.460000+00:00,-0.107667,Instagram,380.28
828,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-05 19:12:22+00:00,2026-05-05 19:13:24+00:00,2026-05-05 19:22:11.441000+00:00,-9.824017,Instagram,1.03
834,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-05 19:37:27+00:00,2026-05-05 20:13:37+00:00,2026-05-05 19:37:35.102000+00:00,-0.135033,Instagram,36.17
869,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-06 18:19:59+00:00,2026-05-06 18:20:29+00:00,2026-05-06 18:23:00+00:00,-3.016667,Instagram,0.50
1398,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 05:36:33.182000+00:00,2026-04-24 05:37:38.245000+00:00,2026-04-24 05:37:36.168000+00:00,-1.049767,YouTube,1.08
1400,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 05:38:46.510000+00:00,2026-04-24 05:54:31.528000+00:00,2026-04-24 05:54:29.451000+00:00,-15.715683,YouTube,15.75
1402,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:13:32.498000+00:00,2026-04-24 06:22:59.039000+00:00,2026-04-24 06:22:56.962000+00:00,-9.407733,YouTube,9.44
1404,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:28:56.696000+00:00,2026-04-24 06:29:46.089000+00:00,2026-04-24 06:29:44.012000+00:00,-0.788600,YouTube,0.82
1406,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:29:48.756000+00:00,2026-04-24 06:31:00.928000+00:00,2026-04-24 06:30:58.851000+00:00,-1.168250,YouTube,1.20
1408,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:31:35.259000+00:00,2026-04-24 06:32:47.322000+00:00,2026-04-24 06:32:45.245000+00:00,-1.166433,YouTube,1.20
1410,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:48:36.187000+00:00,2026-04-24 06:49:15.856000+00:00,2026-04-24 06:49:13.779000+00:00,-0.626533,Facebook,0.66
1412,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:49:21.004000+00:00,2026-04-24 07:19:18.661000+00:00,2026-04-24 07:19:16.584000+00:00,-29.926333,Facebook,29.96
1414,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:25:57.302000+00:00,2026-04-24 07:28:44.221000+00:00,2026-04-24 07:28:42.144000+00:00,-2.747367,Facebook,2.78
1416,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:34:55.484000+00:00,2026-04-24 07:42:15.846000+00:00,2026-04-24 07:42:13.769000+00:00,-7.304750,Facebook,7.34
1418,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:50:12.467000+00:00,2026-04-24 07:52:04.857000+00:00,2026-04-24 07:52:02.780000+00:00,-1.838550,Facebook,1.87
1420,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:01:18.530000+00:00,2026-04-24 08:03:59.016000+00:00,2026-04-24 08:03:56.939000+00:00,-2.640150,Facebook,2.67
1422,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:07:15.154000+00:00,2026-04-24 08:09:44.779000+00:00,2026-04-24 08:09:42.702000+00:00,-2.459133,Facebook,2.49
1424,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:15:58.672000+00:00,2026-04-24 08:17:57.367000+00:00,2026-04-24 08:17:55.290000+00:00,-1.943633,Instagram,1.98
1426,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:30:01.084000+00:00,2026-04-24 09:32:43.081000+00:00,2026-04-24 09:32:41.004000+00:00,-2.665333,Instagram,2.70
1428,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:34:32.021000+00:00,2026-04-24 09:35:15.475000+00:00,2026-04-24 09:35:13.398000+00:00,-0.689617,Facebook,0.72
1430,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:35:21.146000+00:00,2026-04-24 09:37:25.977000+00:00,2026-04-24 09:37:23.900000+00:00,-2.045900,Facebook,2.08
1432,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:58:44.549000+00:00,2026-04-24 10:00:40.163000+00:00,2026-04-24 10:00:38.086000+00:00,-1.892283,TikTok,1.93
1434,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 10:18:08.335000+00:00,2026-04-24 10:19:06.704000+00:00,2026-04-24 10:19:04.627000+00:00,-0.938200,Facebook,0.97
1436,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:31:56.752000+00:00,2026-04-24 11:33:22.527000+00:00,2026-04-24 11:33:20.450000+00:00,-1.394967,Facebook,1.43
1438,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:34:06.229000+00:00,2026-04-24 11:35:38.232000+00:00,2026-04-24 11:35:36.155000+00:00,-1.498767,Facebook,1.53
1440,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:38:32.635000+00:00,2026-04-24 11:39:14.822000+00:00,2026-04-24 11:39:12.745000+00:00,-0.668500,Facebook,0.70
1442,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 13:00:15.480000+00:00,2026-04-24 13:02:26.051000+00:00,2026-04-24 13:02:23.974000+00:00,-2.141567,Facebook,2.18
1444,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 13:02:32.608000+00:00,2026-04-24 13:04:55.536000+00:00,2026-04-24 13:04:53.459000+00:00,-2.347517,Facebook,2.38

In [ ]:
print("========== OVERLAPS BY USER ==========")

display(
    overlaps.groupby("user_id")
    .agg(
        overlapping_sessions=("user_id", "size"),
        mean_overlap_minutes=("session_gap_minutes", "mean"),
        maximum_overlap_minutes=("session_gap_minutes", "min")
    )
    .reset_index()
)

========== OVERLAPS BY USER ==========

,user_id,overlapping_sessions,mean_overlap_minutes,maximum_overlap_minutes
0,85bfc215-c24f-4814-aa00-6794f1a7278a,6,-8.029592,-33.826783
1,8cf97b0c-76c9-4d72-b617-759a955f969f,240,-5.480831,-81.203117

In [ ]:
print("========== OVERLAP APP PATTERNS ==========")

overlaps["previous_app"] = (
    temp.loc[overlaps.index - 1, "app_label"].values
)

display(
    overlaps.groupby(
        ["previous_app", "app_label"]
    )
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
    .head(20)
)

========== OVERLAP APP PATTERNS ==========

  previous_app  app_label  count
0     Facebook   Facebook    154
2    Instagram  Instagram     59
5      YouTube    YouTube     26
3     Snapchat   Snapchat      4
4       TikTok     TikTok      2
1     Facebook  Instagram      1

In [ ]:
print("========== OVERLAP MAGNITUDE ==========")

overlap_magnitude = (
    overlaps["session_gap_minutes"]
    .abs()
)

print(overlap_magnitude.describe())

print("\nOverlap duration ranges:")

bins = [-float("inf"), 1, 5, 10, 30, 60, float("inf")]

labels = [
    "<= 1 min",
    "1–5 min",
    "5–10 min",
    "10–30 min",
    "30–60 min",
    "> 60 min"
]

display(
    pd.cut(
        overlap_magnitude,
        bins=bins,
        labels=labels
    )
    .value_counts()
    .sort_index()
    .rename_axis("overlap_size")
    .reset_index(name="count")
)

========== OVERLAP MAGNITUDE ==========
count    246.000000
mean       5.542996
std       10.994173
min        0.001767
25%        0.848133
50%        1.850075
75%        4.967542
max       81.203117
Name: session_gap_minutes, dtype: float64

Overlap duration ranges:

  overlap_size  count
0     <= 1 min     74
1      1–5 min    111
2     5–10 min     30
3    10–30 min     23
4    30–60 min      5
5     > 60 min      3

In [ ]:
# Make a diagnostic copy
overlap_check = df_all.copy()

overlap_check["start_utc"] = pd.to_datetime(
    overlap_check["session_start"],
    unit="ms",
    utc=True
)

overlap_check["end_utc"] = pd.to_datetime(
    overlap_check["session_end"],
    unit="ms",
    utc=True
)

# Sort by user, app, and start time
overlap_check = overlap_check.sort_values(
    ["user_id", "app_label", "start_utc"]
).reset_index(drop=True)

# Previous session for the same user + app
overlap_check["previous_same_app_start"] = (
    overlap_check
    .groupby(["user_id", "app_label"])["start_utc"]
    .shift(1)
)

overlap_check["previous_same_app_end"] = (
    overlap_check
    .groupby(["user_id", "app_label"])["end_utc"]
    .shift(1)
)

# Actual interval intersection:
# max(starts) -> min(ends)
intersection_start = overlap_check[
    ["start_utc", "previous_same_app_start"]
].max(axis=1)

intersection_end = overlap_check[
    ["end_utc", "previous_same_app_end"]
].min(axis=1)

overlap_check["actual_overlap_minutes"] = (
    (intersection_end - intersection_start)
    .dt.total_seconds() / 60
).clip(lower=0)

# Fraction of the CURRENT session that is actually overlapped
overlap_check["actual_overlap_fraction"] = (
    overlap_check["actual_overlap_minutes"]
    / overlap_check["duration_minutes"]
)

# Keep only genuine intersections
actual_overlaps = overlap_check[
    overlap_check["actual_overlap_minutes"] > 0
].copy()

print("Actual same-app overlapping sessions:", len(actual_overlaps))

print("\nActual overlap fraction:")
print(
    actual_overlaps["actual_overlap_fraction"].describe()
)

print(
    "\nActual overlap >= 90%:",
    (
        actual_overlaps["actual_overlap_fraction"] >= 0.90
    ).sum()
)

print(
    "Actual overlap < 90%:",
    (
        actual_overlaps["actual_overlap_fraction"] < 0.90
    ).sum()
)

print(
    "\nActual overlap > 100%:",
    (
        actual_overlaps["actual_overlap_fraction"] > 1.0
    ).sum()
)

Actual same-app overlapping sessions: 272

Actual overlap fraction:
count    272.000000
mean       0.907015
std        0.258827
min        0.000283
25%        0.963870
50%        0.985006
75%        0.995493
max        1.006289
Name: actual_overlap_fraction, dtype: float64

Actual overlap >= 90%: 251
Actual overlap < 90%: 21

Actual overlap > 100%: 15

In [ ]:
over_100 = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] > 1.0
].copy()

cols = [
    "user_id",
    "app_label",
    "start_utc",
    "end_utc",
    "duration_minutes",
    "previous_same_app_start",
    "previous_same_app_end",
    "actual_overlap_minutes",
    "actual_overlap_fraction"
]

print(
    over_100[cols]
    .sort_values("actual_overlap_fraction", ascending=False)
    .to_string(index=False)
)

                             user_id app_label                        start_utc                          end_utc  duration_minutes          previous_same_app_start            previous_same_app_end  actual_overlap_minutes  actual_overlap_fraction
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-03 19:11:38+00:00        2026-05-03 19:12:10+00:00              0.53 2026-05-03 19:10:35.588000+00:00 2026-05-03 19:12:54.043000+00:00                0.533333                 1.006289
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67  Facebook 2026-09-26 15:30:41.251000+00:00 2026-09-26 15:31:22.223000+00:00              0.68                              NaT                              NaT                0.682867                 1.004216
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-05 19:12:22+00:00        2026-05-05 19:13:24+00:00              1.03 2026-05-05 19:10:46.942000+00:00 2026-05-05 19:22:11.441000+00:00                1.033333                 1.003236
f5e00193-6fb8-4767-ba5e-5c824dc24c89    TikTok 2026-09-23 06:58:02.956000+00:00 2026-09-23 06:58:51.700000+00:00              0.81                              NaT                              NaT                0.812400                 1.002963
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-17 10:18:14.939000+00:00 2026-04-17 10:19:07.258000+00:00              0.87                              NaT                              NaT                0.871983                 1.002280
e7642be3-461d-4c8e-98cd-0eccc76764ec Twitter/X 2026-09-24 17:31:25.124000+00:00 2026-09-24 17:34:15.154000+00:00              2.83                              NaT                              NaT                2.833833                 1.001355
d5a62f7a-97c9-481c-83be-f0a06b70cad9  Facebook 2026-04-16 19:07:01.509000+00:00 2026-04-16 19:09:11.825000+00:00              2.17                              NaT                              NaT                2.171933                 1.000891
8cf97b0c-76c9-4d72-b617-759a955f969f  Snapchat 2026-04-25 07:46:57.388000+00:00 2026-04-25 07:47:40.025000+00:00              0.71                              NaT                              NaT                0.710617                 1.000869
e7642be3-461d-4c8e-98cd-0eccc76764ec    TikTok 2026-09-22 19:31:52.389000+00:00 2026-09-22 19:36:20.176000+00:00              4.46                              NaT                              NaT                4.463117                 1.000699
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4   YouTube 2026-09-10 18:19:11.005000+00:00 2026-09-10 18:23:39.985000+00:00              4.48                              NaT                              NaT                4.483000                 1.000670
85bfc215-c24f-4814-aa00-6794f1a7278a   YouTube 2026-04-12 12:07:52.362000+00:00 2026-04-12 12:14:38.197000+00:00              6.76                              NaT                              NaT                6.763917                 1.000579
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 Instagram 2026-09-02 12:42:42.152000+00:00 2026-09-02 12:51:08.201000+00:00              8.43                              NaT                              NaT                8.434150                 1.000492
e7642be3-461d-4c8e-98cd-0eccc76764ec  Facebook 2026-09-22 19:06:43.060000+00:00 2026-09-22 19:09:29.936000+00:00              2.78                              NaT                              NaT                2.781267                 1.000456
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-17 16:44:29.899000+00:00 2026-04-17 16:53:38.397000+00:00              9.14                              NaT                              NaT                9.141633                 1.000179
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram 2026-04-09 05:53:43.406000+00:00 2026-04-09 05:59:04.446000+00:00              5.35                              NaT                              NaT                5.350667                 1.000125

In [ ]:
partial_overlaps = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] < 0.90
].copy()

cols = [
    "user_id",
    "app_label",
    "start_utc",
    "end_utc",
    "duration_minutes",
    "previous_same_app_start",
    "previous_same_app_end",
    "actual_overlap_minutes",
    "actual_overlap_fraction"
]

print(
    partial_overlaps[
        cols
    ]
    .sort_values(
        ["user_id", "start_utc"]
    )
    .to_string(index=False)
)

                             user_id app_label                        start_utc                          end_utc  duration_minutes          previous_same_app_start            previous_same_app_end  actual_overlap_minutes  actual_overlap_fraction
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-04 03:30:54+00:00        2026-05-04 09:51:11+00:00            380.28 2026-05-04 03:28:32.196000+00:00 2026-05-04 03:31:00.460000+00:00                0.107667                 0.000283
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-05 19:37:27+00:00        2026-05-05 20:13:37+00:00             36.17 2026-05-05 19:34:44.514000+00:00 2026-05-05 19:37:35.102000+00:00                0.135033                 0.003733
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 05:34:55.703000+00:00 2026-04-25 05:51:29.763000+00:00             16.57 2026-04-25 05:33:37.593000+00:00 2026-04-25 05:34:57.775000+00:00                0.034533                 0.002084
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 15:38:02.069000+00:00 2026-04-25 15:41:51.498000+00:00              3.82 2026-04-25 15:36:53.479000+00:00 2026-04-25 15:38:04.142000+00:00                0.034550                 0.009045
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 18:25:52.696000+00:00 2026-04-25 18:27:47.356000+00:00              1.91 2026-04-25 18:23:12.050000+00:00 2026-04-25 18:25:54.768000+00:00                0.034533                 0.018080
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 09:47:50.645000+00:00 2026-04-26 09:48:34.592000+00:00              0.73 2026-04-26 09:46:56.311000+00:00 2026-04-26 09:47:52.717000+00:00                0.034533                 0.047306
8cf97b0c-76c9-4d72-b617-759a955f969f Instagram 2026-04-26 17:04:55.322000+00:00 2026-04-26 17:46:35.058000+00:00             41.66 2026-04-26 17:01:19.849000+00:00 2026-04-26 17:04:57.280000+00:00                0.032633                 0.000783
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:20:20.343000+00:00 2026-04-26 18:23:44.640000+00:00              3.40 2026-04-26 18:17:42.888000+00:00 2026-04-26 18:20:22.415000+00:00                0.034533                 0.010157
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:31:40.609000+00:00 2026-04-26 18:46:09.663000+00:00             14.48 2026-04-26 18:30:33.566000+00:00 2026-04-26 18:31:42.678000+00:00                0.034483                 0.002381
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:46:09.670000+00:00 2026-04-26 18:48:32.072000+00:00              2.37 2026-04-26 18:31:42.686000+00:00 2026-04-26 18:46:11.740000+00:00                0.034500                 0.014557
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:49:57.413000+00:00 2026-04-26 18:52:30.906000+00:00              2.56 2026-04-26 18:48:47.849000+00:00 2026-04-26 18:49:57.519000+00:00                0.001767                 0.000690
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 19:14:19.729000+00:00 2026-04-26 19:21:05.372000+00:00              6.76 2026-04-26 19:13:50.008000+00:00 2026-04-26 19:14:21.801000+00:00                0.034533                 0.005108
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-26 21:01:58.555000+00:00 2026-04-26 21:04:47.542000+00:00              2.82 2026-04-26 19:40:46.303000+00:00 2026-04-26 21:02:00.567000+00:00                0.033533                 0.011891
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-26 21:04:47.607000+00:00 2026-04-26 21:15:18.219000+00:00             10.51 2026-04-26 21:02:00.632000+00:00 2026-04-26 21:04:49.619000+00:00                0.033533                 0.003191
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 10:08:26.389000+00:00 2026-04-27 10:14:07.097000+00:00              5.68 2026-04-27 10:07:53.346000+00:00 2026-04-27 10:08:28.460000+00:00                0.034517                 0.006077
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 10:14:07.101000+00:00 2026-04-27 10:14:44.483000+00:00              0.62 2026-04-27 10:08:28.466000+00:00 2026-04-27 10:14:09.174000+00:00                0.034550                 0.055726
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 19:25:30.299000+00:00 2026-04-27 19:26:53.007000+00:00              1.38 2026-04-27 18:58:34.457000+00:00 2026-04-27 19:25:32.350000+00:00                0.034183                 0.024771
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-28 12:58:57.973000+00:00 2026-04-28 13:05:09.150000+00:00              6.19 2026-04-28 12:57:58.028000+00:00 2026-04-28 12:59:00.045000+00:00                0.034533                 0.005579
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-28 14:12:52.699000+00:00 2026-04-28 14:15:29.612000+00:00              2.62 2026-04-28 14:12:05.286000+00:00 2026-04-28 14:12:54.773000+00:00                0.034567                 0.013193
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-29 13:28:45.155000+00:00 2026-04-29 13:29:35.993000+00:00              0.85 2026-04-29 13:28:12.775000+00:00 2026-04-29 13:28:47.228000+00:00                0.034550                 0.040647
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-30 21:00:36.969000+00:00 2026-04-30 21:01:11.429000+00:00              0.57 2026-04-30 21:00:05.223000+00:00 2026-04-30 21:00:39.038000+00:00                0.034483                 0.060497

In [ ]:
high_overlap = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] >= 0.90
].copy()

high_overlap["current_contained_in_previous"] = (
    (high_overlap["start_utc"] >= high_overlap["previous_same_app_start"]) &
    (high_overlap["end_utc"] <= high_overlap["previous_same_app_end"])
)

high_overlap["previous_contained_in_current"] = (
    (high_overlap["previous_same_app_start"] >= high_overlap["start_utc"]) &
    (high_overlap["previous_same_app_end"] <= high_overlap["end_utc"])
)

print(
    "Current contained in previous:",
    high_overlap["current_contained_in_previous"].sum()
)

print(
    "Previous contained in current:",
    high_overlap["previous_contained_in_current"].sum()
)

print(
    "Neither fully contained:",
    (
        ~high_overlap["current_contained_in_previous"] &
        ~high_overlap["previous_contained_in_current"]
    ).sum()
)

Current contained in previous: 4
Previous contained in current: 0
Neither fully contained: 247

In [ ]:
print("\nBy user:")
print(
    high_overlap.groupby("user_id").size()
)

print("\nBy app:")
print(
    high_overlap.groupby("app_label").size()
)

By user:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4      2
85bfc215-c24f-4814-aa00-6794f1a7278a      9
8cf97b0c-76c9-4d72-b617-759a955f969f    225
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67      5
d5a62f7a-97c9-481c-83be-f0a06b70cad9      4
e7642be3-461d-4c8e-98cd-0eccc76764ec      5
f5e00193-6fb8-4767-ba5e-5c824dc24c89      1
dtype: int64

By app:
app_label
Facebook     143
Instagram     62
Snapchat       7
TikTok         7
Twitter/X      3
YouTube       29
dtype: int64

In [ ]:
high_overlap["previous_duration_minutes"] = (
    (
        high_overlap["previous_same_app_end"]
        - high_overlap["previous_same_app_start"]
    )
    .dt.total_seconds() / 60
)

high_overlap["duration_ratio_to_previous"] = (
    high_overlap["duration_minutes"]
    / high_overlap["previous_duration_minutes"]
)

print("\nCurrent duration:")
print(
    high_overlap["duration_minutes"].describe()
)

print("\nPrevious duration:")
print(
    high_overlap["previous_duration_minutes"].describe()
)

print("\nCurrent / previous duration ratio:")
print(
    high_overlap["duration_ratio_to_previous"].describe()
)

Current duration:
count    251.000000
mean       6.963267
std       20.594475
min        0.500000
25%        1.030000
50%        2.100000
75%        5.515000
max      283.270000
Name: duration_minutes, dtype: float64

Previous duration:
count    224.000000
mean       6.147869
std       11.410117
min        0.503700
25%        1.090621
50%        2.099892
75%        5.680663
max       81.237733
Name: previous_duration_minutes, dtype: float64

Current / previous duration ratio:
count    224.000000
mean       0.983835
std        0.118110
min        0.022474
25%        0.998528
50%        0.999894
75%        1.000630
max        1.009174
Name: duration_ratio_to_previous, dtype: float64

In [ ]:
# Calculate previous same-app duration for all records
overlap_check["previous_duration_minutes"] = (
    (
        overlap_check["previous_same_app_end"]
        - overlap_check["previous_same_app_start"]
    )
    .dt.total_seconds() / 60
)

overlap_check["duration_ratio_to_previous"] = (
    overlap_check["duration_minutes"]
    / overlap_check["previous_duration_minutes"]
)

# Candidate redundant sessions
potential_duplicates = overlap_check[
    (overlap_check["actual_overlap_fraction"] >= 0.90) &
    (overlap_check["duration_ratio_to_previous"] >= 0.90) &
    (overlap_check["duration_ratio_to_previous"] <= 1.10)
].copy()

print("Potential redundant sessions:", len(potential_duplicates))

print(
    "Percentage of all sessions:",
    round(len(potential_duplicates) / len(df_all) * 100, 2),
    "%"
)

print("\nBy user:")
print(
    potential_duplicates["user_id"].value_counts()
)

print("\nBy app:")
print(
    potential_duplicates["app_label"].value_counts()
)

Potential redundant sessions: 220
Percentage of all sessions: 3.71 %

By user:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    220
Name: count, dtype: int64

By app:
app_label
Facebook     138
Instagram     52
YouTube       24
Snapchat       4
TikTok         2
Name: count, dtype: int64

CREATE CANONICAL DATASET THAT REMOVES REDUNDANT SESSIONS

In [ ]:
# Create a clean derived copy
df_sessions = overlap_check.copy()

# Flag potential redundant sessions
df_sessions["is_potential_redundant"] = (
    (df_sessions["actual_overlap_fraction"] >= 0.90) &
    (df_sessions["duration_ratio_to_previous"] >= 0.90) &
    (df_sessions["duration_ratio_to_previous"] <= 1.10)
)

print("Total sessions:", len(df_sessions))
print(
    "Potential redundant:",
    df_sessions["is_potential_redundant"].sum()
)
print(
    "Potential redundant (%):",
    round(
        df_sessions["is_potential_redundant"].mean() * 100,
        2
    )
)

Total sessions: 5931
Potential redundant: 220
Potential redundant (%): 3.71

In [ ]:
df_sessions_clean = df_sessions[
    ~df_sessions["is_potential_redundant"]
].copy()

df_sessions_clean = (
    df_sessions_clean
    .sort_values(["user_id", "start_utc"])
    .reset_index(drop=True)
)

print("Raw sessions:", len(df_sessions))
print("Clean sessions:", len(df_sessions_clean))
print(
    "Removed from analysis:",
    len(df_sessions) - len(df_sessions_clean)
)

Raw sessions: 5931
Clean sessions: 5711
Removed from analysis: 220

ADDING QUALITY FLAGS - To never lose track of a record

In [ ]:
# Start from the raw session dataset with the 220 potential
# redundant records excluded.
df_sessions_clean = df_sessions[
    ~df_sessions["is_potential_redundant"]
].copy()

# Sort chronologically within each user + app
df_sessions_clean = (
    df_sessions_clean
    .sort_values(["user_id", "app_label", "start_utc"])
    .reset_index(drop=True)
)

# Previous same-app session end
df_sessions_clean["previous_same_app_end_clean"] = (
    df_sessions_clean
    .groupby(["user_id", "app_label"])["end_utc"]
    .shift(1)
)

# Actual remaining overlap
df_sessions_clean["remaining_overlap_minutes"] = (
    (
        df_sessions_clean["previous_same_app_end_clean"]
        - df_sessions_clean["start_utc"]
    )
    .dt.total_seconds() / 60
).clip(lower=0)

# Flag residual overlaps
df_sessions_clean["has_same_app_overlap"] = (
    df_sessions_clean["remaining_overlap_minutes"] > 0
)

# Categorize
df_sessions_clean["overlap_category"] = "none"

df_sessions_clean.loc[
    df_sessions_clean["has_same_app_overlap"],
    "overlap_category"
] = "residual_overlap"

print("Canonical sessions:", len(df_sessions_clean))

print("\nOverlap categories:")
print(
    df_sessions_clean["overlap_category"].value_counts()
)

print("\nResidual overlaps:")
print(
    df_sessions_clean["remaining_overlap_minutes"]
    .loc[df_sessions_clean["has_same_app_overlap"]]
    .describe()
)

Canonical sessions: 5711

Overlap categories:
overlap_category
none                5705
residual_overlap       6
Name: count, dtype: int64

Residual overlaps:
count     6.000000
mean      8.029592
std      13.150307
min       0.107667
25%       0.418121
50%       2.142025
75%       8.122179
max      33.826783
Name: remaining_overlap_minutes, dtype: float64

CANONICAL TEMPORAL COLUMNS

In [ ]:
# ============================================================
# STEP 1: CANONICAL TEMPORAL REPRESENTATION
# ============================================================

df_features = df_sessions_clean.copy()

# Merge 'is_schedule_conflict' from df_student_activities into df_features
# Ensure 'user_id' and 'session_start' are common keys for merging
df_features = pd.merge(
    df_features,
    df_student_activities[['user_id', 'session_start', 'is_schedule_conflict']],
    on=['user_id', 'session_start'],
    how='left'
)

# Convert timestamps from Unix milliseconds → UTC
df_features["timestamp_utc"] = pd.to_datetime(
    df_features["session_start"],
    unit="ms",
    utc=True
)

df_features["session_end_utc"] = pd.to_datetime(
    df_features["session_end"],
    unit="ms",
    utc=True
)

# Convert UTC → Kenya local time
df_features["timestamp_local"] = (
    df_features["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

df_features["session_end_local"] = (
    df_features["session_end_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# Canonical local calendar fields
df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

df_features["local_hour"] = (
    df_features["timestamp_local"].dt.hour
)

df_features["local_minute"] = (
    df_features["timestamp_local"].dt.minute
)

df_features["day_of_week"] = (
    df_features["timestamp_local"].dt.day_name()
)

# Sort chronologically within participant
df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

print("Rows:", len(df_features))
print("Users:", df_features["user_id"].nunique())

print("\nDate range:")
print(df_features["local_date"].min(), "→", df_features["local_date"].max())

print("\nTimezone:")
print(df_features["timestamp_local"].dt.tz)

Rows: 5711
Users: 7

Date range:
2026-04-09 → 2026-09-30

Timezone:
Africa/Nairobi

CALCULATE SESSION GAP

In [ ]:
# ============================================================
# STEP 2: SESSION GAP
# ============================================================

df_features["previous_session_end"] = (
    df_features
    .groupby("user_id")["session_end_local"]
    .shift(1)
)

df_features["session_gap_minutes"] = (
    (
        df_features["timestamp_local"]
        - df_features["previous_session_end"]
    )
    .dt.total_seconds() / 60
)

print(df_features["session_gap_minutes"].describe())

print("\nNegative gaps:")
print(
    (df_features["session_gap_minutes"] < 0).sum()
)

print("\nMissing gaps:")
print(
    df_features["session_gap_minutes"].isna().sum()
)

count     5704.000000
mean        71.894120
std       1092.252741
min        -33.826783
25%          0.344075
50%          2.550275
75%         21.127308
max      62586.002650
Name: session_gap_minutes, dtype: float64

Negative gaps:
6

Missing gaps:
7

DETERMINE DAILY CAUSAL FEATURES FOR BASELINE DERIVATION

In [ ]:
# ============================================================
# STEP 3: CAUSAL DAILY FEATURES
# ============================================================

df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Number of sessions that occurred earlier on the same day
df_features["prior_daily_session_count"] = (
    df_features
    .groupby(["user_id", "local_date"])
    .cumcount()
)

# Usage accumulated before the current session
df_features["prior_daily_usage_minutes"] = (
    df_features
    .groupby(["user_id", "local_date"])["duration_minutes"]
    .transform(
        lambda s: s.shift(1).fillna(0).cumsum()
    )
)

print(
    df_features[
        [
            "user_id",
            "local_date",
            "timestamp_local",
            "duration_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes"
        ]
    ].head(15)
)

                                 user_id  local_date  \
0   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
1   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
2   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
3   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
4   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
5   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
6   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
7   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
8   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
9   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
10  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
11  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
12  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
13  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
14  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02

                    timestamp_local  duration_minutes  \
0  2026-09-02 15:42:42.152000+03:00              8.43
1  2026-09-02 17:31:20.020000+03:00              0.62
2  2026-09-02 17:32:57.877000+03:00              2.61
3  2026-09-02 17:35:34.725000+03:00              0.72
4  2026-09-02 17:37:01.411000+03:00              0.64
5  2026-09-02 17:38:05.397000+03:00              1.26
6  2026-09-02 17:39:21.029000+03:00              0.93
7  2026-09-02 17:45:07.658000+03:00              0.90
8  2026-09-02 17:46:18.607000+03:00              2.19
9  2026-09-02 17:48:30.079000+03:00              1.19
10 2026-09-02 19:15:50.864000+03:00              2.98
11 2026-09-02 19:20:52.009000+03:00              3.63
12 2026-09-02 19:24:39.124000+03:00              2.74
13 2026-09-02 19:28:46.339000+03:00              2.86
14 2026-09-02 19:31:40.960000+03:00              1.73

    prior_daily_session_count  prior_daily_usage_minutes
0                           0                       0.00
1                           1                       8.43
2                           2                       9.05
3                           3                      11.66
4                           4                      12.38
5                           5                      13.02
6                           6                      14.28
7                           7                      15.21
8                           8                      16.11
9                           9                      18.30
10                         10                      19.49
11                         11                      22.47
12                         12                      26.10
13                         13                      28.84
14                         14                      31.70

BUILD TOTAL PARTICIPANTS USAGE BASELINE

In [ ]:
# ============================================================
# STEP 4: INDIVIDUAL DURATION BASELINE
# ============================================================

df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Historical median based ONLY on previous sessions
df_features["previous_median_duration"] = (
    df_features
    .groupby("user_id")["duration_minutes"]
    .transform(
        lambda s:
        s.shift(1)
         .expanding(min_periods=5)
         .median()
    )
)

# Absolute deviation from personal baseline
df_features["duration_baseline_deviation"] = (
    df_features["duration_minutes"]
    - df_features["previous_median_duration"]
)

# Relative deviation from personal baseline
df_features["duration_baseline_ratio"] = (
    df_features["duration_minutes"]
    / df_features["previous_median_duration"].replace(0, np.nan)
)

print(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(20)
)

                                 user_id                  timestamp_local  \
0   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 15:42:42.152000+03:00
1   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:31:20.020000+03:00
2   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:32:57.877000+03:00
3   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:35:34.725000+03:00
4   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:37:01.411000+03:00
5   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:38:05.397000+03:00
6   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:39:21.029000+03:00
7   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:45:07.658000+03:00
8   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:46:18.607000+03:00
9   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:48:30.079000+03:00
10  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:15:50.864000+03:00
11  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:20:52.009000+03:00
12  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:24:39.124000+03:00
13  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:28:46.339000+03:00
14  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:31:40.960000+03:00
15  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:11:49.254000+03:00
16  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:18:14.014000+03:00
17  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:29:48.483000+03:00
18  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:40:32.214000+03:00
19  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:41:37.829000+03:00

    duration_minutes  previous_median_duration  duration_baseline_deviation  \
0               8.43                       NaN                          NaN
1               0.62                       NaN                          NaN
2               2.61                       NaN                          NaN
3               0.72                       NaN                          NaN
4               0.64                       NaN                          NaN
5               1.26                     0.720                        0.540
6               0.93                     0.990                       -0.060
7               0.90                     0.930                       -0.030
8               2.19                     0.915                        1.275
9               1.19                     0.930                        0.260
10              2.98                     1.060                        1.920
11              3.63                     1.190                        2.440
12              2.74                     1.225                        1.515
13              2.86                     1.260                        1.600
14              1.73                     1.725                        0.005
15              2.77                     1.730                        1.040
16              1.01                     1.960                       -0.950
17              3.59                     1.730                        1.860
18              0.95                     1.960                       -1.010
19              2.65                     1.730                        0.920

    duration_baseline_ratio
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                  1.750000
6                  0.939394
7                  0.967742
8                  2.393443
9                  1.279570
10                 2.811321
11                 3.050420
12                 2.236735
13                 2.269841
14                 1.002899
15                 1.601156
16                 0.515306
17                 2.075145
18                 0.484694
19                 1.531792

ENSURING NO DATA LEAKAGE

In [ ]:
# ============================================================
# STEP 5: BASIC FEATURE SANITY CHECK
# ============================================================

feature_columns = [
    "session_gap_minutes",
    "prior_daily_session_count",
    "prior_daily_usage_minutes",
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio"
]

print("Feature summary:")
print(
    df_features[feature_columns].describe()
)

print("\nMissing values:")
print(
    df_features[feature_columns].isna().sum()
)

Feature summary:
       session_gap_minutes  prior_daily_session_count  \
count          5704.000000                5711.000000
mean             71.894120                  19.994397
std            1092.252741                  17.608596
min             -33.826783                   0.000000
25%               0.344075                   7.000000
50%               2.550275                  16.000000
75%              21.127308                  29.000000
max           62586.002650                 119.000000

       prior_daily_usage_minutes  previous_median_duration  \
count                5711.000000               5676.000000
mean                  111.657155                  2.505791
std                    91.959292                  0.967712
min                     0.000000                  0.720000
25%                    37.300000                  2.100000
50%                    95.960000                  2.420000
75%                   161.505000                  2.455000
max                   482.900000                  7.780000

       duration_baseline_deviation  duration_baseline_ratio
count                  5676.000000              5676.000000
mean                      3.745278                 2.561130
std                      12.495269                 4.780675
min                      -7.010000                 0.068456
25%                      -1.220000                 0.477212
50%                       0.105000                 1.046571
75%                       3.851250                 2.624127
max                     376.615000               104.422222

Missing values:
session_gap_minutes             7
prior_daily_session_count       0
prior_daily_usage_minutes       0
previous_median_duration       35
duration_baseline_deviation    35
duration_baseline_ratio        35
dtype: int64

In [ ]:
# Check first session for each user
first_sessions = (
    df_features
    .groupby("user_id")
    .head(1)
)

print(
    first_sessions[
        [
            "user_id",
            "session_gap_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes",
            "previous_median_duration"
        ]
    ].to_string(index=False)
)

                             user_id  session_gap_minutes  prior_daily_session_count  prior_daily_usage_minutes  previous_median_duration
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4                  NaN                          0                        0.0                       NaN
85bfc215-c24f-4814-aa00-6794f1a7278a                  NaN                          0                        0.0                       NaN
8cf97b0c-76c9-4d72-b617-759a955f969f                  NaN                          0                        0.0                       NaN
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67                  NaN                          0                        0.0                       NaN
d5a62f7a-97c9-481c-83be-f0a06b70cad9                  NaN                          0                        0.0                       NaN
e7642be3-461d-4c8e-98cd-0eccc76764ec                  NaN                          0                        0.0                       NaN
f5e00193-6fb8-4767-ba5e-5c824dc24c89                  NaN                          0                        0.0                       NaN

In [ ]:
# ============================================================
# TIMETABLE: PREPARE TIME INTERVALS
# ============================================================

day_to_number = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

timetable_df["day_of_week_num"] = (
    timetable_df["day"].map(day_to_number)
)

timetable_df["start_minute"] = (
    pd.to_datetime(
        timetable_df["start_time"],
        format="%H:%M"
    ).dt.hour * 60
    +
    pd.to_datetime(
        timetable_df["start_time"],
        format="%H:%M"
    ).dt.minute
)

timetable_df["end_minute"] = (
    pd.to_datetime(
        timetable_df["end_time"],
        format="%H:%M"
    ).dt.hour * 60
    +
    pd.to_datetime(
        timetable_df["end_time"],
        format="%H:%M"
    ).dt.minute
)

print(
    timetable_df[
        [
            "day",
            "start_time",
            "end_time",
            "day_of_week_num",
            "start_minute",
            "end_minute"
        ]
    ].to_string(index=False)
)

      day start_time end_time day_of_week_num  start_minute  end_minute
   Monday      08:15    10:15               0           495         615
   Monday      10:15    12:15               0           615         735
   Monday      13:15    14:15               0           795         855
   Monday      15:15    17:15               0           915        1035
  Tuesday      08:15    10:15               1           495         615
  Tuesday      10:15    11:15               1           615         675
  Tuesday      11:15    12:15               1           675         735
  Tuesday      13:15    15:15               1           795         915
Wednesday      08:15    10:15               2           495         615
Wednesday      11:15    12:15               2           675         735
Wednesday      13:15    15:15               2           795         915
Wednesday      15:15    17:15               2           915        1035
 Thursday      08:15    10:15               3           495         615
 Thursday      11:15    13:15               3           675         795
 Thursday      15:15    17:15               3           915        1035
   Friday      08:15    10:15               4           495         615
   Friday      14:15    17:15               4           855        1035

In [ ]:
# ============================================================
# RECOMPUTE SCHEDULE CONFLICT FOR ALL CANONICAL SESSIONS
# ============================================================

def evaluate_schedule_conflict(timestamp, timetable):
    weekday = timestamp.weekday()
    minute_of_day = timestamp.hour * 60 + timestamp.minute

    day_events = timetable[
        timetable["day_of_week_num"] == weekday
    ]

    conflict = day_events[
        (day_events["start_minute"] <= minute_of_day) &
        (minute_of_day < day_events["end_minute"])
    ]

    return int(not conflict.empty)


df_features["is_schedule_conflict"] = (
    df_features["timestamp_local"]
    .apply(
        lambda timestamp:
        evaluate_schedule_conflict(timestamp, timetable_df)
    )
    .astype(int)
)

print("Rows:", len(df_features))

print("\nSchedule conflict values:")
print(
    df_features["is_schedule_conflict"]
    .value_counts(dropna=False)
)

print("\nMissing values:")
print(
    df_features["is_schedule_conflict"].isna().sum()
)

print("\nConflict percentage:")
print(
    df_features["is_schedule_conflict"].mean() * 100
)

Rows: 5711

Schedule conflict values:
is_schedule_conflict
0    4165
1    1546
Name: count, dtype: int64

Missing values:
0

Conflict percentage:
27.07056557520574

In [ ]:
# -----------------------------------------
# Additional session-level features
# -----------------------------------------

# Prior usage of the current app today
df_features["prior_app_usage_minutes"] = (
    df_features
    .groupby(["user_id", "local_date", "app_label"])["duration_minutes"]
    .transform(
        lambda s: s.shift(1).fillna(0).cumsum()
    )
)

# Prior number of sessions for the current app today
df_features["prior_app_session_count"] = (
    df_features
    .groupby(["user_id", "local_date", "app_label"])
    .cumcount()
)

# Cyclical time-of-day features
df_features["hour_sin"] = np.sin(
    2 * np.pi * df_features["local_hour"] / 24
)

df_features["hour_cos"] = np.cos(
    2 * np.pi * df_features["local_hour"] / 24
)

# Cyclical day-of-week features
day_number = df_features["timestamp_local"].dt.dayofweek

df_features["day_sin"] = np.sin(
    2 * np.pi * day_number / 7
)

df_features["day_cos"] = np.cos(
    2 * np.pi * day_number / 7
)

# Late-night context
df_features["is_late_night"] = (
    (df_features["local_hour"] >= 22) |
    (df_features["local_hour"] < 6)
).astype(int)

# Rapid return indicator
df_features["rapid_reopen"] = (
    df_features["session_gap_minutes"] <= 2
).astype(int)

In [ ]:
new_features = [
    "prior_app_usage_minutes",
    "prior_app_session_count",
    "hour_sin",
    "hour_cos",
    "day_sin",
    "day_cos",
    "is_late_night",
    "rapid_reopen"
]

df_features[new_features].describe()

,prior_app_usage_minutes,prior_app_session_count,hour_sin,hour_cos,day_sin,day_cos,is_late_night,rapid_reopen
count,5711.000000,5711.000000,5711.000000,5711.000000,5711.000000,5711.000000,5711.000000,5711.000000
mean,52.864708,10.684644,-0.288709,-0.176466,0.059922,-0.023369,0.144633,0.461916
std,67.505846,13.035967,0.644551,0.685723,0.699628,0.711729,0.351761,0.498591
min,0.000000,0.000000,-1.000000,-1.000000,-0.974928,-0.900969,0.000000,0.000000
25%,8.720000,3.000000,-0.866025,-0.866025,-0.433884,-0.900969,0.000000,0.000000
50%,29.130000,7.000000,-0.500000,-0.258819,0.000000,-0.222521,0.000000,0.000000
75%,69.120000,14.000000,0.258819,0.500000,0.781831,0.623490,0.000000,1.000000
max,478.730000,119.000000,1.000000,1.000000,0.974928,1.000000,1.000000,1.000000

In [ ]:
df_features[
    [
        "duration_minutes",
        "session_gap_minutes",
        "prior_daily_session_count",
        "prior_daily_usage_minutes",
        "previous_median_duration",
        "duration_baseline_deviation",
        "duration_baseline_ratio",
        "prior_app_usage_minutes",
        "prior_app_session_count",
        "is_schedule_conflict",
        "is_late_night",
        "rapid_reopen"
    ]
].head(10)

,duration_minutes,session_gap_minutes,prior_daily_session_count,prior_daily_usage_minutes,previous_median_duration,duration_baseline_deviation,duration_baseline_ratio,prior_app_usage_minutes,prior_app_session_count,is_schedule_conflict,is_late_night,rapid_reopen
0,8.43,NaN,0,0.00,NaN,NaN,NaN,0.00,0,1,0,0
1,0.62,100.196983,1,8.43,NaN,NaN,NaN,8.43,1,0,0,0
2,2.61,1.006717,2,9.05,NaN,NaN,NaN,9.05,2,0,0,1
3,0.72,0.000183,3,11.66,NaN,NaN,NaN,11.66,3,0,0,1
4,0.64,0.728583,4,12.38,NaN,NaN,NaN,12.38,4,0,0,1
5,1.26,0.425200,5,13.02,0.720,0.540,1.750000,13.02,5,0,0,1
6,0.93,0.000367,6,14.28,0.990,-0.060,0.939394,14.28,6,0,0,1
7,0.90,4.847017,7,15.21,0.930,-0.030,0.967742,15.21,7,0,0,0
8,2.19,0.285300,8,16.11,0.915,1.275,2.393443,16.11,8,0,0,1
9,1.19,0.000400,9,18.30,0.930,0.260,1.279570,18.30,9,0,0,1

In [ ]:
# Check dataset dimensions
print("Total sessions:", len(df_features))
print("Unique participants:", df_features["user_id"].nunique())

# Check missing values in engineered features
feature_columns = [
    "duration_minutes",
    "session_gap_minutes",
    "prior_daily_session_count",
    "prior_daily_usage_minutes",
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio",
    "prior_app_usage_minutes",
    "prior_app_session_count",
    "hour_sin",
    "hour_cos",
    "day_sin",
    "day_cos",
    "is_late_night",
    "rapid_reopen",
    "is_schedule_conflict"
]

print("\nMissing values:")
print(df_features[feature_columns].isna().sum())

Total sessions: 5711
Unique participants: 7

Missing values:
duration_minutes                0
session_gap_minutes             7
prior_daily_session_count       0
prior_daily_usage_minutes       0
previous_median_duration       35
duration_baseline_deviation    35
duration_baseline_ratio        35
prior_app_usage_minutes         0
prior_app_session_count         0
hour_sin                        0
hour_cos                        0
day_sin                         0
day_cos                         0
is_late_night                   0
rapid_reopen                    0
is_schedule_conflict            0
dtype: int64

In [ ]:
# Verify missing session gaps occur only on first sessions
first_sessions = (
    df_features
    .groupby("user_id")
    .head(1)
    .index
)

print(
    "Missing session gaps on first sessions:",
    df_features.loc[first_sessions, "session_gap_minutes"].isna().sum()
)

print(
    "Total missing session gaps:",
    df_features["session_gap_minutes"].isna().sum()
)

# Inspect missing personal baselines by participant
print(
    df_features.groupby("user_id")[
        [
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].apply(lambda x: x.isna().sum())
)

Missing session gaps on first sessions: 7
Total missing session gaps: 7
                                      previous_median_duration  \
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4                         5
85bfc215-c24f-4814-aa00-6794f1a7278a                         5
8cf97b0c-76c9-4d72-b617-759a955f969f                         5
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67                         5
d5a62f7a-97c9-481c-83be-f0a06b70cad9                         5
e7642be3-461d-4c8e-98cd-0eccc76764ec                         5
f5e00193-6fb8-4767-ba5e-5c824dc24c89                         5

                                      duration_baseline_deviation  \
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4                            5
85bfc215-c24f-4814-aa00-6794f1a7278a                            5
8cf97b0c-76c9-4d72-b617-759a955f969f                            5
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67                            5
d5a62f7a-97c9-481c-83be-f0a06b70cad9                            5
e7642be3-461d-4c8e-98cd-0eccc76764ec                            5
f5e00193-6fb8-4767-ba5e-5c824dc24c89                            5

                                      duration_baseline_ratio
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4                        5
85bfc215-c24f-4814-aa00-6794f1a7278a                        5
8cf97b0c-76c9-4d72-b617-759a955f969f                        5
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67                        5
d5a62f7a-97c9-481c-83be-f0a06b70cad9                        5
e7642be3-461d-4c8e-98cd-0eccc76764ec                        5
f5e00193-6fb8-4767-ba5e-5c824dc24c89                        5

In [ ]:
print(df_features[feature_columns].describe().T.to_string())

                              count        mean          std        min        25%        50%         75%           max
duration_minutes             5711.0    6.235025    12.539186   0.500000   1.050000   2.430000    6.405000    380.280000
session_gap_minutes          5704.0   71.894120  1092.252741 -33.826783   0.344075   2.550275   21.127308  62586.002650
prior_daily_session_count    5711.0   19.994397    17.608596   0.000000   7.000000  16.000000   29.000000    119.000000
prior_daily_usage_minutes    5711.0  111.657155    91.959292   0.000000  37.300000  95.960000  161.505000    482.900000
previous_median_duration     5676.0    2.505791     0.967712   0.720000   2.100000   2.420000    2.455000      7.780000
duration_baseline_deviation  5676.0    3.745278    12.495269  -7.010000  -1.220000   0.105000    3.851250    376.615000
duration_baseline_ratio      5676.0    2.561130     4.780675   0.068456   0.477212   1.046571    2.624127    104.422222
prior_app_usage_minutes      5711.0   52.864708    67.505846   0.000000   8.720000  29.130000   69.120000    478.730000
prior_app_session_count      5711.0   10.684644    13.035967   0.000000   3.000000   7.000000   14.000000    119.000000
hour_sin                     5711.0   -0.288709     0.644551  -1.000000  -0.866025  -0.500000    0.258819      1.000000
hour_cos                     5711.0   -0.176466     0.685723  -1.000000  -0.866025  -0.258819    0.500000      1.000000
day_sin                      5711.0    0.059922     0.699628  -0.974928  -0.433884   0.000000    0.781831      0.974928
day_cos                      5711.0   -0.023369     0.711729  -0.900969  -0.900969  -0.222521    0.623490      1.000000
is_late_night                5711.0    0.144633     0.351761   0.000000   0.000000   0.000000    0.000000      1.000000
rapid_reopen                 5711.0    0.461916     0.498591   0.000000   0.000000   0.000000    1.000000      1.000000
is_schedule_conflict         5711.0    0.270706     0.444363   0.000000   0.000000   0.000000    1.000000      1.000000

In [ ]:
print("===== NEGATIVE GAPS =====")

negative_gaps = df_features[
    df_features["session_gap_minutes"] < 0
]

print("Count:", len(negative_gaps))

print(
    negative_gaps[
        [
            "user_id",
            "timestamp_local",
            "session_end_local",
            "app_label",
            "duration_minutes",
            "session_gap_minutes"
        ]
    ].to_string(index=False)
)


print("\n===== LONG SESSIONS =====")

long_sessions = df_features[
    df_features["duration_minutes"] > 60
]

print("Count:", len(long_sessions))

print(
    long_sessions[
        [
            "user_id",
            "timestamp_local",
            "session_end_local",
            "app_label",
            "duration_minutes"
        ]
    ].sort_values(
        "duration_minutes",
        ascending=False
    ).to_string(index=False)
)


print("\n===== EXTREME BASELINE RATIOS =====")

extreme_ratio = df_features[
    df_features["duration_baseline_ratio"] > 10
]

print("Count:", len(extreme_ratio))

print(
    extreme_ratio[
        [
            "user_id",
            "timestamp_local",
            "app_label",
            "duration_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].sort_values(
        "duration_baseline_ratio",
        ascending=False
    ).to_string(index=False)
)

===== NEGATIVE GAPS =====
Count: 6
                             user_id           timestamp_local         session_end_local app_label  duration_minutes  session_gap_minutes
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-03 22:11:38+03:00 2026-05-03 22:12:10+03:00 Instagram              0.53            -1.267383
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-03 22:23:42+03:00 2026-05-03 22:24:31+03:00 Instagram              0.82           -33.826783
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-04 06:30:54+03:00 2026-05-04 12:51:11+03:00 Instagram            380.28            -0.107667
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-05 22:12:22+03:00 2026-05-05 22:13:24+03:00 Instagram              1.03            -9.824017
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-05 22:37:27+03:00 2026-05-05 23:13:37+03:00 Instagram             36.17            -0.135033
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-05-06 21:19:59+03:00 2026-05-06 21:20:29+03:00 Instagram              0.50            -3.016667

===== LONG SESSIONS =====
Count: 45
                             user_id                  timestamp_local                session_end_local app_label  duration_minutes
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-04 06:30:54+03:00        2026-05-04 12:51:11+03:00 Instagram            380.28
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-05 17:27:06+03:00        2026-05-05 22:10:22+03:00  Snapchat            283.27
d5a62f7a-97c9-481c-83be-f0a06b70cad9 2026-04-21 00:18:54.141000+03:00 2026-04-21 03:26:51.593000+03:00   YouTube            187.96
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-16 12:08:46.327000+03:00 2026-09-16 14:27:22.508000+03:00 Instagram            138.60
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-06 16:43:47+03:00        2026-05-06 19:02:01+03:00 Instagram            138.23
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 06:00:09+03:00        2026-05-03 08:17:05+03:00   YouTube            136.93
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-05 15:11:04+03:00        2026-05-05 17:27:06+03:00 Instagram            136.03
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-06 19:06:15+03:00        2026-05-06 21:18:28+03:00 Instagram            132.22
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-02 22:19:26+03:00        2026-05-03 00:21:29+03:00   YouTube            122.05
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-23 22:15:17.616000+03:00 2026-09-24 00:03:44.452000+03:00   YouTube            108.45
e7642be3-461d-4c8e-98cd-0eccc76764ec 2026-09-29 12:51:38.948000+03:00 2026-09-29 14:38:59.412000+03:00 Instagram            107.34
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-07-10 20:09:52.384000+03:00 2026-07-10 21:56:16.548000+03:00 Instagram            106.40
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 20:20:16+03:00        2026-05-03 22:05:48+03:00 Instagram            105.53
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-01 20:34:12.847000+03:00 2026-05-01 22:18:03.976000+03:00   YouTube            103.85
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 17:21:27+03:00        2026-05-03 18:59:30+03:00 Instagram             98.05
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-18 19:27:21.480000+03:00 2026-09-18 21:00:37.163000+03:00 Instagram             93.26
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-14 06:52:07.922000+03:00 2026-05-14 08:20:06.407000+03:00   YouTube             87.97
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-19 09:29:21.589000+03:00 2026-05-19 10:52:17.630000+03:00   YouTube             82.93
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-26 22:40:44.226000+03:00 2026-04-27 00:01:58.490000+03:00   YouTube             81.24
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-15 22:40:38.560000+03:00 2026-05-15 23:59:56.265000+03:00   YouTube             79.30
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-16 09:41:31.608000+03:00 2026-09-16 10:59:32.928000+03:00 Instagram             78.02
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-11 21:53:17.444000+03:00 2026-09-11 23:09:02.054000+03:00 Instagram             75.74
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-29 06:01:18.978000+03:00 2026-04-29 07:16:05.057000+03:00   YouTube             74.77
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-25 00:15:41.281000+03:00 2026-09-25 01:30:06.516000+03:00   YouTube             74.42
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-16 00:25:20.274000+03:00 2026-05-16 01:39:22.282000+03:00   YouTube             74.03
e7642be3-461d-4c8e-98cd-0eccc76764ec 2026-09-24 10:58:31.797000+03:00 2026-09-24 12:12:05.856000+03:00    TikTok             73.57
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-20 22:48:15.415000+03:00 2026-07-21 00:01:26.458000+03:00   YouTube             73.18
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-10 10:18:05.762000+03:00 2026-05-10 11:30:24.508000+03:00   YouTube             72.31
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-27 07:16:26.816000+03:00 2026-04-27 08:28:38.361000+03:00   YouTube             72.19
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-28 17:13:10.203000+03:00 2026-09-28 18:25:04.510000+03:00   YouTube             71.91
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-26 03:21:18.458000+03:00 2026-05-26 04:32:48.077000+03:00   YouTube             71.49
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-06-01 16:07:01.229000+03:00 2026-06-01 17:17:06.551000+03:00 Instagram             70.09
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-23 03:45:01.423000+03:00 2026-05-23 04:54:04.081000+03:00   YouTube             69.04
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-06-08 03:56:54.844000+03:00 2026-06-08 05:05:35.681000+03:00   YouTube             68.68
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-04-29 07:23:03.087000+03:00 2026-04-29 08:31:02.854000+03:00 Instagram             68.00
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-03 20:13:06.967000+03:00 2026-05-03 21:19:49.848000+03:00 Instagram             66.71
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-23 00:38:41.757000+03:00 2026-09-23 01:45:11.127000+03:00 Instagram             66.49
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-06-08 20:35:33.248000+03:00 2026-06-08 21:40:40.543000+03:00 Instagram             65.12
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-06-01 17:24:38.238000+03:00 2026-06-01 18:29:17.359000+03:00 Instagram             64.65
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-19 00:24:37.176000+03:00 2026-07-19 01:28:33.191000+03:00   YouTube             63.93
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-16 22:06:03.176000+03:00 2026-05-16 23:08:44.356000+03:00   YouTube             62.69
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-04 20:25:46.937000+03:00 2026-09-04 21:26:57.662000+03:00 Instagram             61.18
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-11 00:21:47.082000+03:00 2026-07-11 01:22:57.011000+03:00   YouTube             61.17
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-26 23:57:50.395000+03:00 2026-09-27 00:58:30.471000+03:00   YouTube             60.67
e7642be3-461d-4c8e-98cd-0eccc76764ec 2026-09-27 23:03:34.230000+03:00 2026-09-28 00:03:57.950000+03:00 Instagram             60.40

===== EXTREME BASELINE RATIOS =====
Count: 286
                             user_id                  timestamp_local app_label  duration_minutes  previous_median_duration  duration_baseline_deviation  duration_baseline_ratio
d5a62f7a-97c9-481c-83be-f0a06b70cad9 2026-04-21 00:18:54.141000+03:00   YouTube            187.96                     1.800                      186.160               104.422222
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-04 06:30:54+03:00 Instagram            380.28                     3.665                      376.615               103.759891
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-05 17:27:06+03:00  Snapchat            283.27                     3.540                      279.730                80.019774
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-16 12:08:46.327000+03:00 Instagram            138.60                     2.305                      136.295                60.130152
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-01 20:34:12.847000+03:00   YouTube            103.85                     1.990                      101.860                52.185930
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-04 20:25:46.937000+03:00 Instagram             61.18                     1.290                       59.890                47.426357
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-04 17:41:02.844000+03:00 Instagram             55.54                     1.225                       54.315                45.338776
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-23 22:15:17.616000+03:00   YouTube            108.45                     2.420                      106.030                44.814050
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-06 16:43:47+03:00 Instagram            138.23                     3.210                      135.020                43.062305
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-06 19:06:15+03:00 Instagram            132.22                     3.200                      129.020                41.318750
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-18 19:27:21.480000+03:00 Instagram             93.26                     2.280                       90.980                40.903509
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-14 06:52:07.922000+03:00   YouTube             87.97                     2.180                       85.790                40.353211
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-26 22:40:44.226000+03:00   YouTube             81.24                     2.040                       79.200                39.823529
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-05 15:11:04+03:00 Instagram            136.03                     3.520                      132.510                38.644886
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-29 06:01:18.978000+03:00   YouTube             74.77                     2.010                       72.760                37.199005
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-27 07:16:26.816000+03:00   YouTube             72.19                     2.070                       70.120                34.874396
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-16 09:41:31.608000+03:00 Instagram             78.02                     2.245                       75.775                34.752784
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-15 22:40:38.560000+03:00   YouTube             79.30                     2.290                       77.010                34.628821
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-10 10:18:05.762000+03:00   YouTube             72.31                     2.100                       70.210                34.433333
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-19 09:29:21.589000+03:00   YouTube             82.93                     2.420                       80.510                34.268595
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 06:00:09+03:00   YouTube            136.93                     4.065                      132.865                33.685117
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-03 20:13:06.967000+03:00 Instagram             66.71                     2.040                       64.670                32.700980
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-11 21:53:17.444000+03:00 Instagram             75.74                     2.320                       73.420                32.646552
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-16 00:25:20.274000+03:00   YouTube             74.03                     2.310                       71.720                32.047619
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-06 14:47:14.636000+03:00 Instagram             54.44                     1.730                       52.710                31.468208
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-25 00:15:41.281000+03:00   YouTube             74.42                     2.420                       72.000                30.752066
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-02 22:19:26+03:00   YouTube            122.05                     4.000                      118.050                30.512500
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-23 00:38:41.757000+03:00 Instagram             66.49                     2.180                       64.310                30.500000
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-20 22:48:15.415000+03:00   YouTube             73.18                     2.420                       70.760                30.239669
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-28 17:13:10.203000+03:00   YouTube             71.91                     2.390                       69.520                30.087866
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-26 03:21:18.458000+03:00   YouTube             71.49                     2.460                       69.030                29.060976
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-23 03:45:01.423000+03:00   YouTube             69.04                     2.380                       66.660                29.008403
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-25 16:47:07.463000+03:00 Instagram             52.07                     1.825                       50.245                28.531507
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-07-10 20:09:52.384000+03:00 Instagram            106.40                     3.730                      102.670                28.525469
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-06-08 03:56:54.844000+03:00   YouTube             68.68                     2.470                       66.210                27.805668
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 20:20:16+03:00 Instagram            105.53                     3.810                      101.720                27.698163
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-16 22:06:03.176000+03:00   YouTube             62.69                     2.330                       60.360                26.905579
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-09 09:21:26.390000+03:00 Instagram             54.54                     2.060                       52.480                26.475728
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-06-08 20:35:33.248000+03:00 Instagram             65.12                     2.470                       62.650                26.364372
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-19 00:24:37.176000+03:00   YouTube             63.93                     2.440                       61.490                26.200820
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-26 18:51:25.610000+03:00  Facebook             50.53                     1.940                       48.590                26.046392
85bfc215-c24f-4814-aa00-6794f1a7278a        2026-05-03 17:21:27+03:00 Instagram             98.05                     3.810                       94.240                25.734908
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-09-26 23:57:50.395000+03:00   YouTube             60.67                     2.400                       58.270                25.279167
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-11 00:21:47.082000+03:00   YouTube             61.17                     2.420                       58.750                25.276860
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-21 04:02:04.253000+03:00   YouTube             59.43                     2.415                       57.015                24.608696
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-17 18:56:57.394000+03:00 Instagram             55.81                     2.315                       53.495                24.107991
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-25 21:33:41.014000+03:00   YouTube             59.20                     2.460                       56.740                24.065041
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-18 00:44:13.186000+03:00   YouTube             58.92                     2.450                       56.470                24.048980
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-12 19:09:09.884000+03:00 Instagram             55.25                     2.300                       52.950                24.021739
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67 2026-09-24 21:29:33.862000+03:00    TikTok             46.37                     1.950                       44.420                23.779487
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-17 22:32:22.564000+03:00   YouTube             55.49                     2.345                       53.145                23.663113
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-15 20:37:54.038000+03:00  Facebook             53.39                     2.300                       51.090                23.213043
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67 2026-09-26 20:44:20.289000+03:00    TikTok             49.76                     2.175                       47.585                22.878161
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-23 09:26:49.222000+03:00 Instagram             49.05                     2.185                       46.865                22.448513
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-08-04 16:52:49.154000+03:00   YouTube             54.10                     2.430                       51.670                22.263374
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-21 21:39:12.744000+03:00 Instagram             48.45                     2.185                       46.265                22.173913
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-20 22:47:32.556000+03:00 Instagram             46.57                     2.180                       44.390                21.362385
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-26 20:04:55.322000+03:00 Instagram             41.66                     1.965                       39.695                21.201018
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-19 22:06:50.759000+03:00   YouTube             50.37                     2.420                       47.950                20.814050
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-04 10:06:38.010000+03:00 Instagram             25.79                     1.260                       24.530                20.468254
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-13 20:58:06.911000+03:00   YouTube             50.10                     2.450                       47.650                20.448980
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-30 08:32:20.277000+03:00   YouTube             49.18                     2.420                       46.760                20.322314
d5a62f7a-97c9-481c-83be-f0a06b70cad9 2026-04-17 00:43:13.583000+03:00   YouTube             48.82                     2.410                       46.410                20.257261
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-07-30 03:05:59.968000+03:00   YouTube             48.75                     2.420                       46.330                20.144628
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-19 11:15:10.072000+03:00 Instagram             46.28                     2.310                       43.970                20.034632
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-06-01 16:07:01.229000+03:00 Instagram             70.09                     3.510                       66.580                19.968661
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-08-05 07:59:22.806000+03:00  Facebook             48.46                     2.430                       46.030                19.942387
f5e00193-6fb8-4767-ba5e-5c824dc24c89 2026-09-27 20:27:27.010000+03:00    TikTok             23.10                     1.180                       21.920                19.576271
e7642be3-461d-4c8e-98cd-0eccc76764ec 2026-09-23 14:53:03.371000+03:00    TikTok             59.27                     3.080                       56.190                19.243506
d5a62f7a-97c9-481c-83be-f0a06b70cad9 2026-04-23 18:28:54.966000+03:00 Instagram             38.14                     1.990                       36.150                19.165829
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-05-22 04:21:41.319000+03:00   YouTube             46.38                     2.420                       43.960                19.165289

In [ ]:
# -----------------------------------------
# Session overlap indicator
# -----------------------------------------

df_features["has_session_overlap"] = (
    df_features["session_gap_minutes"] < 0
).astype(int)

# Non-negative version for modelling
df_features["session_gap_minutes_nonnegative"] = (
    df_features["session_gap_minutes"].clip(lower=0)
)

# -----------------------------------------
# Log transformations for skewed variables
# -----------------------------------------

df_features["log_duration"] = np.log1p(
    df_features["duration_minutes"]
)

df_features["log_duration_baseline_ratio"] = np.log1p(
    df_features["duration_baseline_ratio"]
)

df_features["log_prior_daily_usage"] = np.log1p(
    df_features["prior_daily_usage_minutes"]
)

df_features["log_prior_app_usage"] = np.log1p(
    df_features["prior_app_usage_minutes"]
)

In [ ]:
transformed_features = [
    "log_duration",
    "log_duration_baseline_ratio",
    "log_prior_daily_usage",
    "log_prior_app_usage",
    "session_gap_minutes_nonnegative",
    "has_session_overlap"
]

print(
    df_features[transformed_features]
    .describe()
    .T
)

                                  count       mean          std       min  \
log_duration                     5711.0   1.458260     0.893302  0.405465
log_duration_baseline_ratio      5676.0   0.932941     0.703094  0.066215
log_prior_daily_usage            5711.0   4.168184     1.369720  0.000000
log_prior_app_usage              5711.0   3.137707     1.531677  0.000000
session_gap_minutes_nonnegative  5704.0  71.902567  1092.252084  0.000000
has_session_overlap              5711.0   0.001051     0.032399  0.000000

                                      25%       50%        75%           max
log_duration                     0.717840  1.232560   2.002155      5.943534
log_duration_baseline_ratio      0.390157  0.716166   1.287613      4.657973
log_prior_daily_usage            3.645449  4.574299   5.090709      6.181878
log_prior_app_usage              2.274186  3.405521   4.250208      6.173223
session_gap_minutes_nonnegative  0.344075  2.550275  21.127308  62586.002650
has_session_overlap              0.000000  0.000000   0.000000      1.000000

In [ ]:
df_features["log_session_gap"] = np.log1p(
    df_features["session_gap_minutes_nonnegative"]
)

In [ ]:
def calculate_recent_windows(group):
    group = group.sort_values("timestamp_local").copy()

    timestamps = group["timestamp_local"].tolist()
    durations = group["duration_minutes"].to_numpy()

    sessions_15 = []
    sessions_30 = []
    usage_30 = []

    for i, current_time in enumerate(timestamps):

        if i == 0:
            sessions_15.append(0)
            sessions_30.append(0)
            usage_30.append(0.0)
            continue

        elapsed_minutes = np.array([
            (current_time - previous_time).total_seconds() / 60
            for previous_time in timestamps[:i]
        ])

        recent_15 = elapsed_minutes <= 15
        recent_30 = elapsed_minutes <= 30

        sessions_15.append(
            int(recent_15.sum())
        )

        sessions_30.append(
            int(recent_30.sum())
        )

        usage_30.append(
            float(durations[:i][recent_30].sum())
        )

    group["sessions_last_15min"] = sessions_15
    group["sessions_last_30min"] = sessions_30
    group["usage_last_30min"] = usage_30

    return group


df_features = (
    df_features
    .groupby("user_id", group_keys=False)
    .apply(calculate_recent_windows)
    .reset_index(drop=True)
)

/tmp/ipykernel_4058/4111373394.py:49: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calculate_recent_windows)

In [ ]:
recent_features = [
    "sessions_last_15min",
    "sessions_last_30min",
    "usage_last_30min"
]

print(df_features[recent_features].describe().T)

                      count      mean       std  min  25%   50%    75%    max
sessions_last_15min  5711.0  1.188408  1.325440  0.0  0.0  1.00   2.00   7.00
sessions_last_30min  5711.0  2.029942  1.995875  0.0  0.0  2.00   3.00  11.00
usage_last_30min     5711.0  7.128014  7.747863  0.0  0.0  4.35  11.92  53.87

In [ ]:
print(
    df_features
    .groupby("user_id")
    .head(1)[
        [
            "user_id",
            "timestamp_local",
            "sessions_last_15min",
            "sessions_last_30min",
            "usage_last_30min"
        ]
    ].to_string(index=False)
)

                             user_id                  timestamp_local  sessions_last_15min  sessions_last_30min  usage_last_30min
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 15:42:42.152000+03:00                    0                    0               0.0
85bfc215-c24f-4814-aa00-6794f1a7278a 2026-04-09 08:53:43.406000+03:00                    0                    0               0.0
8cf97b0c-76c9-4d72-b617-759a955f969f 2026-04-17 13:18:14.939000+03:00                    0                    0               0.0
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67 2026-09-23 11:16:20.108000+03:00                    0                    0               0.0
d5a62f7a-97c9-481c-83be-f0a06b70cad9 2026-04-16 22:07:01.509000+03:00                    0                    0               0.0
e7642be3-461d-4c8e-98cd-0eccc76764ec 2026-09-22 22:06:43.060000+03:00                    0                    0               0.0
f5e00193-6fb8-4767-ba5e-5c824dc24c89 2026-09-23 09:58:02.956000+03:00                    0                    0               0.0

In [ ]:
print(df_features[[
    "sessions_last_15min",
    "sessions_last_30min",
    "usage_last_30min"
]].describe().T)

                      count      mean       std  min  25%   50%    75%    max
sessions_last_15min  5711.0  1.188408  1.325440  0.0  0.0  1.00   2.00   7.00
sessions_last_30min  5711.0  2.029942  1.995875  0.0  0.0  2.00   3.00  11.00
usage_last_30min     5711.0  7.128014  7.747863  0.0  0.0  4.35  11.92  53.87

In [ ]:
print(
    df_features[
        [
            "sessions_last_15min",
            "sessions_last_30min",
            "usage_last_30min"
        ]
    ].isna().sum()
)

sessions_last_15min    0
sessions_last_30min    0
usage_last_30min       0
dtype: int64

In [ ]:
candidate_features = [
    # Session-level behaviour
    "duration_minutes",
    "session_gap_minutes",
    "session_gap_minutes_nonnegative",

    # Prior daily behaviour
    "prior_daily_session_count",
    "prior_daily_usage_minutes",

    # Personal baseline
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio",

    # Prior app behaviour
    "prior_app_usage_minutes",
    "prior_app_session_count",

    # Recent behavioural windows
    "sessions_last_15min",
    "sessions_last_30min",
    "usage_last_30min",

    # Time/context
    "local_hour",
    "local_minute",
    "hour_sin",
    "hour_cos",
    "day_sin",
    "day_cos",
    "is_late_night",
    "is_schedule_conflict",

    # Behavioural event indicator
    "rapid_reopen",
    "has_session_overlap",

    # Transformed variables
    "log_duration",
    "log_duration_baseline_ratio",
    "log_prior_daily_usage",
    "log_prior_app_usage",
    "log_session_gap",

    # App identity
    "app_label"
]

print("Number of candidate features:", len(candidate_features))

print("\nMissing values:")
print(
    df_features[candidate_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

Number of candidate features: 29

Missing values:
previous_median_duration           35
duration_baseline_deviation        35
duration_baseline_ratio            35
log_duration_baseline_ratio        35
session_gap_minutes_nonnegative     7
log_session_gap                     7
session_gap_minutes                 7
prior_daily_usage_minutes           0
prior_daily_session_count           0
prior_app_session_count             0
sessions_last_15min                 0
duration_minutes                    0
prior_app_usage_minutes             0
usage_last_30min                    0
sessions_last_30min                 0
local_hour                          0
local_minute                        0
day_sin                             0
day_cos                             0
hour_sin                            0
hour_cos                            0
is_schedule_conflict                0
is_late_night                       0
has_session_overlap                 0
rapid_reopen                        0
log_duration                        0
log_prior_daily_usage               0
log_prior_app_usage                 0
app_label                           0
dtype: int64

In [ ]:
print("\nFeature data types:")
print(df_features[candidate_features].dtypes)

Feature data types:
duration_minutes                   float64
session_gap_minutes                float64
session_gap_minutes_nonnegative    float64
prior_daily_session_count            int64
prior_daily_usage_minutes          float64
previous_median_duration           float64
duration_baseline_deviation        float64
duration_baseline_ratio            float64
prior_app_usage_minutes            float64
prior_app_session_count              int64
sessions_last_15min                  int64
sessions_last_30min                  int64
usage_last_30min                   float64
local_hour                           int32
local_minute                         int32
hour_sin                           float64
hour_cos                           float64
day_sin                            float64
day_cos                            float64
is_late_night                        int64
is_schedule_conflict                 int64
rapid_reopen                         int64
has_session_overlap                  int64
log_duration                       float64
log_duration_baseline_ratio        float64
log_prior_daily_usage              float64
log_prior_app_usage                float64
log_session_gap                    float64
app_label                           object
dtype: object

In [ ]:
print("\nUnique values:")
for feature in candidate_features:
    print(
        f"{feature:35} "
        f"{df_features[feature].nunique(dropna=True)}"
    )

Unique values:
duration_minutes                    1598
session_gap_minutes                 5337
session_gap_minutes_nonnegative     5331
prior_daily_session_count           120
prior_daily_usage_minutes           5208
previous_median_duration            378
duration_baseline_deviation         3291
duration_baseline_ratio             5140
prior_app_usage_minutes             4527
prior_app_session_count             120
sessions_last_15min                 8
sessions_last_30min                 12
usage_last_30min                    2356
local_hour                          24
local_minute                        60
hour_sin                            22
hour_cos                            22
day_sin                             7
day_cos                             7
is_late_night                       2
is_schedule_conflict                2
rapid_reopen                        2
has_session_overlap                 2
log_duration                        1598
log_duration_baseline_ratio         5128
log_prior_daily_usage               4987
log_prior_app_usage                 4284
log_session_gap                     5331
app_label                           6

INSPECT DAILY ASI SCORE

In [ ]:
# Inspect the daily behavioural index

daily_asi = (
    df_features[
        ["user_id", "local_date", "day_asi_score"]
    ]
    .drop_duplicates()
    .sort_values(["user_id", "local_date"])
)

print("Participant-days:", len(daily_asi))
print("Participants:", daily_asi["user_id"].nunique())

print("\nDays per participant:")
print(
    daily_asi
    .groupby("user_id")
    .size()
    .describe()
)

print("\nASI summary:")
print(
    daily_asi["day_asi_score"]
    .describe()
)

print("\nFirst 20 participant-days:")
display(daily_asi.head(20))

Participant-days: 221
Participants: 7

Days per participant:
count     7.000000
mean     31.571429
std      37.152197
min       7.000000
25%       7.500000
50%       8.000000
75%      46.500000
max      98.000000
dtype: float64

ASI summary:
count    221.000000
mean      43.900452
std       14.594490
min        5.000000
25%       35.000000
50%       47.000000
75%       55.000000
max       74.000000
Name: day_asi_score, dtype: float64

First 20 participant-days:

                                  user_id  local_date  day_asi_score
0    46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02             40
26   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-03             37
52   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-04             44
65   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-05             37
74   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-06             47
91   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-07             41
109  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-08             48
138  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-09             58
190  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-10             24
202  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-11             52
226  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-12             55
250  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-13             37
266  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-14             23
276  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-15             30
288  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-16             66
321  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-17             29
331  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-18             47
343  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-19             58
385  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-20             53
412  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-21             53

In [ ]:
# Check gaps between observed participant-days

daily_asi_check = daily_asi.copy()

daily_asi_check["local_date"] = pd.to_datetime(
    daily_asi_check["local_date"]
)

daily_asi_check["previous_date"] = (
    daily_asi_check
    .groupby("user_id")["local_date"]
    .shift(1)
)

daily_asi_check["days_since_previous"] = (
    daily_asi_check["local_date"]
    - daily_asi_check["previous_date"]
).dt.days

print(
    daily_asi_check["days_since_previous"]
    .describe()
)

print("\nConsecutive participant-days:")
print(
    (daily_asi_check["days_since_previous"] == 1)
    .value_counts(dropna=False)
)

count    214.000000
mean       1.439252
std        3.825238
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       44.000000
Name: days_since_previous, dtype: float64

Consecutive participant-days:
days_since_previous
True     207
False     14
Name: count, dtype: int64

In [ ]:
# Show date coverage for every participant

coverage = (
    daily_asi_check
    .groupby("user_id")
    .agg(
        first_day=("local_date", "min"),
        last_day=("local_date", "max"),
        observed_days=("local_date", "count"),
        consecutive_days=(
            "days_since_previous",
            lambda x: (x == 1).sum()
        )
    )
)

display(coverage)

,first_day,last_day,observed_days,consecutive_days
user_id,,,,
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02,2026-09-24,23,22
85bfc215-c24f-4814-aa00-6794f1a7278a,2026-04-09,2026-07-12,70,67
8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-17,2026-09-29,98,93
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,2026-09-23,2026-09-30,8,7
d5a62f7a-97c9-481c-83be-f0a06b70cad9,2026-04-16,2026-04-23,7,5
e7642be3-461d-4c8e-98cd-0eccc76764ec,2026-09-22,2026-09-29,8,7
f5e00193-6fb8-4767-ba5e-5c824dc24c89,2026-09-23,2026-09-29,7,6

BUILD DAILY FORECASTING DATASET

In [82]:
# ============================================================
# STEP 1 — Build daily forecasting dataset
# ============================================================

# Start with one row per participant-day
daily = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .groupby(["user_id", "local_date"], as_index=False)
    .agg(
        day_asi_score=("day_asi_score", "first"),

        daily_usage_minutes=("duration_minutes", "sum"),
        daily_session_count=("duration_minutes", "count"),
        daily_avg_session_duration=("duration_minutes", "mean"),
        daily_max_session_duration=("duration_minutes", "max"),

        daily_late_night_sessions=("is_late_night", "sum"),
        daily_schedule_conflicts=("is_schedule_conflict", "sum"),
        daily_rapid_reopens=("rapid_reopen", "sum"),

        daily_sessions_last_15min=("sessions_last_15min", "sum"),
        daily_sessions_last_30min=("sessions_last_30min", "sum"),
    )
)

daily["local_date"] = pd.to_datetime(daily["local_date"])

# Sort chronologically within each participant
daily = (
    daily
    .sort_values(["user_id", "local_date"])
    .reset_index(drop=True)
)

print("Participant-days:", len(daily))
print("Participants:", daily["user_id"].nunique())

display(daily.head())

Participant-days: 219
Participants: 7

,user_id,local_date,day_asi_score,daily_usage_minutes,daily_session_count,daily_avg_session_duration,daily_max_session_duration,daily_late_night_sessions,daily_schedule_conflicts,daily_rapid_reopens,daily_sessions_last_15min,daily_sessions_last_30min
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02,40,59.40,26,2.284615,8.43,0,1,11,57,76
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-03,37,72.61,26,2.792692,11.64,1,8,13,39,50
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-04,44,176.66,13,13.589231,61.18,0,3,1,3,3
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-05,37,22.76,9,2.528889,5.45,7,0,4,5,14
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-06,47,126.11,17,7.418235,54.44,1,0,10,19,22

In [86]:
# ============================================================
# STEP 2 — Historical / lagged features
# ============================================================

daily["previous_day_asi"] = (
    daily.groupby("user_id")["day_asi_score"].shift(1)
)

daily["asi_change_previous_day"] = (
    daily["day_asi_score"]
    - daily["previous_day_asi"]
)

daily["asi_rolling_3day"] = (
    daily.groupby("user_id")["day_asi_score"]
    .transform(
        lambda s: s.shift(1).rolling(
            window=3,
            min_periods=1
        ).mean()
    )
)

daily["asi_rolling_7day"] = (
    daily.groupby("user_id")["day_asi_score"]
    .transform(
        lambda s: s.shift(1).rolling(
            window=7,
            min_periods=1
        ).mean()
    )
)

CREATE FUTURE TARGET

In [87]:
# ============================================================
# STEP 3 — Future target
# ============================================================

daily["next_day_date"] = (
    daily.groupby("user_id")["local_date"].shift(-1)
)

daily["next_day_asi"] = (
    daily.groupby("user_id")["day_asi_score"].shift(-1)
)

# Only keep TRUE next-day transitions
daily["days_to_target"] = (
    daily["next_day_date"] - daily["local_date"]
).dt.days

daily_forecast = daily[
    daily["days_to_target"] == 1
].copy()

print("Forecasting observations:", len(daily_forecast))
print("Participants:", daily_forecast["user_id"].nunique())

display(
    daily_forecast[
        [
            "user_id",
            "local_date",
            "day_asi_score",
            "previous_day_asi",
            "asi_rolling_3day",
            "asi_rolling_7day",
            "next_day_asi"
        ]
    ].head(15)
)

Forecasting observations: 207
Participants: 7

,user_id,local_date,day_asi_score,previous_day_asi,asi_rolling_3day,asi_rolling_7day,next_day_asi
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02,40,NaN,NaN,NaN,37.0
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-03,37,40.0,40.000000,40.000000,44.0
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-04,44,37.0,38.500000,38.500000,37.0
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-05,37,44.0,40.333333,40.333333,47.0
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-06,47,37.0,39.333333,39.500000,41.0
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-07,41,47.0,42.666667,41.000000,48.0
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-08,48,41.0,41.666667,41.000000,58.0
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-09,58,48.0,45.333333,42.000000,24.0
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-10,24,58.0,49.000000,44.571429,52.0
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-11,52,24.0,43.333333,42.714286,55.0
10,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-12,55,52.0,44.666667,43.857143,37.0
11,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-13,37,55.0,43.666667,46.428571,23.0
12,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-14,23,37.0,48.000000,45.000000,30.0
13,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-15,30,23.0,38.333333,42.428571,66.0
14,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-16,66,30.0,30.000000,39.857143,29.0

AGGREGATED BEHAVIOURAL VARIABLES

In [88]:
# ============================================================
# STEP 4 — Lag behavioural variables
# ============================================================

behavioural_daily_features = [
    "daily_usage_minutes",
    "daily_session_count",
    "daily_avg_session_duration",
    "daily_max_session_duration",
    "daily_late_night_sessions",
    "daily_schedule_conflicts",
    "daily_rapid_reopens",
    "daily_sessions_last_15min",
    "daily_sessions_last_30min",
]

for feature in behavioural_daily_features:

    daily[f"previous_{feature}"] = (
        daily.groupby("user_id")[feature].shift(1)
    )

    daily[f"rolling_3day_{feature}"] = (
        daily.groupby("user_id")[feature]
        .transform(
            lambda s: s.shift(1).rolling(
                3,
                min_periods=1
            ).mean()
        )
    )

In [89]:
# ============================================================
# STEP 4 — Lag behavioural variables
# ============================================================

behavioural_daily_features = [
    "daily_usage_minutes",
    "daily_session_count",
    "daily_avg_session_duration",
    "daily_max_session_duration",
    "daily_late_night_sessions",
    "daily_schedule_conflicts",
    "daily_rapid_reopens",
    "daily_sessions_last_15min",
    "daily_sessions_last_30min",
]

for feature in behavioural_daily_features:

    daily[f"previous_{feature}"] = (
        daily.groupby("user_id")[feature].shift(1)
    )

    daily[f"rolling_3day_{feature}"] = (
        daily.groupby("user_id")[feature]
        .transform(
            lambda s: s.shift(1).rolling(
                3,
                min_periods=1
            ).mean()
        )
    )

In [90]:
# ============================================================
# STEP 5 — Final initial feature set
# ============================================================

ml_features = [
    # Previous ASI trajectory
    "previous_day_asi",
    "asi_change_previous_day",
    "asi_rolling_3day",
    "asi_rolling_7day",

    # Previous behavioural state
    "previous_daily_usage_minutes",
    "previous_daily_session_count",
    "previous_daily_avg_session_duration",
    "previous_daily_max_session_duration",

    # Recent behavioural trends
    "rolling_3day_daily_usage_minutes",
    "rolling_3day_daily_session_count",
    "rolling_3day_daily_avg_session_duration",
    "rolling_3day_daily_max_session_duration",

    # Contextual behaviour
    "previous_daily_late_night_sessions",
    "previous_daily_schedule_conflicts",
    "previous_daily_rapid_reopens",

    "rolling_3day_daily_late_night_sessions",
    "rolling_3day_daily_schedule_conflicts",
    "rolling_3day_daily_rapid_reopens",
]

target = "next_day_asi"

model_data = daily_forecast[
    ["user_id", "local_date"] +
    ml_features +
    [target]
].copy()

print("Rows:", len(model_data))
print("Features:", len(ml_features))

print("\nMissing values:")
print(
    model_data[ml_features + [target]]
    .isna()
    .sum()
)

Rows: 207
Features: 18

Missing values:
previous_day_asi                           7
asi_change_previous_day                    7
asi_rolling_3day                           7
asi_rolling_7day                           7
previous_daily_usage_minutes               7
previous_daily_session_count               7
previous_daily_avg_session_duration        7
previous_daily_max_session_duration        7
rolling_3day_daily_usage_minutes           7
rolling_3day_daily_session_count           7
rolling_3day_daily_avg_session_duration    7
rolling_3day_daily_max_session_duration    7
previous_daily_late_night_sessions         7
previous_daily_schedule_conflicts          7
previous_daily_rapid_reopens               7
rolling_3day_daily_late_night_sessions     7
rolling_3day_daily_schedule_conflicts      7
rolling_3day_daily_rapid_reopens           7
next_day_asi                               0
dtype: int64

In [91]:
display(model_data.head(10))

print("\nShape:")
print(model_data.shape)

print("\nTarget distribution:")
print(model_data["next_day_asi"].describe())

print("\nObservations per participant:")
print(
    model_data.groupby("user_id").size()
)

,user_id,local_date,previous_day_asi,asi_change_previous_day,asi_rolling_3day,asi_rolling_7day,previous_daily_usage_minutes,previous_daily_session_count,previous_daily_avg_session_duration,previous_daily_max_session_duration,...,rolling_3day_daily_session_count,rolling_3day_daily_avg_session_duration,rolling_3day_daily_max_session_duration,previous_daily_late_night_sessions,previous_daily_schedule_conflicts,previous_daily_rapid_reopens,rolling_3day_daily_late_night_sessions,rolling_3day_daily_schedule_conflicts,rolling_3day_daily_rapid_reopens,next_day_asi
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-03,40.0,-3.0,40.000000,40.000000,59.40,26.0,2.284615,8.43,...,26.000000,2.284615,8.430000,0.0,1.0,11.0,0.000000,1.000000,11.000000,44.0
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-04,37.0,7.0,38.500000,38.500000,72.61,26.0,2.792692,11.64,...,26.000000,2.538654,10.035000,1.0,8.0,13.0,0.500000,4.500000,12.000000,37.0
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-05,44.0,-7.0,40.333333,40.333333,176.66,13.0,13.589231,61.18,...,21.666667,6.222179,27.083333,0.0,3.0,1.0,0.333333,4.000000,8.333333,47.0
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-06,37.0,10.0,39.333333,39.500000,22.76,9.0,2.528889,5.45,...,16.000000,6.303604,26.090000,7.0,0.0,4.0,2.666667,3.666667,6.000000,41.0
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-07,47.0,-6.0,42.666667,41.000000,126.11,17.0,7.418235,54.44,...,13.000000,7.845452,40.356667,1.0,0.0,10.0,2.666667,1.000000,5.000000,48.0
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-08,41.0,7.0,41.666667,41.000000,124.25,18.0,6.902778,27.08,...,14.666667,5.616634,28.990000,1.0,5.0,8.0,3.000000,1.666667,7.333333,58.0
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-09,48.0,10.0,45.333333,42.000000,139.72,29.0,4.817931,33.60,...,21.333333,6.379648,38.373333,7.0,4.0,12.0,3.000000,3.000000,10.000000,24.0
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-10,58.0,-34.0,49.000000,44.571429,353.50,52.0,6.798077,54.54,...,33.000000,6.172929,38.406667,2.0,24.0,30.0,3.333333,11.000000,16.666667,52.0
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-11,24.0,28.0,43.333333,42.714286,33.99,12.0,2.832500,5.35,...,31.000000,4.816169,31.163333,2.0,3.0,0.0,3.666667,10.333333,14.000000,55.0

Shape:
(207, 21)

Target distribution:
count    207.000000
mean      44.072464
std       14.716729
min        5.000000
25%       35.000000
50%       47.000000
75%       55.000000
max       74.000000
Name: next_day_asi, dtype: float64

Observations per participant:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    22
85bfc215-c24f-4814-aa00-6794f1a7278a    67
8cf97b0c-76c9-4d72-b617-759a955f969f    93
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67     7
d5a62f7a-97c9-481c-83be-f0a06b70cad9     5
e7642be3-461d-4c8e-98cd-0eccc76764ec     7
f5e00193-6fb8-4767-ba5e-5c824dc24c89     6
dtype: int64

In [93]:
# Remove first-day observations with no historical predictors

model_data_clean = model_data.dropna(
    subset=ml_features
).copy()

print("Original observations:", len(model_data))
print("Usable observations:", len(model_data_clean))
print("Removed:", len(model_data) - len(model_data_clean))

print("\nParticipants represented:")
print(
    model_data_clean["user_id"].nunique()
)

print("\nObservations per participant:")
print(
    model_data_clean
    .groupby("user_id")
    .size()
    .sort_values(ascending=False)
)

print("\nMissing predictor values:")
print(
    model_data_clean[ml_features]
    .isna()
    .sum()
    .sum()
)

Original observations: 207
Usable observations: 200
Removed: 7

Participants represented:
7

Observations per participant:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    92
85bfc215-c24f-4814-aa00-6794f1a7278a    66
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    21
9d9e9be2-c5aa-406b-a5a4-e5546f00cb67     6
e7642be3-461d-4c8e-98cd-0eccc76764ec     6
f5e00193-6fb8-4767-ba5e-5c824dc24c89     5
d5a62f7a-97c9-481c-83be-f0a06b70cad9     4
dtype: int64

Missing predictor values:
0

LEAVE ONE PARTICIPANT OUT (LOPO) SPLIT TEST - we have few participants

In [94]:
# Add the current day's ASI for the persistence baseline
current_asi = daily[
    ["user_id", "local_date", "day_asi_score"]
].copy()

model_data_clean = model_data_clean.merge(
    current_asi,
    on=["user_id", "local_date"],
    how="left"
)

print("Shape:", model_data_clean.shape)

print("\nMissing current ASI:")
print(model_data_clean["day_asi_score"].isna().sum())

print("\nCurrent ASI summary:")
print(model_data_clean["day_asi_score"].describe())

Shape: (200, 22)

Missing current ASI:
0

Current ASI summary:
count    200.000000
mean      43.900000
std       14.610865
min        5.000000
25%       34.500000
50%       47.000000
75%       55.000000
max       74.000000
Name: day_asi_score, dtype: float64

OK XGBOOST HERE WE GO

In [95]:
import numpy as np
import pandas as pd

from sklearn.model_selection import LeaveOneGroupOut
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor


# --------------------------------------------------
# 1. Prepare X, y, and participant groups
# --------------------------------------------------

X = model_data_clean[ml_features].copy()
y = model_data_clean["next_day_asi"].copy()
groups = model_data_clean["user_id"].copy()


# --------------------------------------------------
# 2. Define models
# --------------------------------------------------

models = {
    "Ridge": Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("model", Ridge(alpha=1.0))
    ]),

    "Random Forest": Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("model", RandomForestRegressor(
            n_estimators=300,
            random_state=42,
            n_jobs=-1
        ))
    ]),

    "XGBoost": Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("model", XGBRegressor(
            n_estimators=300,
            max_depth=3,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1
        ))
    ])
}


# --------------------------------------------------
# 3. Leave-One-Participant-Out evaluation
# --------------------------------------------------

logo = LeaveOneGroupOut()

results = []

for fold, (train_idx, test_idx) in enumerate(
    logo.split(X, y, groups=groups),
    start=1
):

    X_train = X.iloc[train_idx]
    X_test = X.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

    test_participants = groups.iloc[test_idx].unique()

    participant = test_participants[0]

    print(f"\nFold {fold}")
    print(f"Held-out participant: {participant}")
    print(f"Training observations: {len(train_idx)}")
    print(f"Test observations: {len(test_idx)}")


    # ----------------------------------------------
    # Persistence baseline
    # ----------------------------------------------

    baseline_pred = model_data_clean.iloc[test_idx]["day_asi_score"]

    results.append({
        "fold": fold,
        "participant": participant,
        "model": "Persistence",
        "mae": mean_absolute_error(y_test, baseline_pred),
        "rmse": np.sqrt(mean_squared_error(y_test, baseline_pred)),
        "r2": r2_score(y_test, baseline_pred)
    })


    # ----------------------------------------------
    # ML models
    # ----------------------------------------------

    for model_name, model in models.items():

        model.fit(X_train, y_train)

        predictions = model.predict(X_test)

        results.append({
            "fold": fold,
            "participant": participant,
            "model": model_name,
            "mae": mean_absolute_error(y_test, predictions),
            "rmse": np.sqrt(mean_squared_error(y_test, predictions)),
            "r2": r2_score(y_test, predictions)
        })


# --------------------------------------------------
# 4. Convert results to DataFrame
# --------------------------------------------------

results_df = pd.DataFrame(results)

print("\nEvaluation results:")
display(results_df)

Fold 1
Held-out participant: 46b5fe4a-2c09-4006-bd5b-08bf12ece5e4
Training observations: 179
Test observations: 21

Fold 2
Held-out participant: 85bfc215-c24f-4814-aa00-6794f1a7278a
Training observations: 134
Test observations: 66

Fold 3
Held-out participant: 8cf97b0c-76c9-4d72-b617-759a955f969f
Training observations: 108
Test observations: 92

Fold 4
Held-out participant: 9d9e9be2-c5aa-406b-a5a4-e5546f00cb67
Training observations: 194
Test observations: 6

Fold 5
Held-out participant: d5a62f7a-97c9-481c-83be-f0a06b70cad9
Training observations: 196
Test observations: 4

Fold 6
Held-out participant: e7642be3-461d-4c8e-98cd-0eccc76764ec
Training observations: 194
Test observations: 6

Fold 7
Held-out participant: f5e00193-6fb8-4767-ba5e-5c824dc24c89
Training observations: 195
Test observations: 5

Evaluation results:

,fold,participant,model,mae,rmse,r2
0,1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,Persistence,12.904762,17.089401,-1.112053
1,1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,Ridge,10.641439,13.147586,-0.250096
2,1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,Random Forest,9.613968,12.911534,-0.205610
3,1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,XGBoost,11.154154,14.395241,-0.498611
4,2,85bfc215-c24f-4814-aa00-6794f1a7278a,Persistence,13.045455,16.115586,-0.113236
5,2,85bfc215-c24f-4814-aa00-6794f1a7278a,Ridge,14.743503,17.342715,-0.289226
6,2,85bfc215-c24f-4814-aa00-6794f1a7278a,Random Forest,14.579596,17.138755,-0.259081
7,2,85bfc215-c24f-4814-aa00-6794f1a7278a,XGBoost,16.240250,18.858571,-0.524448
8,3,8cf97b0c-76c9-4d72-b617-759a955f969f,Persistence,9.402174,12.040241,-0.619166
9,3,8cf97b0c-76c9-4d72-b617-759a955f969f,Ridge,7.855672,10.614043,-0.258296
10,3,8cf97b0c-76c9-4d72-b617-759a955f969f,Random Forest,9.314529,11.994864,-0.606984
11,3,8cf97b0c-76c9-4d72-b617-759a955f969f,XGBoost,9.840471,12.553708,-0.760213
12,4,9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,Persistence,6.166667,7.129750,-1.789634
13,4,9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,Ridge,6.985572,7.975310,-2.490550
14,4,9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,Random Forest,6.517778,7.599042,-2.168957
15,4,9d9e9be2-c5aa-406b-a5a4-e5546f00cb67,XGBoost,7.108848,8.797557,-3.247397
16,5,d5a62f7a-97c9-481c-83be-f0a06b70cad9,Persistence,16.500000,16.881943,-1.720764
17,5,d5a62f7a-97c9-481c-83be-f0a06b70cad9,Ridge,9.813151,12.473424,-0.485311
18,5,d5a62f7a-97c9-481c-83be-f0a06b70cad9,Random Forest,10.984167,11.512273,-0.265226
19,5,d5a62f7a-97c9-481c-83be-f0a06b70cad9,XGBoost,11.643982,12.271124,-0.437523
20,6,e7642be3-461d-4c8e-98cd-0eccc76764ec,Persistence,7.833333,8.916277,-1.553078
21,6,e7642be3-461d-4c8e-98cd-0eccc76764ec,Ridge,6.376865,7.636148,-0.872603
22,6,e7642be3-461d-4c8e-98cd-0eccc76764ec,Random Forest,5.848333,6.181729,-0.227204
23,6,e7642be3-461d-4c8e-98cd-0eccc76764ec,XGBoost,3.363897,5.137790,0.152286
24,7,f5e00193-6fb8-4767-ba5e-5c824dc24c89,Persistence,26.800000,30.776614,-1.905521
25,7,f5e00193-6fb8-4767-ba5e-5c824dc24c89,Ridge,17.693032,25.922331,-1.061249
26,7,f5e00193-6fb8-4767-ba5e-5c824dc24c89,Random Forest,16.800667,20.743256,-0.319886
27,7,f5e00193-6fb8-4767-ba5e-5c824dc24c89,XGBoost,16.329221,19.924022,-0.217689

TERRIBLE TERRIBLE TERRIBLE PERFORMANCE - all predictive models had -R2 values

In [96]:
# --------------------------------------------------
# Behaviour-only feature set
# --------------------------------------------------

asi_history_features = [
    "previous_day_asi",
    "asi_change_previous_day",
    "asi_rolling_3day",
    "asi_rolling_7day"
]

behaviour_only_features = [
    feature for feature in ml_features
    if feature not in asi_history_features
]

print("Full feature count:", len(ml_features))
print("Behaviour-only feature count:", len(behaviour_only_features))

print("\nBehaviour-only features:")
for feature in behaviour_only_features:
    print("-", feature)

Full feature count: 18
Behaviour-only feature count: 14

Behaviour-only features:
- previous_daily_usage_minutes
- previous_daily_session_count
- previous_daily_avg_session_duration
- previous_daily_max_session_duration
- rolling_3day_daily_usage_minutes
- rolling_3day_daily_session_count
- rolling_3day_daily_avg_session_duration
- rolling_3day_daily_max_session_duration
- previous_daily_late_night_sessions
- previous_daily_schedule_conflicts
- previous_daily_rapid_reopens
- rolling_3day_daily_late_night_sessions
- rolling_3day_daily_schedule_conflicts
- rolling_3day_daily_rapid_reopens