<a href="https://colab.research.google.com/github/AmyMugeni/cognilens/blob/ML-dataset-processing/Cognilens_ML_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import os

drive.mount('/content/drive')

project_path = '/content/drive/MyDrive/Cognilens_MLtraining'
os.makedirs(project_path, exist_ok=True)
os.chdir(project_path)

print(f"Working directory set to: {os.getcwd()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Working directory set to: /content/drive/MyDrive/Cognilens_MLtraining

## 1. Imports and Setup

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, GridSearchCV, train_test_split
from sklearn.metrics import classification_report, roc_auc_score, f1_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBClassifier

## 2. Data Loading and Initial Cleaning

In [ ]:
import pandas as pd

# 1. Load Primary Dataset from the current working directory (which is your Drive folder)
df_student_activities = pd.read_csv("SocialMediaUse_export (4).csv")

cols_to_drop = [
    'notification_count', 'triggered_by_notification',
    'scroll_count', 'scroll_speed_estimate', 'avg_scroll_delta_px',
    'micro_scrolls', 'normal_scrolls', 'macro_scrolls',
    'scroll_behavior', 'detected_format'
]
df_student_activities = df_student_activities.drop(columns=[c for c in cols_to_drop if c in df_student_activities.columns], errors='ignore')

print("Initial data loaded and cleaned.")
display(df_student_activities.head())

Initial data loaded and cleaned.

,user_id,session_start,session_end,date,day_of_week,session_hour,time_of_day,app_label,duration_minutes,tap_count,minutes_since_last_session,day_asi_score,day_intensity_score,day_fragmentation_score,day_compulsion_score,day_disruption_score
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790281329502,1790281593063,2026-09-24,Thursday,23,night,Instagram,4.39,0,28.47,48,45,68,32,49
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790279631154,1790279723216,2026-09-24,Thursday,22,night,YouTube,1.53,0,33.34,48,45,68,32,49
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790279484659,1790279621543,2026-09-24,Thursday,22,night,Instagram,2.28,0,7.95,48,45,68,32,49
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790278804601,1790279007621,2026-09-24,Thursday,22,night,Instagram,3.38,2,2.64,48,45,68,32,49
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,1790278538451,1790278646464,2026-09-24,Thursday,22,night,Instagram,1.80,0,0.00,48,45,68,32,49

In [ ]:
from google.colab import files

# Save the initially cleaned DataFrame to a new CSV file
cleaned_output_filename = "cleaned_student_activities.csv"
df_student_activities.to_csv(cleaned_output_filename, index=False)

print(f"File '{cleaned_output_filename}' saved successfully. Downloading...")

# Trigger the download
files.download(cleaned_output_filename)

File 'cleaned_student_activities.csv' saved successfully. Downloading...

In [ ]:
!pip install pdfplumber pandas

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.13/dist-packages (0.11.10)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: pdfminer.six==20260107 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber) (5.13.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)

PDF TIMETABLE CONVERSION TO CSV USING API KEY

In [ ]:
from google.colab import files
import pdfplumber
import re
import pandas as pd
from datetime import datetime

In [ ]:
!pip install google-genai pdf2image pydantic pandas
!apt-get install -y poppler-utils

In [ ]:
from google.colab import userdata
userdata.get('secretName')

I'm broke right now but this will help with model training for now till I pay for API keys for to do pdf to csv that makes sense

In [ ]:
import pandas as pd

rows = [
    ["Monday", "08:15", "10:15", "ICS 4106",
     "Computer Simulation and Modelling", "C Ouma", "STM-B F2-05"],
    ["Monday", "10:15", "12:15", "ICS 4102",
     "Machine Learning", "J Wekesa", ""],
    ["Monday", "13:15", "14:15", "ICS 4103",
     "Cloud Computing", "V Ochango", ""],
    ["Monday", "15:15", "17:15", "ICS 3105",
     "Multimedia Applications", "Z Muti", ""],

    ["Tuesday", "08:15", "10:15", "ICS 4101",
     "ICS Project II", "K Omondi", ""],
    ["Tuesday", "10:15", "11:15", "",
     "Maisha Program 7 - Gents 4A", "P Neri", "RM B"],
    ["Tuesday", "11:15", "12:15", "",
     "Maisha Program 7 - Ladies ICS 4A", "R Bunde", "RM 10"],
    ["Tuesday", "13:15", "15:15", "ICS 4104",
     "Distributed Systems", "H Talo", "STM-B F2-05"],

    ["Wednesday", "08:15", "10:15", "ICS 4111",
     "Embedded Systems and Internet of Things", "A Vikiru", ""],
    ["Wednesday", "11:15", "12:15", "ICS 4106",
     "Computer Simulation and Modelling", "C Ouma", ""],
    ["Wednesday", "13:15", "15:15", "ICS 4104",
     "Distributed Systems", "H Talo", ""],
    ["Wednesday", "15:15", "17:15", "ICS 4103",
     "Cloud Computing", "V Ochango", "MSB 13"],

    ["Thursday", "08:15", "10:15", "ICS 4101",
     "ICS Project II", "K Omondi", "LT 6"],
    ["Thursday", "11:15", "13:15", "ICS 4111",
     "Embedded Systems and Internet of Things", "A Vikiru", "Masinga Lab"],
    ["Thursday", "15:15", "17:15", "ICS 3105",
     "Multimedia Applications", "Z Muti", "LT 6"],

    ["Friday", "08:15", "10:15", "ICS 4102",
     "Machine Learning", "J Wekesa", "LT 2"],
    ["Friday", "14:15", "17:15", "",
     "Sports/Clubs", "", ""],
]

columns = [
    "day", "start_time", "end_time",
    "unit_code", "unit_name", "lecturer", "venue"
]

timetable_df = pd.DataFrame(rows, columns=columns)

# Create an 'activity' column by combining 'unit_code' and 'unit_name'
def get_activity_name(row):
    if row['unit_code'].strip():
        if row['unit_name'].strip():
            return f"{row['unit_code']} - {row['unit_name']}"
        else:
            return row['unit_code']
    else:
        return row['unit_name']

timetable_df['activity'] = timetable_df.apply(get_activity_name, axis=1)

# put weekdays in calendar order
weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
timetable_df["day"] = pd.Categorical(
    timetable_df["day"],
    categories=weekday_order,
    ordered=True
)
timetable_df = timetable_df.sort_values(["day", "start_time"])

# Select only the desired 4 columns for the final CSV
df_final_csv = timetable_df[["day", "start_time", "end_time", "activity"]]

# Save the structured timetable
df_final_csv.to_csv("bics_4a_apr_jul_2026.csv", index=False)

Feature engineering - Timetable part

In [ ]:
import pandas as pd
import numpy as np

# 1. Load your generated timetable CSV
df_timetable = pd.read_csv("bics_4a_apr_jul_2026.csv")

# 2. Convert string time "HH:MM" to 24-hour decimal hours (e.g., "08:15" -> 8.25)
def time_to_decimal(time_str):
    if pd.isna(time_str):
        return np.nan
    hours, minutes = map(int, str(time_str).strip().split(":"))
    return hours + (minutes / 60.0)

df_timetable["start_decimal"] = df_timetable["start_time"].apply(time_to_decimal)
df_timetable["end_decimal"] = df_timetable["end_time"].apply(time_to_decimal)

# 3. Map day strings to standard numerical weekdays (Monday=0, Tuesday=1, ..., Sunday=6)
day_mapping = {
    "Monday": 0, "Tuesday": 1, "Wednesday": 2,
    "Thursday": 3, "Friday": 4, "Saturday": 5, "Sunday": 6
}
df_timetable["day_of_week"] = df_timetable["day"].map(day_mapping)

# 4. Binary Indicator: Flag scheduled commitments
df_timetable["is_scheduled_commitment"] = 1

print("=== PROCESSED TIMETABLE FEATURE MAP ===")
display(df_timetable[["day", "day_of_week", "start_decimal", "end_decimal", "activity", "is_scheduled_commitment"]])

=== PROCESSED TIMETABLE FEATURE MAP ===

,day,day_of_week,start_decimal,end_decimal,activity,is_scheduled_commitment
0,Monday,0,8.25,10.25,ICS 4106 - Computer Simulation and Modelling,1
1,Monday,0,10.25,12.25,ICS 4102 - Machine Learning,1
2,Monday,0,13.25,14.25,ICS 4103 - Cloud Computing,1
3,Monday,0,15.25,17.25,ICS 3105 - Multimedia Applications,1
4,Tuesday,1,8.25,10.25,ICS 4101 - ICS Project II,1
5,Tuesday,1,10.25,11.25,Maisha Program 7 - Gents 4A,1
6,Tuesday,1,11.25,12.25,Maisha Program 7 - Ladies ICS 4A,1
7,Tuesday,1,13.25,15.25,ICS 4104 - Distributed Systems,1
8,Wednesday,2,8.25,10.25,ICS 4111 - Embedded Systems and Internet of Th...,1
9,Wednesday,2,11.25,12.25,ICS 4106 - Computer Simulation and Modelling,1
10,Wednesday,2,13.25,15.25,ICS 4104 - Distributed Systems,1
11,Wednesday,2,15.25,17.25,ICS 4103 - Cloud Computing,1
12,Thursday,3,8.25,10.25,ICS 4101 - ICS Project II,1
13,Thursday,3,11.25,13.25,ICS 4111 - Embedded Systems and Internet of Th...,1
14,Thursday,3,15.25,17.25,ICS 3105 - Multimedia Applications,1
15,Friday,4,8.25,10.25,ICS 4102 - Machine Learning,1
16,Friday,4,14.25,17.25,Sports/Clubs,1

Mapping Timetable features to Cognilens student logs

In [ ]:
import pandas as pd

# ---------------------------------------------------------
# 1. Use the existing student dataset
# ---------------------------------------------------------

df_student_activities = df_student_activities.copy()

# Create a 'timestamp' column from 'session_start' (Unix milliseconds)
df_student_activities["timestamp_utc"] = pd.to_datetime(
    df_student_activities["session_start"],
    unit="ms",
    utc=True
)

df_student_activities["timestamp_local"] = (
    df_student_activities["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# ---------------------------------------------------------
# 2. Make sure timetable times are represented in minutes
# ---------------------------------------------------------

def time_to_minutes(time_str):
    if pd.isna(time_str):
        return None

    hours, minutes = map(int, str(time_str).strip().split(":"))
    return hours * 60 + minutes


df_timetable["start_minute"] = (
    df_timetable["start_time"].apply(time_to_minutes)
)

df_timetable["end_minute"] = (
    df_timetable["end_time"].apply(time_to_minutes)
)

# ---------------------------------------------------------
# 3. Match each session against the shared timetable
# ---------------------------------------------------------

def evaluate_schedule_conflict(timestamp, timetable_df):

    if pd.isna(timestamp):
        return 0

    event_day = timestamp.weekday()

    event_minute = (
        timestamp.hour * 60
        + timestamp.minute
    )

    day_classes = timetable_df[
        timetable_df["day_of_week"] == event_day
    ]

    conflict = day_classes[
        (day_classes["start_minute"] <= event_minute) &
        (event_minute < day_classes["end_minute"])
    ]

    return int(not conflict.empty)


# ---------------------------------------------------------
# 4. Apply the timetable mapping
# ---------------------------------------------------------

df_student_activities["is_schedule_conflict"] = (
    df_student_activities["timestamp_local"].apply(
        lambda ts: evaluate_schedule_conflict(
            ts,
            df_timetable
        )
    )
)
# ---------------------------------------------------------
# 5. Inspect results
# ---------------------------------------------------------

print("Schedule conflict mapping complete.")

print("\nConflict distribution:")
print(
    df_student_activities["is_schedule_conflict"]
    .value_counts()
)

print("\nFirst 10 mapped sessions:")
display(
    df_student_activities[
        [
            "user_id",
            "timestamp_local",
            "day_of_week",
            "session_hour",
            "app_label",
            "duration_minutes",
            "is_schedule_conflict"
        ]
    ].head(10)
)

Schedule conflict mapping complete.

Conflict distribution:
is_schedule_conflict
0    398
1    104
Name: count, dtype: int64

First 10 mapped sessions:

,user_id,timestamp_local,day_of_week,session_hour,app_label,duration_minutes,is_schedule_conflict
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 23:22:09.502000+03:00,Thursday,23,Instagram,4.39,0
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:53:51.154000+03:00,Thursday,22,YouTube,1.53,0
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:51:24.659000+03:00,Thursday,22,Instagram,2.28,0
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:40:04.601000+03:00,Thursday,22,Instagram,3.38,0
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:35:38.451000+03:00,Thursday,22,Instagram,1.80,0
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:30:19.366000+03:00,Thursday,22,Instagram,5.32,0
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:26:02.199000+03:00,Thursday,22,Instagram,2.01,0
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:18:54.137000+03:00,Thursday,22,YouTube,1.61,0
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:13:01.561000+03:00,Thursday,22,Instagram,5.69,0
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 22:00:38.696000+03:00,Thursday,22,Instagram,0.92,0

In [ ]:
from google.colab import files

# Save the DataFrame to a new CSV file
output_filename = "student_activities_with_conflicts.csv"
df_student_activities.to_csv(output_filename, index=False)

print(f"File '{output_filename}' saved successfully. Downloading...")

# Trigger the download
files.download(output_filename)

File 'student_activities_with_conflicts.csv' saved successfully. Downloading...

Noticed an issue with the timezone, UTC/ East African time

In [ ]:
# Compare the existing session_hour with the actual timestamp hour

df_student_activities["timestamp_hour_check"] = (
    df_student_activities["timestamp"].dt.hour
)

comparison = df_student_activities[
    ["timestamp", "session_hour", "timestamp_hour_check"]
].head(20)

display(comparison)

# Count mismatches
mismatch_count = (
    df_student_activities["session_hour"]
    != df_student_activities["timestamp_hour_check"]
).sum()

print(f"Total rows: {len(df_student_activities)}")
print(f"Hour mismatches: {mismatch_count}")
print(
    f"Mismatch percentage: "
    f"{mismatch_count / len(df_student_activities) * 100:.2f}%"
)

In [ ]:
df_student_activities["timestamp_utc"] = pd.to_datetime(
    df_student_activities["session_start"],
    unit="ms",
    utc=True
)

df_student_activities["timestamp_local"] = (
    df_student_activities["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

In [ ]:
display(
    df_student_activities[
        [
            "session_start",
            "timestamp_utc",
            "timestamp_local",
            "session_hour"
        ]
    ].head(10)
)

Feature Engineering of selected features

In [ ]:

# ---------------------------------------------------------
# CogniLens: Initial behavioural feature engineering
# ---------------------------------------------------------

import pandas as pd
import numpy as np

# Work on a copy
df_features = df_student_activities.copy()

# Ensure records are chronologically ordered per user
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# ---------------------------------------------------------
# 1. TEMPORAL FEATURES
# ---------------------------------------------------------

df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

df_features["local_hour"] = (
    df_features["timestamp_local"].dt.hour
)

df_features["day_of_week"] = (
    df_features["timestamp_local"].dt.dayofweek
)

# ---------------------------------------------------------
# 2. COMPULSIVE-USE INDICATORS
# ---------------------------------------------------------

# Calculate gap from the previous session for the same user.
# This is derived from timestamps rather than assuming
# missing gaps represent a fixed duration.


# Convert session_end from Unix milliseconds to local time
df_features["session_end_utc"] = pd.to_datetime(
    df_features["session_end"],
    unit="ms",
    utc=True
)

df_features["session_end_local"] = (
    df_features["session_end_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# Sort chronologically within each user
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# Previous session's end time for each user
df_features["previous_session_end"] = (
    df_features.groupby("user_id")["session_end_local"].shift(1)
)

# Actual time between the previous session ending
# and the current session starting
df_features["session_gap_minutes"] = (
    (
        df_features["timestamp_local"]
        - df_features["previous_session_end"]
    ).dt.total_seconds() / 60
)

# Count sessions per user per local day
df_features["daily_session_count"] = (
    df_features.groupby(["user_id", "local_date"])
    ["timestamp_local"]
    .transform("count")
)

# ---------------------------------------------------------
# 3. SCHEDULE DISRUPTION
# ---------------------------------------------------------

# This is contextual, not proof of neglected responsibility.
df_features["is_schedule_conflict"] = pd.to_numeric(
    df_features["is_schedule_conflict"],
    errors="coerce"
)

# ---------------------------------------------------------
# 4. DURATION AND DAILY USAGE
# ---------------------------------------------------------

df_features["duration_minutes"] = pd.to_numeric(
    df_features["duration_minutes"],
    errors="coerce"
)

# Sum of session durations per user per local day
df_features["daily_usage_minutes"] = (
    df_features.groupby(["user_id", "local_date"])
    ["duration_minutes"]
    .transform("sum")
)

INDIVIDUAL BASELINE CALCULATION

In [ ]:

# Ensure chronological order
df_features = df_features.sort_values(
    ["user_id", "timestamp_local"]
).reset_index(drop=True)

# Calculate median duration from previous sessions only
df_features["previous_median_duration"] = (
    df_features.groupby("user_id")["duration_minutes"]
    .transform(
        lambda s: s.shift(1).expanding(min_periods=5).median()
    )
)

# Current duration minus historical median
df_features["duration_baseline_deviation"] = (
    df_features["duration_minutes"]
    - df_features["previous_median_duration"]
)

# Current duration relative to historical median
df_features["duration_baseline_ratio"] = (
    df_features["duration_minutes"]
    / df_features["previous_median_duration"].replace(0, np.nan)
)

# Inspect the first 15 sessions
display(
    df_features[
        [
            "timestamp_local",
            "duration_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(15)
)

,timestamp_local,duration_minutes,previous_median_duration,duration_baseline_deviation,duration_baseline_ratio
0,2026-09-02 15:42:42.152000+03:00,8.43,NaN,NaN,NaN
1,2026-09-02 17:31:20.020000+03:00,0.62,NaN,NaN,NaN
2,2026-09-02 17:32:57.877000+03:00,2.61,NaN,NaN,NaN
3,2026-09-02 17:35:34.725000+03:00,0.72,NaN,NaN,NaN
4,2026-09-02 17:37:01.411000+03:00,0.64,NaN,NaN,NaN
5,2026-09-02 17:38:05.397000+03:00,1.26,0.720,0.540,1.750000
6,2026-09-02 17:39:21.029000+03:00,0.93,0.990,-0.060,0.939394
7,2026-09-02 17:45:07.658000+03:00,0.90,0.930,-0.030,0.967742
8,2026-09-02 17:46:18.607000+03:00,2.19,0.915,1.275,2.393443
9,2026-09-02 17:48:30.079000+03:00,1.19,0.930,0.260,1.279570
10,2026-09-02 19:15:50.864000+03:00,2.98,1.060,1.920,2.811321
11,2026-09-02 19:20:52.009000+03:00,3.63,1.190,2.440,3.050420
12,2026-09-02 19:24:39.124000+03:00,2.74,1.225,1.515,2.236735
13,2026-09-02 19:28:46.339000+03:00,2.86,1.260,1.600,2.269841
14,2026-09-02 19:31:40.960000+03:00,1.73,1.725,0.005,1.002899

In [ ]:
# ---------------------------------------------------------
# Recalculate real-time daily usage features
# ---------------------------------------------------------

# Make sure records are chronologically ordered
df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Local date
df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

# Number of previous sessions by this user on the same day
df_features["prior_daily_session_count"] = (
    df_features
    .groupby(["user_id", "local_date"])
    .cumcount()
)

# Previous sessions' duration
# Shift BEFORE calculating the cumulative sum so that
# the current session is never included.
df_features["prior_daily_usage_minutes"] = (
    df_features
    .groupby(["user_id", "local_date"])["duration_minutes"]
    .transform(
        lambda s: s.shift(1).fillna(0).cumsum()
    )
)

# ---------------------------------------------------------
# Verify
# ---------------------------------------------------------

print("Real-time feature columns created successfully.")

display(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes"
        ]
    ].head(15)
)

Real-time feature columns created successfully.

,user_id,timestamp_local,duration_minutes,prior_daily_session_count,prior_daily_usage_minutes
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 15:42:42.152000+03:00,8.43,0,0.00
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:31:20.020000+03:00,0.62,1,8.43
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:32:57.877000+03:00,2.61,2,9.05
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:35:34.725000+03:00,0.72,3,11.66
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:37:01.411000+03:00,0.64,4,12.38
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:38:05.397000+03:00,1.26,5,13.02
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:39:21.029000+03:00,0.93,6,14.28
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:45:07.658000+03:00,0.90,7,15.21
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:46:18.607000+03:00,2.19,8,16.11
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:48:30.079000+03:00,1.19,9,18.30
10,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:15:50.864000+03:00,2.98,10,19.49
11,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:20:52.009000+03:00,3.63,11,22.47
12,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:24:39.124000+03:00,2.74,12,26.10
13,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:28:46.339000+03:00,2.86,13,28.84
14,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:31:40.960000+03:00,1.73,14,31.70

In [ ]:

print("Negative session gaps:")
print(
    (df_features["session_gap_minutes"] < 0).sum()
)

print("\nMissing session gaps:")
print(
    df_features["session_gap_minutes"].isna().sum()
)

print("\nGap statistics:")
display(
    df_features["session_gap_minutes"].describe()
)

print("\nReal-time features:")
display(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "session_gap_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(15)
)

Negative session gaps:
0

Missing session gaps:
1

Gap statistics:

count     501.000000
mean       57.279728
std       162.038137
min         0.000100
25%         0.507233
50%         2.744083
75%        25.692150
max      1345.372033
Name: session_gap_minutes, dtype: float64

Real-time features:

,user_id,timestamp_local,duration_minutes,session_gap_minutes,prior_daily_session_count,prior_daily_usage_minutes,previous_median_duration,duration_baseline_deviation,duration_baseline_ratio
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 15:42:42.152000+03:00,8.43,NaN,0,0.00,NaN,NaN,NaN
1,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:31:20.020000+03:00,0.62,100.196983,1,8.43,NaN,NaN,NaN
2,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:32:57.877000+03:00,2.61,1.006717,2,9.05,NaN,NaN,NaN
3,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:35:34.725000+03:00,0.72,0.000183,3,11.66,NaN,NaN,NaN
4,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:37:01.411000+03:00,0.64,0.728583,4,12.38,NaN,NaN,NaN
5,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:38:05.397000+03:00,1.26,0.425200,5,13.02,0.720,0.540,1.750000
6,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:39:21.029000+03:00,0.93,0.000367,6,14.28,0.990,-0.060,0.939394
7,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:45:07.658000+03:00,0.90,4.847017,7,15.21,0.930,-0.030,0.967742
8,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:46:18.607000+03:00,2.19,0.285300,8,16.11,0.915,1.275,2.393443
9,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 17:48:30.079000+03:00,1.19,0.000400,9,18.30,0.930,0.260,1.279570
10,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:15:50.864000+03:00,2.98,86.158617,10,19.49,1.060,1.920,2.811321
11,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:20:52.009000+03:00,3.63,2.040283,11,22.47,1.190,2.440,3.050420
12,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:24:39.124000+03:00,2.74,0.154400,12,26.10,1.225,1.515,2.236735
13,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:28:46.339000+03:00,2.86,1.381000,13,28.84,1.260,1.600,2.269841
14,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-02 19:31:40.960000+03:00,1.73,0.048400,14,31.70,1.725,0.005,1.002899

Check for duplicate sessions

In [ ]:

# ---------------------------------------------------------
# Session data quality checks
# ---------------------------------------------------------

# 1. Duplicate sessions
duplicates = df_features.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("Duplicate session records:", duplicates.sum())

# 2. Negative session durations
print(
    "Negative durations:",
    (df_features["duration_minutes"] < 0).sum()
)

# 3. Overlapping sessions
print(
    "Overlapping session gaps:",
    (df_features["session_gap_minutes"] < 0).sum()
)

# 4. Zero-duration sessions
print(
    "Zero-duration sessions:",
    (df_features["duration_minutes"] == 0).sum()
)

# 5. Missing values in key features
key_features = [
    "duration_minutes",
    "session_gap_minutes",
    "is_schedule_conflict",
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio"
]

print("\nMissing values:")
display(df_features[key_features].isna().sum().to_frame("missing_count"))

# 6. Duration and gap distributions
print("\nDuration statistics:")
display(df_features["duration_minutes"].describe())

print("\nSession gap statistics:")
display(df_features["session_gap_minutes"].describe())

Duplicate session records: 0
Negative durations: 0
Overlapping session gaps: 0
Zero-duration sessions: 0

Missing values:

                             missing_count
duration_minutes                         0
session_gap_minutes                      1
is_schedule_conflict                     0
previous_median_duration                 5
duration_baseline_deviation              5
duration_baseline_ratio                  5

Duration statistics:

count    502.000000
mean       6.865976
std       13.017645
min        0.500000
25%        1.032500
50%        2.285000
75%        6.210000
max      138.600000
Name: duration_minutes, dtype: float64

Session gap statistics:

count     501.000000
mean       57.279728
std       162.038137
min         0.000100
25%         0.507233
50%         2.744083
75%        25.692150
max      1345.372033
Name: session_gap_minutes, dtype: float64

In [ ]:
print("Unique users:", df_features["user_id"].nunique())

print("\nSessions longer than 30 minutes:")
display(
    df_features.loc[
        df_features["duration_minutes"] > 30,
        ["user_id", "timestamp_local", "duration_minutes", "app_label"]
    ].sort_values("duration_minutes", ascending=False)
)

print("\nLongest session gaps:")
display(
    df_features.nlargest(
        10, "session_gap_minutes"
    )[[
        "user_id",
        "timestamp_local",
        "session_gap_minutes"
    ]]
)

Unique users: 1

Sessions longer than 30 minutes:

,user_id,timestamp_local,duration_minutes,app_label
296,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-16 12:08:46.327000+03:00,138.60,Instagram
337,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-18 19:27:21.480000+03:00,93.26,Instagram
290,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-16 09:41:31.608000+03:00,78.02,Instagram
223,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-11 21:53:17.444000+03:00,75.74,Instagram
449,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-23 00:38:41.757000+03:00,66.49,Instagram
62,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-04 20:25:46.937000+03:00,61.18,Instagram
58,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-04 17:41:02.844000+03:00,55.54,Instagram
248,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-12 19:09:09.884000+03:00,55.25,Instagram
144,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-09 09:21:26.390000+03:00,54.54,Instagram
77,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-06 14:47:14.636000+03:00,54.44,Instagram
452,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-23 09:26:49.222000+03:00,49.05,Instagram
422,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-21 21:39:12.744000+03:00,48.45,Instagram
411,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-20 22:47:32.556000+03:00,46.57,Instagram
347,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-19 11:15:10.072000+03:00,46.28,Instagram
487,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 11:36:16.522000+03:00,41.51,YouTube
295,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-16 11:27:12.341000+03:00,41.35,Instagram
424,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-21 22:36:40.074000+03:00,41.29,Instagram
414,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-21 18:43:33.308000+03:00,34.29,Instagram
124,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-08 18:08:07.930000+03:00,33.60,Instagram
346,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-19 10:35:19.337000+03:00,33.30,Instagram
288,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-16 08:30:48.435000+03:00,33.08,Instagram
425,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-22 19:59:38.386000+03:00,32.57,Instagram
145,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-09 10:16:08.595000+03:00,32.54,Instagram
417,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-21 20:38:40.622000+03:00,32.03,Instagram
237,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-12 14:09:44.500000+03:00,31.55,Instagram
416,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-21 19:53:14.358000+03:00,30.20,Instagram

Longest session gaps:

,user_id,timestamp_local,session_gap_minutes
65,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-05 20:14:12.141000+03:00,1345.372033
425,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-22 19:59:38.386000+03:00,1241.682733
385,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-20 13:22:54.031000+03:00,859.866583
266,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-14 10:37:31.496000+03:00,854.591683
276,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-15 12:10:12.848000+03:00,834.783783
250,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-13 09:55:17.825000+03:00,827.652850
332,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-18 18:55:02.108000+03:00,772.307500
109,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-08 10:31:22.975000+03:00,745.051733
343,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-19 10:22:08.741000+03:00,720.263667
486,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,2026-09-24 11:30:03.896000+03:00,713.501583

INDIVIDUAL DATASET PROCESSING

In [49]:
import pandas as pd
import os
import glob

files = glob.glob("/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export*.csv")

for file in sorted(files):
    temp = pd.read_csv(file)

    print(f"\nFile: {os.path.basename(file)}")
    print("Rows:", len(temp))

    if "user_id" in temp.columns:
        print("Unique users:", temp["user_id"].nunique())
        print("User IDs:")
        print(temp["user_id"].value_counts().to_string())
    else:
        print("No user_id column")

    print("Columns:", temp.columns.tolist())

File: SocialMediaUse_export (1).csv
Rows: 645
Unique users: 1
User IDs:
user_id
85bfc215-c24f-4814-aa00-6794f1a7278a    645
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export (2).csv
Rows: 708
Unique users: 1
User IDs:
user_id
85bfc215-c24f-4814-aa00-6794f1a7278a    708
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export (3).csv
Rows: 171
Unique users: 1
User IDs:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    171
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export (4).csv
Rows: 502
Unique users: 1
User IDs:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    502
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export 5.csv
Rows: 183
Unique users: 1
User IDs:
user_id
e7642be3-461d-4c8e-98cd-0eccc76764ec    183
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export 6.csv
Rows: 307
Unique users: 1
User IDs:
user_id
f5e00193-6fb8-4767-ba5e-5c824dc24c89    307
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

File: SocialMediaUse_export.csv
Rows: 3712
Unique users: 2
User IDs:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    3540
d5a62f7a-97c9-481c-83be-f0a06b70cad9     172
Columns: ['user_id', 'session_start', 'session_end', 'date', 'day_of_week', 'session_hour', 'time_of_day', 'app_label', 'detected_format', 'duration_minutes', 'scroll_count', 'tap_count', 'scroll_speed_estimate', 'avg_scroll_delta_px', 'micro_scrolls', 'normal_scrolls', 'macro_scrolls', 'scroll_behavior', 'notification_count', 'triggered_by_notification', 'minutes_since_last_session', 'day_asi_score', 'day_intensity_score', 'day_fragmentation_score', 'day_compulsion_score', 'day_disruption_score']

In [51]:
import pandas as pd
import glob
import os

files = glob.glob("/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export*.csv")

for file in sorted(files):
    temp = pd.read_csv(file)

    print(f"\n{'='*70}")
    print(os.path.basename(file))
    print(f"Rows: {len(temp)}")

    if "user_id" in temp.columns:
        print(f"Users: {temp['user_id'].nunique(dropna=True)}")
        print("User IDs:")
        print(temp["user_id"].dropna().unique())

    if "date" in temp.columns:
        print(f"Date range: {temp['date'].min()} → {temp['date'].max()}")

    if "session_start" in temp.columns:
        print(
            "Session start range:",
            temp["session_start"].min(),
            "→",
            temp["session_start"].max()
        )

    print("Missing user_id:", temp["user_id"].isna().sum())

======================================================================
SocialMediaUse_export (1).csv
Rows: 645
Users: 1
User IDs:
['85bfc215-c24f-4814-aa00-6794f1a7278a']
Date range: 2026-04-09 → 2026-06-04
Session start range: 1775714023406 → 1780569727573
Missing user_id: 0

======================================================================
SocialMediaUse_export (2).csv
Rows: 708
Users: 1
User IDs:
['85bfc215-c24f-4814-aa00-6794f1a7278a']
Date range: 2026-04-09 → 2026-07-12
Session start range: 1775714023406 → 1783889909076
Missing user_id: 0

======================================================================
SocialMediaUse_export (3).csv
Rows: 171
Users: 1
User IDs:
['46b5fe4a-2c09-4006-bd5b-08bf12ece5e4']
Date range: 2026-09-02 → 2026-09-09
Session start range: 1788352962152 → 1788952677459
Missing user_id: 0

======================================================================
SocialMediaUse_export (4).csv
Rows: 502
Users: 1
User IDs:
['46b5fe4a-2c09-4006-bd5b-08bf12ece5e4']
Date range: 2026-09-02 → 2026-09-24
Session start range: 1788352962152 → 1790281329502
Missing user_id: 0

======================================================================
SocialMediaUse_export 5.csv
Rows: 183
Users: 1
User IDs:
['e7642be3-461d-4c8e-98cd-0eccc76764ec']
Date range: 2026-09-22 → 2026-09-29
Session start range: 1790104003060 → 1790702043428
Missing user_id: 0

======================================================================
SocialMediaUse_export 6.csv
Rows: 307
Users: 1
User IDs:
['f5e00193-6fb8-4767-ba5e-5c824dc24c89']
Date range: 2026-09-23 → 2026-09-29
Session start range: 1790146682956 → 1790686457000
Missing user_id: 0

======================================================================
SocialMediaUse_export.csv
Rows: 3712
Users: 2
User IDs:
['8cf97b0c-76c9-4d72-b617-759a955f969f'
 'd5a62f7a-97c9-481c-83be-f0a06b70cad9']
Date range: 2026-04-16 → 2026-09-29
Session start range: 1776366421509 → 1790711732181
Missing user_id: 0

In [52]:
import pandas as pd
import os

candidate_files = [
    "SocialMediaUse_export (2).csv",
    "SocialMediaUse_export (4).csv",
    "SocialMediaUse_export.csv",
    "SocialMediaUse_export 5.csv",
    "SocialMediaUse_export 6.csv"
]

for file in candidate_files:

    temp = pd.read_csv(f"/content/drive/MyDrive/Cognilens_MLtraining/{file}")

    print("\n" + "=" * 70)
    print(file)

    # Duplicate session records
    if "session_start" in temp.columns and "user_id" in temp.columns:
        duplicates = temp.duplicated(
            subset=["user_id", "session_start"],
            keep=False
        )

        print("Duplicate user/session-start records:", duplicates.sum())

    # Missingness
    print("Rows:", len(temp))
    print("Missing user_id:", temp["user_id"].isna().sum())

    # User distribution
    print("\nUsers:")
    print(temp["user_id"].value_counts(dropna=False))

    # Date range
    if "date" in temp.columns:
        print(
            "\nDate range:",
            temp["date"].min(),
            "→",
            temp["date"].max()
        )

======================================================================
SocialMediaUse_export (2).csv
Duplicate user/session-start records: 0
Rows: 708
Missing user_id: 0

Users:
user_id
85bfc215-c24f-4814-aa00-6794f1a7278a    708
Name: count, dtype: int64

Date range: 2026-04-09 → 2026-07-12

======================================================================
SocialMediaUse_export (4).csv
Duplicate user/session-start records: 0
Rows: 502
Missing user_id: 0

Users:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4    502
Name: count, dtype: int64

Date range: 2026-09-02 → 2026-09-24

======================================================================
SocialMediaUse_export.csv
Duplicate user/session-start records: 0
Rows: 3712
Missing user_id: 0

Users:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    3540
d5a62f7a-97c9-481c-83be-f0a06b70cad9     172
Name: count, dtype: int64

Date range: 2026-04-16 → 2026-09-29

======================================================================
SocialMediaUse_export 5.csv
Duplicate user/session-start records: 0
Rows: 183
Missing user_id: 0

Users:
user_id
e7642be3-461d-4c8e-98cd-0eccc76764ec    183
Name: count, dtype: int64

Date range: 2026-09-22 → 2026-09-29

======================================================================
SocialMediaUse_export 6.csv
Duplicate user/session-start records: 0
Rows: 307
Missing user_id: 0

Users:
user_id
f5e00193-6fb8-4767-ba5e-5c824dc24c89    307
Name: count, dtype: int64

Date range: 2026-09-23 → 2026-09-29

COMBINED PARTICIPANT DATASET

In [53]:
import pandas as pd

# Load canonical source files
df_user_1 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export (2).csv"
)

df_user_2 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export (4).csv"
)

df_users_3_4 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export.csv"
)

df_user_5 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export 5.csv"
)

df_user_6 = pd.read_csv(
    "/content/drive/MyDrive/Cognilens_MLtraining/SocialMediaUse_export 6.csv"
)

# Combine
df_all = pd.concat(
    [
        df_user_1,
        df_user_2,
        df_users_3_4,
        df_user_5,
        df_user_6
    ],
    ignore_index=True
)

print("Total sessions:", len(df_all))
print("Unique users:", df_all["user_id"].nunique())

print("\nSessions per user:")
display(
    df_all.groupby("user_id")
    .size()
    .reset_index(name="session_count")
)

# Global duplicate check
duplicates = df_all.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("\nDuplicate user/session-start records:", duplicates.sum())

Total sessions: 5412
Unique users: 6

Sessions per user:

                                user_id  session_count
0  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4            502
1  85bfc215-c24f-4814-aa00-6794f1a7278a            708
2  8cf97b0c-76c9-4d72-b617-759a955f969f           3540
3  d5a62f7a-97c9-481c-83be-f0a06b70cad9            172
4  e7642be3-461d-4c8e-98cd-0eccc76764ec            183
5  f5e00193-6fb8-4767-ba5e-5c824dc24c89            307

Duplicate user/session-start records: 0

DATASET AUDIT AND INTEGRITY

In [55]:
# ============================================
# DATASET INTEGRITY AUDIT
# ============================================

print("========== DATASET OVERVIEW ==========")
print("Total sessions:", len(df_all))
print("Unique users:", df_all["user_id"].nunique())

print("\n========== DUPLICATES ==========")

duplicate_pairs = df_all.duplicated(
    subset=["user_id", "session_start"],
    keep=False
)

print("Duplicate user/session-start records:",
      duplicate_pairs.sum())

print("\n========== MISSING VALUES ==========")

missing_summary = (
    df_all.isna()
    .sum()
    .reset_index()
)

missing_summary.columns = ["column", "missing_count"]

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"] / len(df_all) * 100
)

display(
    missing_summary[
        missing_summary["missing_count"] > 0
    ].sort_values("missing_percentage", ascending=False)
)

print("\n========== DATA TYPES ==========")
print(df_all.dtypes)

print("\n========== SESSION DURATION ==========")

print(
    df_all["duration_minutes"].describe()
)

print("\n========== USERS ==========")

display(
    df_all.groupby("user_id")
    .agg(
        sessions=("user_id", "size"),
        mean_duration=("duration_minutes", "mean"),
        median_duration=("duration_minutes", "median"),
        total_usage_minutes=("duration_minutes", "sum")
    )
    .reset_index()
)

print("\n========== DATE RANGE ==========")

print("Earliest date:", df_all["date"].min())
print("Latest date:", df_all["date"].max())

========== DATASET OVERVIEW ==========
Total sessions: 5412
Unique users: 6

========== DUPLICATES ==========
Duplicate user/session-start records: 0

========== MISSING VALUES ==========

                        column  missing_count  missing_percentage
17             scroll_behavior           5194           95.971914
20  minutes_since_last_session             18            0.332594

========== DATA TYPES ==========
user_id                        object
session_start                   int64
session_end                     int64
date                           object
day_of_week                    object
session_hour                    int64
time_of_day                    object
app_label                      object
detected_format                object
duration_minutes              float64
scroll_count                    int64
tap_count                       int64
scroll_speed_estimate         float64
avg_scroll_delta_px             int64
micro_scrolls                   int64
normal_scrolls                  int64
macro_scrolls                   int64
scroll_behavior                object
notification_count              int64
triggered_by_notification        bool
minutes_since_last_session    float64
day_asi_score                   int64
day_intensity_score             int64
day_fragmentation_score         int64
day_compulsion_score            int64
day_disruption_score            int64
dtype: object

========== SESSION DURATION ==========
count    5412.000000
mean        6.364581
std        12.899891
min         0.500000
25%         1.067500
50%         2.450000
75%         6.432500
max       380.280000
Name: duration_minutes, dtype: float64

========== USERS ==========

,user_id,sessions,mean_duration,median_duration,total_usage_minutes
0,46b5fe4a-2c09-4006-bd5b-08bf12ece5e4,502,6.865976,2.285,3446.72
1,85bfc215-c24f-4814-aa00-6794f1a7278a,708,9.351935,3.790,6621.17
2,8cf97b0c-76c9-4d72-b617-759a955f969f,3540,5.798130,2.385,20525.38
3,d5a62f7a-97c9-481c-83be-f0a06b70cad9,172,6.233140,2.115,1072.10
4,e7642be3-461d-4c8e-98cd-0eccc76764ec,183,11.288251,7.050,2065.75
5,f5e00193-6fb8-4767-ba5e-5c824dc24c89,307,2.325700,1.210,713.99

========== DATE RANGE ==========
Earliest date: 2026-04-09
Latest date: 2026-09-29

In [56]:
print("========== TIMESTAMP CHECK ==========")

print("Missing session_start:",
      df_all["session_start"].isna().sum())

print("Missing session_end:",
      df_all["session_end"].isna().sum())

print("\nSession start data type:")
print(df_all["session_start"].dtype)

print("\nSession end data type:")
print(df_all["session_end"].dtype)

print("\nSample timestamps:")
display(
    df_all[
        ["user_id", "session_start", "session_end", "date", "session_hour"]
    ].head(10)
)

========== TIMESTAMP CHECK ==========
Missing session_start: 0
Missing session_end: 0

Session start data type:
int64

Session end data type:
int64

Sample timestamps:

,user_id,session_start,session_end,date,session_hour
0,85bfc215-c24f-4814-aa00-6794f1a7278a,1783889909076,1783890023674,2026-07-12,23
1,85bfc215-c24f-4814-aa00-6794f1a7278a,1783889342907,1783889898338,2026-07-12,23
2,85bfc215-c24f-4814-aa00-6794f1a7278a,1783887454981,1783888072008,2026-07-12,23
3,85bfc215-c24f-4814-aa00-6794f1a7278a,1783882413067,1783883571231,2026-07-12,21
4,85bfc215-c24f-4814-aa00-6794f1a7278a,1783882027872,1783882405234,2026-07-12,21
5,85bfc215-c24f-4814-aa00-6794f1a7278a,1783881837402,1783882015997,2026-07-12,21
6,85bfc215-c24f-4814-aa00-6794f1a7278a,1783880117282,1783880483307,2026-07-12,21
7,85bfc215-c24f-4814-aa00-6794f1a7278a,1783879842467,1783880091939,2026-07-12,21
8,85bfc215-c24f-4814-aa00-6794f1a7278a,1783878863089,1783879666339,2026-07-12,20
9,85bfc215-c24f-4814-aa00-6794f1a7278a,1783878306397,1783878812562,2026-07-12,20

In [57]:
# ============================================
# TIMESTAMP VALIDATION
# ============================================

import pandas as pd

# Convert timestamps without modifying df_all yet
start_utc = pd.to_datetime(
    df_all["session_start"],
    unit="ms",
    utc=True,
    errors="coerce"
)

end_utc = pd.to_datetime(
    df_all["session_end"],
    unit="ms",
    utc=True,
    errors="coerce"
)

print("Invalid session_start timestamps:", start_utc.isna().sum())
print("Invalid session_end timestamps:", end_utc.isna().sum())

print("\nEarliest session start:")
print(start_utc.min())

print("\nLatest session start:")
print(start_utc.max())

print("\nEarliest session end:")
print(end_utc.min())

print("\nLatest session end:")
print(end_utc.max())


# ============================================
# SESSION DURATION CONSISTENCY
# ============================================

calculated_duration = (
    end_utc - start_utc
).dt.total_seconds() / 60

timestamp_duration_difference = (
    calculated_duration - df_all["duration_minutes"]
)

print("\n========== DURATION VALIDATION ==========")

print(
    "Negative timestamp durations:",
    (calculated_duration < 0).sum()
)

print(
    "Zero timestamp durations:",
    (calculated_duration == 0).sum()
)

print(
    "Duration differences > 1 second:",
    (timestamp_duration_difference.abs() > (1 / 60)).sum()
)

print("\nCalculated duration statistics:")
print(calculated_duration.describe())

print("\nRecorded duration statistics:")
print(df_all["duration_minutes"].describe())


# ============================================
# OVERLAPPING SESSIONS
# ============================================

temp = df_all.copy()

temp["start_utc"] = start_utc
temp["end_utc"] = end_utc

temp = temp.sort_values(
    ["user_id", "start_utc"]
).reset_index(drop=True)

temp["previous_end_utc"] = (
    temp.groupby("user_id")["end_utc"].shift(1)
)

temp["session_gap_minutes"] = (
    temp["start_utc"] - temp["previous_end_utc"]
).dt.total_seconds() / 60

print("\n========== SESSION OVERLAPS ==========")

print(
    "Overlapping sessions:",
    (temp["session_gap_minutes"] < 0).sum()
)

print(
    "Zero-gap sessions:",
    (temp["session_gap_minutes"] == 0).sum()
)

print("\nSession gap statistics:")
print(temp["session_gap_minutes"].describe())

Invalid session_start timestamps: 0
Invalid session_end timestamps: 0

Earliest session start:
2026-04-09 05:53:43.406000+00:00

Latest session start:
2026-09-29 19:55:32.181000+00:00

Earliest session end:
2026-04-09 05:59:04.446000+00:00

Latest session end:
2026-09-29 20:01:28.004000+00:00

========== DURATION VALIDATION ==========
Negative timestamp durations: 0
Zero timestamp durations: 0
Duration differences > 1 second: 0

Calculated duration statistics:
count    5412.000000
mean        6.364586
std        12.899949
min         0.500000
25%         1.065004
50%         2.448742
75%         6.434717
max       380.283333
dtype: float64

Recorded duration statistics:
count    5412.000000
mean        6.364581
std        12.899891
min         0.500000
25%         1.067500
50%         2.450000
75%         6.432500
max       380.280000
Name: duration_minutes, dtype: float64

========== SESSION OVERLAPS ==========
Overlapping sessions: 246
Zero-gap sessions: 16

Session gap statistics:
count     5406.000000
mean        74.209751
std       1121.813933
min        -81.203117
25%          0.261117
50%          2.428017
75%         21.281425
max      62586.002650
Name: session_gap_minutes, dtype: float64

INSPECT OVERLAPPING SESSIONS

In [58]:
# ============================================
# INSPECT OVERLAPPING SESSIONS
# ============================================

overlaps = temp[
    temp["session_gap_minutes"] < 0
].copy()

print("Overlapping records:", len(overlaps))

display(
    overlaps[
        [
            "user_id",
            "start_utc",
            "end_utc",
            "previous_end_utc",
            "session_gap_minutes",
            "app_label",
            "duration_minutes"
        ]
    ]
    .sort_values(
        ["user_id", "start_utc"]
    )
    .head(30)
)

Overlapping records: 246

,user_id,start_utc,end_utc,previous_end_utc,session_gap_minutes,app_label,duration_minutes
797,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-03 19:11:38+00:00,2026-05-03 19:12:10+00:00,2026-05-03 19:12:54.043000+00:00,-1.267383,Instagram,0.53
801,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-03 19:23:42+00:00,2026-05-03 19:24:31+00:00,2026-05-03 19:57:31.607000+00:00,-33.826783,Instagram,0.82
810,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-04 03:30:54+00:00,2026-05-04 09:51:11+00:00,2026-05-04 03:31:00.460000+00:00,-0.107667,Instagram,380.28
828,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-05 19:12:22+00:00,2026-05-05 19:13:24+00:00,2026-05-05 19:22:11.441000+00:00,-9.824017,Instagram,1.03
834,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-05 19:37:27+00:00,2026-05-05 20:13:37+00:00,2026-05-05 19:37:35.102000+00:00,-0.135033,Instagram,36.17
869,85bfc215-c24f-4814-aa00-6794f1a7278a,2026-05-06 18:19:59+00:00,2026-05-06 18:20:29+00:00,2026-05-06 18:23:00+00:00,-3.016667,Instagram,0.50
1398,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 05:36:33.182000+00:00,2026-04-24 05:37:38.245000+00:00,2026-04-24 05:37:36.168000+00:00,-1.049767,YouTube,1.08
1400,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 05:38:46.510000+00:00,2026-04-24 05:54:31.528000+00:00,2026-04-24 05:54:29.451000+00:00,-15.715683,YouTube,15.75
1402,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:13:32.498000+00:00,2026-04-24 06:22:59.039000+00:00,2026-04-24 06:22:56.962000+00:00,-9.407733,YouTube,9.44
1404,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:28:56.696000+00:00,2026-04-24 06:29:46.089000+00:00,2026-04-24 06:29:44.012000+00:00,-0.788600,YouTube,0.82
1406,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:29:48.756000+00:00,2026-04-24 06:31:00.928000+00:00,2026-04-24 06:30:58.851000+00:00,-1.168250,YouTube,1.20
1408,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:31:35.259000+00:00,2026-04-24 06:32:47.322000+00:00,2026-04-24 06:32:45.245000+00:00,-1.166433,YouTube,1.20
1410,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:48:36.187000+00:00,2026-04-24 06:49:15.856000+00:00,2026-04-24 06:49:13.779000+00:00,-0.626533,Facebook,0.66
1412,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 06:49:21.004000+00:00,2026-04-24 07:19:18.661000+00:00,2026-04-24 07:19:16.584000+00:00,-29.926333,Facebook,29.96
1414,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:25:57.302000+00:00,2026-04-24 07:28:44.221000+00:00,2026-04-24 07:28:42.144000+00:00,-2.747367,Facebook,2.78
1416,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:34:55.484000+00:00,2026-04-24 07:42:15.846000+00:00,2026-04-24 07:42:13.769000+00:00,-7.304750,Facebook,7.34
1418,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 07:50:12.467000+00:00,2026-04-24 07:52:04.857000+00:00,2026-04-24 07:52:02.780000+00:00,-1.838550,Facebook,1.87
1420,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:01:18.530000+00:00,2026-04-24 08:03:59.016000+00:00,2026-04-24 08:03:56.939000+00:00,-2.640150,Facebook,2.67
1422,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:07:15.154000+00:00,2026-04-24 08:09:44.779000+00:00,2026-04-24 08:09:42.702000+00:00,-2.459133,Facebook,2.49
1424,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 08:15:58.672000+00:00,2026-04-24 08:17:57.367000+00:00,2026-04-24 08:17:55.290000+00:00,-1.943633,Instagram,1.98
1426,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:30:01.084000+00:00,2026-04-24 09:32:43.081000+00:00,2026-04-24 09:32:41.004000+00:00,-2.665333,Instagram,2.70
1428,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:34:32.021000+00:00,2026-04-24 09:35:15.475000+00:00,2026-04-24 09:35:13.398000+00:00,-0.689617,Facebook,0.72
1430,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:35:21.146000+00:00,2026-04-24 09:37:25.977000+00:00,2026-04-24 09:37:23.900000+00:00,-2.045900,Facebook,2.08
1432,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 09:58:44.549000+00:00,2026-04-24 10:00:40.163000+00:00,2026-04-24 10:00:38.086000+00:00,-1.892283,TikTok,1.93
1434,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 10:18:08.335000+00:00,2026-04-24 10:19:06.704000+00:00,2026-04-24 10:19:04.627000+00:00,-0.938200,Facebook,0.97
1436,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:31:56.752000+00:00,2026-04-24 11:33:22.527000+00:00,2026-04-24 11:33:20.450000+00:00,-1.394967,Facebook,1.43
1438,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:34:06.229000+00:00,2026-04-24 11:35:38.232000+00:00,2026-04-24 11:35:36.155000+00:00,-1.498767,Facebook,1.53
1440,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 11:38:32.635000+00:00,2026-04-24 11:39:14.822000+00:00,2026-04-24 11:39:12.745000+00:00,-0.668500,Facebook,0.70
1442,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 13:00:15.480000+00:00,2026-04-24 13:02:26.051000+00:00,2026-04-24 13:02:23.974000+00:00,-2.141567,Facebook,2.18
1444,8cf97b0c-76c9-4d72-b617-759a955f969f,2026-04-24 13:02:32.608000+00:00,2026-04-24 13:04:55.536000+00:00,2026-04-24 13:04:53.459000+00:00,-2.347517,Facebook,2.38

In [59]:
print("========== OVERLAPS BY USER ==========")

display(
    overlaps.groupby("user_id")
    .agg(
        overlapping_sessions=("user_id", "size"),
        mean_overlap_minutes=("session_gap_minutes", "mean"),
        maximum_overlap_minutes=("session_gap_minutes", "min")
    )
    .reset_index()
)

========== OVERLAPS BY USER ==========

,user_id,overlapping_sessions,mean_overlap_minutes,maximum_overlap_minutes
0,85bfc215-c24f-4814-aa00-6794f1a7278a,6,-8.029592,-33.826783
1,8cf97b0c-76c9-4d72-b617-759a955f969f,240,-5.480831,-81.203117

In [60]:
print("========== OVERLAP APP PATTERNS ==========")

overlaps["previous_app"] = (
    temp.loc[overlaps.index - 1, "app_label"].values
)

display(
    overlaps.groupby(
        ["previous_app", "app_label"]
    )
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
    .head(20)
)

========== OVERLAP APP PATTERNS ==========

  previous_app  app_label  count
0     Facebook   Facebook    154
2    Instagram  Instagram     59
5      YouTube    YouTube     26
3     Snapchat   Snapchat      4
4       TikTok     TikTok      2
1     Facebook  Instagram      1

In [61]:
print("========== OVERLAP MAGNITUDE ==========")

overlap_magnitude = (
    overlaps["session_gap_minutes"]
    .abs()
)

print(overlap_magnitude.describe())

print("\nOverlap duration ranges:")

bins = [-float("inf"), 1, 5, 10, 30, 60, float("inf")]

labels = [
    "<= 1 min",
    "1–5 min",
    "5–10 min",
    "10–30 min",
    "30–60 min",
    "> 60 min"
]

display(
    pd.cut(
        overlap_magnitude,
        bins=bins,
        labels=labels
    )
    .value_counts()
    .sort_index()
    .rename_axis("overlap_size")
    .reset_index(name="count")
)

========== OVERLAP MAGNITUDE ==========
count    246.000000
mean       5.542996
std       10.994173
min        0.001767
25%        0.848133
50%        1.850075
75%        4.967542
max       81.203117
Name: session_gap_minutes, dtype: float64

Overlap duration ranges:

  overlap_size  count
0     <= 1 min     74
1      1–5 min    111
2     5–10 min     30
3    10–30 min     23
4    30–60 min      5
5     > 60 min      3

In [67]:
# Make a diagnostic copy
overlap_check = df_all.copy()

overlap_check["start_utc"] = pd.to_datetime(
    overlap_check["session_start"],
    unit="ms",
    utc=True
)

overlap_check["end_utc"] = pd.to_datetime(
    overlap_check["session_end"],
    unit="ms",
    utc=True
)

# Sort by user, app, and start time
overlap_check = overlap_check.sort_values(
    ["user_id", "app_label", "start_utc"]
).reset_index(drop=True)

# Previous session for the same user + app
overlap_check["previous_same_app_start"] = (
    overlap_check
    .groupby(["user_id", "app_label"])["start_utc"]
    .shift(1)
)

overlap_check["previous_same_app_end"] = (
    overlap_check
    .groupby(["user_id", "app_label"])["end_utc"]
    .shift(1)
)

# Actual interval intersection:
# max(starts) -> min(ends)
intersection_start = overlap_check[
    ["start_utc", "previous_same_app_start"]
].max(axis=1)

intersection_end = overlap_check[
    ["end_utc", "previous_same_app_end"]
].min(axis=1)

overlap_check["actual_overlap_minutes"] = (
    (intersection_end - intersection_start)
    .dt.total_seconds() / 60
).clip(lower=0)

# Fraction of the CURRENT session that is actually overlapped
overlap_check["actual_overlap_fraction"] = (
    overlap_check["actual_overlap_minutes"]
    / overlap_check["duration_minutes"]
)

# Keep only genuine intersections
actual_overlaps = overlap_check[
    overlap_check["actual_overlap_minutes"] > 0
].copy()

print("Actual same-app overlapping sessions:", len(actual_overlaps))

print("\nActual overlap fraction:")
print(
    actual_overlaps["actual_overlap_fraction"].describe()
)

print(
    "\nActual overlap >= 90%:",
    (
        actual_overlaps["actual_overlap_fraction"] >= 0.90
    ).sum()
)

print(
    "Actual overlap < 90%:",
    (
        actual_overlaps["actual_overlap_fraction"] < 0.90
    ).sum()
)

print(
    "\nActual overlap > 100%:",
    (
        actual_overlaps["actual_overlap_fraction"] > 1.0
    ).sum()
)

Actual same-app overlapping sessions: 267

Actual overlap fraction:
count    267.000000
mean       0.905269
std        0.260929
min        0.000283
25%        0.963540
50%        0.984400
75%        0.995227
max        1.006289
Name: actual_overlap_fraction, dtype: float64

Actual overlap >= 90%: 246
Actual overlap < 90%: 21

Actual overlap > 100%: 14

In [68]:
over_100 = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] > 1.0
].copy()

cols = [
    "user_id",
    "app_label",
    "start_utc",
    "end_utc",
    "duration_minutes",
    "previous_same_app_start",
    "previous_same_app_end",
    "actual_overlap_minutes",
    "actual_overlap_fraction"
]

print(
    over_100[cols]
    .sort_values("actual_overlap_fraction", ascending=False)
    .to_string(index=False)
)

                             user_id app_label                        start_utc                          end_utc  duration_minutes          previous_same_app_start            previous_same_app_end  actual_overlap_minutes  actual_overlap_fraction
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-03 19:11:38+00:00        2026-05-03 19:12:10+00:00              0.53 2026-05-03 19:10:35.588000+00:00 2026-05-03 19:12:54.043000+00:00                0.533333                 1.006289
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-05 19:12:22+00:00        2026-05-05 19:13:24+00:00              1.03 2026-05-05 19:10:46.942000+00:00 2026-05-05 19:22:11.441000+00:00                1.033333                 1.003236
f5e00193-6fb8-4767-ba5e-5c824dc24c89    TikTok 2026-09-23 06:58:02.956000+00:00 2026-09-23 06:58:51.700000+00:00              0.81                              NaT                              NaT                0.812400                 1.002963
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-17 10:18:14.939000+00:00 2026-04-17 10:19:07.258000+00:00              0.87                              NaT                              NaT                0.871983                 1.002280
e7642be3-461d-4c8e-98cd-0eccc76764ec Twitter/X 2026-09-24 17:31:25.124000+00:00 2026-09-24 17:34:15.154000+00:00              2.83                              NaT                              NaT                2.833833                 1.001355
d5a62f7a-97c9-481c-83be-f0a06b70cad9  Facebook 2026-04-16 19:07:01.509000+00:00 2026-04-16 19:09:11.825000+00:00              2.17                              NaT                              NaT                2.171933                 1.000891
8cf97b0c-76c9-4d72-b617-759a955f969f  Snapchat 2026-04-25 07:46:57.388000+00:00 2026-04-25 07:47:40.025000+00:00              0.71                              NaT                              NaT                0.710617                 1.000869
e7642be3-461d-4c8e-98cd-0eccc76764ec    TikTok 2026-09-22 19:31:52.389000+00:00 2026-09-22 19:36:20.176000+00:00              4.46                              NaT                              NaT                4.463117                 1.000699
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4   YouTube 2026-09-10 18:19:11.005000+00:00 2026-09-10 18:23:39.985000+00:00              4.48                              NaT                              NaT                4.483000                 1.000670
85bfc215-c24f-4814-aa00-6794f1a7278a   YouTube 2026-04-12 12:07:52.362000+00:00 2026-04-12 12:14:38.197000+00:00              6.76                              NaT                              NaT                6.763917                 1.000579
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 Instagram 2026-09-02 12:42:42.152000+00:00 2026-09-02 12:51:08.201000+00:00              8.43                              NaT                              NaT                8.434150                 1.000492
e7642be3-461d-4c8e-98cd-0eccc76764ec  Facebook 2026-09-22 19:06:43.060000+00:00 2026-09-22 19:09:29.936000+00:00              2.78                              NaT                              NaT                2.781267                 1.000456
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-17 16:44:29.899000+00:00 2026-04-17 16:53:38.397000+00:00              9.14                              NaT                              NaT                9.141633                 1.000179
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram 2026-04-09 05:53:43.406000+00:00 2026-04-09 05:59:04.446000+00:00              5.35                              NaT                              NaT                5.350667                 1.000125

In [69]:
partial_overlaps = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] < 0.90
].copy()

cols = [
    "user_id",
    "app_label",
    "start_utc",
    "end_utc",
    "duration_minutes",
    "previous_same_app_start",
    "previous_same_app_end",
    "actual_overlap_minutes",
    "actual_overlap_fraction"
]

print(
    partial_overlaps[
        cols
    ]
    .sort_values(
        ["user_id", "start_utc"]
    )
    .to_string(index=False)
)

                             user_id app_label                        start_utc                          end_utc  duration_minutes          previous_same_app_start            previous_same_app_end  actual_overlap_minutes  actual_overlap_fraction
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-04 03:30:54+00:00        2026-05-04 09:51:11+00:00            380.28 2026-05-04 03:28:32.196000+00:00 2026-05-04 03:31:00.460000+00:00                0.107667                 0.000283
85bfc215-c24f-4814-aa00-6794f1a7278a Instagram        2026-05-05 19:37:27+00:00        2026-05-05 20:13:37+00:00             36.17 2026-05-05 19:34:44.514000+00:00 2026-05-05 19:37:35.102000+00:00                0.135033                 0.003733
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 05:34:55.703000+00:00 2026-04-25 05:51:29.763000+00:00             16.57 2026-04-25 05:33:37.593000+00:00 2026-04-25 05:34:57.775000+00:00                0.034533                 0.002084
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 15:38:02.069000+00:00 2026-04-25 15:41:51.498000+00:00              3.82 2026-04-25 15:36:53.479000+00:00 2026-04-25 15:38:04.142000+00:00                0.034550                 0.009045
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-25 18:25:52.696000+00:00 2026-04-25 18:27:47.356000+00:00              1.91 2026-04-25 18:23:12.050000+00:00 2026-04-25 18:25:54.768000+00:00                0.034533                 0.018080
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 09:47:50.645000+00:00 2026-04-26 09:48:34.592000+00:00              0.73 2026-04-26 09:46:56.311000+00:00 2026-04-26 09:47:52.717000+00:00                0.034533                 0.047306
8cf97b0c-76c9-4d72-b617-759a955f969f Instagram 2026-04-26 17:04:55.322000+00:00 2026-04-26 17:46:35.058000+00:00             41.66 2026-04-26 17:01:19.849000+00:00 2026-04-26 17:04:57.280000+00:00                0.032633                 0.000783
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:20:20.343000+00:00 2026-04-26 18:23:44.640000+00:00              3.40 2026-04-26 18:17:42.888000+00:00 2026-04-26 18:20:22.415000+00:00                0.034533                 0.010157
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:31:40.609000+00:00 2026-04-26 18:46:09.663000+00:00             14.48 2026-04-26 18:30:33.566000+00:00 2026-04-26 18:31:42.678000+00:00                0.034483                 0.002381
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:46:09.670000+00:00 2026-04-26 18:48:32.072000+00:00              2.37 2026-04-26 18:31:42.686000+00:00 2026-04-26 18:46:11.740000+00:00                0.034500                 0.014557
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 18:49:57.413000+00:00 2026-04-26 18:52:30.906000+00:00              2.56 2026-04-26 18:48:47.849000+00:00 2026-04-26 18:49:57.519000+00:00                0.001767                 0.000690
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-26 19:14:19.729000+00:00 2026-04-26 19:21:05.372000+00:00              6.76 2026-04-26 19:13:50.008000+00:00 2026-04-26 19:14:21.801000+00:00                0.034533                 0.005108
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-26 21:01:58.555000+00:00 2026-04-26 21:04:47.542000+00:00              2.82 2026-04-26 19:40:46.303000+00:00 2026-04-26 21:02:00.567000+00:00                0.033533                 0.011891
8cf97b0c-76c9-4d72-b617-759a955f969f   YouTube 2026-04-26 21:04:47.607000+00:00 2026-04-26 21:15:18.219000+00:00             10.51 2026-04-26 21:02:00.632000+00:00 2026-04-26 21:04:49.619000+00:00                0.033533                 0.003191
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 10:08:26.389000+00:00 2026-04-27 10:14:07.097000+00:00              5.68 2026-04-27 10:07:53.346000+00:00 2026-04-27 10:08:28.460000+00:00                0.034517                 0.006077
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 10:14:07.101000+00:00 2026-04-27 10:14:44.483000+00:00              0.62 2026-04-27 10:08:28.466000+00:00 2026-04-27 10:14:09.174000+00:00                0.034550                 0.055726
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-27 19:25:30.299000+00:00 2026-04-27 19:26:53.007000+00:00              1.38 2026-04-27 18:58:34.457000+00:00 2026-04-27 19:25:32.350000+00:00                0.034183                 0.024771
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-28 12:58:57.973000+00:00 2026-04-28 13:05:09.150000+00:00              6.19 2026-04-28 12:57:58.028000+00:00 2026-04-28 12:59:00.045000+00:00                0.034533                 0.005579
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-28 14:12:52.699000+00:00 2026-04-28 14:15:29.612000+00:00              2.62 2026-04-28 14:12:05.286000+00:00 2026-04-28 14:12:54.773000+00:00                0.034567                 0.013193
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-29 13:28:45.155000+00:00 2026-04-29 13:29:35.993000+00:00              0.85 2026-04-29 13:28:12.775000+00:00 2026-04-29 13:28:47.228000+00:00                0.034550                 0.040647
8cf97b0c-76c9-4d72-b617-759a955f969f  Facebook 2026-04-30 21:00:36.969000+00:00 2026-04-30 21:01:11.429000+00:00              0.57 2026-04-30 21:00:05.223000+00:00 2026-04-30 21:00:39.038000+00:00                0.034483                 0.060497

In [70]:
high_overlap = actual_overlaps[
    actual_overlaps["actual_overlap_fraction"] >= 0.90
].copy()

high_overlap["current_contained_in_previous"] = (
    (high_overlap["start_utc"] >= high_overlap["previous_same_app_start"]) &
    (high_overlap["end_utc"] <= high_overlap["previous_same_app_end"])
)

high_overlap["previous_contained_in_current"] = (
    (high_overlap["previous_same_app_start"] >= high_overlap["start_utc"]) &
    (high_overlap["previous_same_app_end"] <= high_overlap["end_utc"])
)

print(
    "Current contained in previous:",
    high_overlap["current_contained_in_previous"].sum()
)

print(
    "Previous contained in current:",
    high_overlap["previous_contained_in_current"].sum()
)

print(
    "Neither fully contained:",
    (
        ~high_overlap["current_contained_in_previous"] &
        ~high_overlap["previous_contained_in_current"]
    ).sum()
)

Current contained in previous: 4
Previous contained in current: 0
Neither fully contained: 242

In [71]:
print("\nBy user:")
print(
    high_overlap.groupby("user_id").size()
)

print("\nBy app:")
print(
    high_overlap.groupby("app_label").size()
)

By user:
user_id
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4      2
85bfc215-c24f-4814-aa00-6794f1a7278a      9
8cf97b0c-76c9-4d72-b617-759a955f969f    225
d5a62f7a-97c9-481c-83be-f0a06b70cad9      4
e7642be3-461d-4c8e-98cd-0eccc76764ec      5
f5e00193-6fb8-4767-ba5e-5c824dc24c89      1
dtype: int64

By app:
app_label
Facebook     142
Instagram     61
Snapchat       6
TikTok         6
Twitter/X      2
YouTube       29
dtype: int64

In [72]:
high_overlap["previous_duration_minutes"] = (
    (
        high_overlap["previous_same_app_end"]
        - high_overlap["previous_same_app_start"]
    )
    .dt.total_seconds() / 60
)

high_overlap["duration_ratio_to_previous"] = (
    high_overlap["duration_minutes"]
    / high_overlap["previous_duration_minutes"]
)

print("\nCurrent duration:")
print(
    high_overlap["duration_minutes"].describe()
)

print("\nPrevious duration:")
print(
    high_overlap["previous_duration_minutes"].describe()
)

print("\nCurrent / previous duration ratio:")
print(
    high_overlap["duration_ratio_to_previous"].describe()
)

Current duration:
count    246.000000
mean       6.895813
std       20.747652
min        0.500000
25%        1.030000
50%        2.090000
75%        5.425000
max      283.270000
Name: duration_minutes, dtype: float64

Previous duration:
count    224.000000
mean       6.147869
std       11.410117
min        0.503700
25%        1.090621
50%        2.099892
75%        5.680663
max       81.237733
Name: previous_duration_minutes, dtype: float64

Current / previous duration ratio:
count    224.000000
mean       0.983835
std        0.118110
min        0.022474
25%        0.998528
50%        0.999894
75%        1.000630
max        1.009174
Name: duration_ratio_to_previous, dtype: float64

In [73]:
# Calculate previous same-app duration for all records
overlap_check["previous_duration_minutes"] = (
    (
        overlap_check["previous_same_app_end"]
        - overlap_check["previous_same_app_start"]
    )
    .dt.total_seconds() / 60
)

overlap_check["duration_ratio_to_previous"] = (
    overlap_check["duration_minutes"]
    / overlap_check["previous_duration_minutes"]
)

# Candidate redundant sessions
potential_duplicates = overlap_check[
    (overlap_check["actual_overlap_fraction"] >= 0.90) &
    (overlap_check["duration_ratio_to_previous"] >= 0.90) &
    (overlap_check["duration_ratio_to_previous"] <= 1.10)
].copy()

print("Potential redundant sessions:", len(potential_duplicates))

print(
    "Percentage of all sessions:",
    round(len(potential_duplicates) / len(df_all) * 100, 2),
    "%"
)

print("\nBy user:")
print(
    potential_duplicates["user_id"].value_counts()
)

print("\nBy app:")
print(
    potential_duplicates["app_label"].value_counts()
)

Potential redundant sessions: 220
Percentage of all sessions: 4.07 %

By user:
user_id
8cf97b0c-76c9-4d72-b617-759a955f969f    220
Name: count, dtype: int64

By app:
app_label
Facebook     138
Instagram     52
YouTube       24
Snapchat       4
TikTok         2
Name: count, dtype: int64

CREATE CANONICAL DATASET THAT REMOVES REDUNDANT SESSIONS

In [74]:
# Create a clean derived copy
df_sessions = overlap_check.copy()

# Flag potential redundant sessions
df_sessions["is_potential_redundant"] = (
    (df_sessions["actual_overlap_fraction"] >= 0.90) &
    (df_sessions["duration_ratio_to_previous"] >= 0.90) &
    (df_sessions["duration_ratio_to_previous"] <= 1.10)
)

print("Total sessions:", len(df_sessions))
print(
    "Potential redundant:",
    df_sessions["is_potential_redundant"].sum()
)
print(
    "Potential redundant (%):",
    round(
        df_sessions["is_potential_redundant"].mean() * 100,
        2
    )
)

Total sessions: 5412
Potential redundant: 220
Potential redundant (%): 4.07

In [75]:
df_sessions_clean = df_sessions[
    ~df_sessions["is_potential_redundant"]
].copy()

df_sessions_clean = (
    df_sessions_clean
    .sort_values(["user_id", "start_utc"])
    .reset_index(drop=True)
)

print("Raw sessions:", len(df_sessions))
print("Clean sessions:", len(df_sessions_clean))
print(
    "Removed from analysis:",
    len(df_sessions) - len(df_sessions_clean)
)

Raw sessions: 5412
Clean sessions: 5192
Removed from analysis: 220

ADDING QUALITY FLAGS - To never lose track of a record

In [80]:
# Start from the raw session dataset with the 220 potential
# redundant records excluded.
df_sessions_clean = df_sessions[
    ~df_sessions["is_potential_redundant"]
].copy()

# Sort chronologically within each user + app
df_sessions_clean = (
    df_sessions_clean
    .sort_values(["user_id", "app_label", "start_utc"])
    .reset_index(drop=True)
)

# Previous same-app session end
df_sessions_clean["previous_same_app_end_clean"] = (
    df_sessions_clean
    .groupby(["user_id", "app_label"])["end_utc"]
    .shift(1)
)

# Actual remaining overlap
df_sessions_clean["remaining_overlap_minutes"] = (
    (
        df_sessions_clean["previous_same_app_end_clean"]
        - df_sessions_clean["start_utc"]
    )
    .dt.total_seconds() / 60
).clip(lower=0)

# Flag residual overlaps
df_sessions_clean["has_same_app_overlap"] = (
    df_sessions_clean["remaining_overlap_minutes"] > 0
)

# Categorize
df_sessions_clean["overlap_category"] = "none"

df_sessions_clean.loc[
    df_sessions_clean["has_same_app_overlap"],
    "overlap_category"
] = "residual_overlap"

print("Canonical sessions:", len(df_sessions_clean))

print("\nOverlap categories:")
print(
    df_sessions_clean["overlap_category"].value_counts()
)

print("\nResidual overlaps:")
print(
    df_sessions_clean["remaining_overlap_minutes"]
    .loc[df_sessions_clean["has_same_app_overlap"]]
    .describe()
)

Canonical sessions: 5192

Overlap categories:
overlap_category
none                5186
residual_overlap       6
Name: count, dtype: int64

Residual overlaps:
count     6.000000
mean      8.029592
std      13.150307
min       0.107667
25%       0.418121
50%       2.142025
75%       8.122179
max      33.826783
Name: remaining_overlap_minutes, dtype: float64

CANONICAL TEMPORAL COLUMNS

In [95]:
# ============================================================
# STEP 1: CANONICAL TEMPORAL REPRESENTATION
# ============================================================

df_features = df_sessions_clean.copy()

# Merge 'is_schedule_conflict' from df_student_activities into df_features
# Ensure 'user_id' and 'session_start' are common keys for merging
df_features = pd.merge(
    df_features,
    df_student_activities[['user_id', 'session_start', 'is_schedule_conflict']],
    on=['user_id', 'session_start'],
    how='left'
)

# Convert timestamps from Unix milliseconds → UTC
df_features["timestamp_utc"] = pd.to_datetime(
    df_features["session_start"],
    unit="ms",
    utc=True
)

df_features["session_end_utc"] = pd.to_datetime(
    df_features["session_end"],
    unit="ms",
    utc=True
)

# Convert UTC → Kenya local time
df_features["timestamp_local"] = (
    df_features["timestamp_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

df_features["session_end_local"] = (
    df_features["session_end_utc"]
    .dt.tz_convert("Africa/Nairobi")
)

# Canonical local calendar fields
df_features["local_date"] = (
    df_features["timestamp_local"].dt.date
)

df_features["local_hour"] = (
    df_features["timestamp_local"].dt.hour
)

df_features["local_minute"] = (
    df_features["timestamp_local"].dt.minute
)

df_features["day_of_week"] = (
    df_features["timestamp_local"].dt.day_name()
)

# Sort chronologically within participant
df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

print("Rows:", len(df_features))
print("Users:", df_features["user_id"].nunique())

print("\nDate range:")
print(df_features["local_date"].min(), "→", df_features["local_date"].max())

print("\nTimezone:")
print(df_features["timestamp_local"].dt.tz)

Rows: 5192
Users: 6

Date range:
2026-04-09 → 2026-09-29

Timezone:
Africa/Nairobi

CALCULATE SESSION GAP

In [83]:
# ============================================================
# STEP 2: SESSION GAP
# ============================================================

df_features["previous_session_end"] = (
    df_features
    .groupby("user_id")["session_end_local"]
    .shift(1)
)

df_features["session_gap_minutes"] = (
    (
        df_features["timestamp_local"]
        - df_features["previous_session_end"]
    )
    .dt.total_seconds() / 60
)

print(df_features["session_gap_minutes"].describe())

print("\nNegative gaps:")
print(
    (df_features["session_gap_minutes"] < 0).sum()
)

print("\nMissing gaps:")
print(
    df_features["session_gap_minutes"].isna().sum()
)

count     5186.000000
mean        77.612862
std       1145.239461
min        -33.826783
25%          0.387821
50%          2.807817
75%         23.605117
max      62586.002650
Name: session_gap_minutes, dtype: float64

Negative gaps:
6

Missing gaps:
6

DETERMINE DAILY CAUSAL FEATURES FOR BASELINE DERIVATION

In [84]:
# ============================================================
# STEP 3: CAUSAL DAILY FEATURES
# ============================================================

df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Number of sessions that occurred earlier on the same day
df_features["prior_daily_session_count"] = (
    df_features
    .groupby(["user_id", "local_date"])
    .cumcount()
)

# Usage accumulated before the current session
df_features["prior_daily_usage_minutes"] = (
    df_features
    .groupby(["user_id", "local_date"])["duration_minutes"]
    .transform(
        lambda s: s.shift(1).fillna(0).cumsum()
    )
)

print(
    df_features[
        [
            "user_id",
            "local_date",
            "timestamp_local",
            "duration_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes"
        ]
    ].head(15)
)

                                 user_id  local_date  \
0   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
1   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
2   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
3   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
4   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
5   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
6   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
7   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
8   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
9   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
10  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
11  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
12  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
13  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02
14  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4  2026-09-02

                    timestamp_local  duration_minutes  \
0  2026-09-02 15:42:42.152000+03:00              8.43
1  2026-09-02 17:31:20.020000+03:00              0.62
2  2026-09-02 17:32:57.877000+03:00              2.61
3  2026-09-02 17:35:34.725000+03:00              0.72
4  2026-09-02 17:37:01.411000+03:00              0.64
5  2026-09-02 17:38:05.397000+03:00              1.26
6  2026-09-02 17:39:21.029000+03:00              0.93
7  2026-09-02 17:45:07.658000+03:00              0.90
8  2026-09-02 17:46:18.607000+03:00              2.19
9  2026-09-02 17:48:30.079000+03:00              1.19
10 2026-09-02 19:15:50.864000+03:00              2.98
11 2026-09-02 19:20:52.009000+03:00              3.63
12 2026-09-02 19:24:39.124000+03:00              2.74
13 2026-09-02 19:28:46.339000+03:00              2.86
14 2026-09-02 19:31:40.960000+03:00              1.73

    prior_daily_session_count  prior_daily_usage_minutes
0                           0                       0.00
1                           1                       8.43
2                           2                       9.05
3                           3                      11.66
4                           4                      12.38
5                           5                      13.02
6                           6                      14.28
7                           7                      15.21
8                           8                      16.11
9                           9                      18.30
10                         10                      19.49
11                         11                      22.47
12                         12                      26.10
13                         13                      28.84
14                         14                      31.70

BUILD TOTAL PARTICIPANTS USAGE BASELINE

In [85]:
# ============================================================
# STEP 4: INDIVIDUAL DURATION BASELINE
# ============================================================

df_features = (
    df_features
    .sort_values(["user_id", "timestamp_local"])
    .reset_index(drop=True)
)

# Historical median based ONLY on previous sessions
df_features["previous_median_duration"] = (
    df_features
    .groupby("user_id")["duration_minutes"]
    .transform(
        lambda s:
        s.shift(1)
         .expanding(min_periods=5)
         .median()
    )
)

# Absolute deviation from personal baseline
df_features["duration_baseline_deviation"] = (
    df_features["duration_minutes"]
    - df_features["previous_median_duration"]
)

# Relative deviation from personal baseline
df_features["duration_baseline_ratio"] = (
    df_features["duration_minutes"]
    / df_features["previous_median_duration"].replace(0, np.nan)
)

print(
    df_features[
        [
            "user_id",
            "timestamp_local",
            "duration_minutes",
            "previous_median_duration",
            "duration_baseline_deviation",
            "duration_baseline_ratio"
        ]
    ].head(20)
)

                                 user_id                  timestamp_local  \
0   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 15:42:42.152000+03:00
1   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:31:20.020000+03:00
2   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:32:57.877000+03:00
3   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:35:34.725000+03:00
4   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:37:01.411000+03:00
5   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:38:05.397000+03:00
6   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:39:21.029000+03:00
7   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:45:07.658000+03:00
8   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:46:18.607000+03:00
9   46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 17:48:30.079000+03:00
10  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:15:50.864000+03:00
11  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:20:52.009000+03:00
12  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:24:39.124000+03:00
13  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:28:46.339000+03:00
14  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 19:31:40.960000+03:00
15  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:11:49.254000+03:00
16  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:18:14.014000+03:00
17  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:29:48.483000+03:00
18  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:40:32.214000+03:00
19  46b5fe4a-2c09-4006-bd5b-08bf12ece5e4 2026-09-02 20:41:37.829000+03:00

    duration_minutes  previous_median_duration  duration_baseline_deviation  \
0               8.43                       NaN                          NaN
1               0.62                       NaN                          NaN
2               2.61                       NaN                          NaN
3               0.72                       NaN                          NaN
4               0.64                       NaN                          NaN
5               1.26                     0.720                        0.540
6               0.93                     0.990                       -0.060
7               0.90                     0.930                       -0.030
8               2.19                     0.915                        1.275
9               1.19                     0.930                        0.260
10              2.98                     1.060                        1.920
11              3.63                     1.190                        2.440
12              2.74                     1.225                        1.515
13              2.86                     1.260                        1.600
14              1.73                     1.725                        0.005
15              2.77                     1.730                        1.040
16              1.01                     1.960                       -0.950
17              3.59                     1.730                        1.860
18              0.95                     1.960                       -1.010
19              2.65                     1.730                        0.920

    duration_baseline_ratio
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                  1.750000
6                  0.939394
7                  0.967742
8                  2.393443
9                  1.279570
10                 2.811321
11                 3.050420
12                 2.236735
13                 2.269841
14                 1.002899
15                 1.601156
16                 0.515306
17                 2.075145
18                 0.484694
19                 1.531792

ENSURING NO DATA LEAKAGE

In [86]:
# ============================================================
# STEP 5: BASIC FEATURE SANITY CHECK
# ============================================================

feature_columns = [
    "session_gap_minutes",
    "prior_daily_session_count",
    "prior_daily_usage_minutes",
    "previous_median_duration",
    "duration_baseline_deviation",
    "duration_baseline_ratio"
]

print("Feature summary:")
print(
    df_features[feature_columns].describe()
)

print("\nMissing values:")
print(
    df_features[feature_columns].isna().sum()
)

Feature summary:
       session_gap_minutes  prior_daily_session_count  \
count          5186.000000                5192.000000
mean             77.612862                  18.620763
std            1145.239461                  16.509749
min             -33.826783                   0.000000
25%               0.387821                   6.000000
50%               2.807817                  15.000000
75%              23.605117                  27.000000
max           62586.002650                 119.000000

       prior_daily_usage_minutes  previous_median_duration  \
count                5192.000000               5162.000000
mean                  106.056972                  2.533911
std                    90.360646                  1.008783
min                     0.000000                  0.720000
25%                    33.425000                  2.110000
50%                    88.890000                  2.420000
75%                   151.955000                  2.460000
max                   482.900000                  7.780000

       duration_baseline_deviation  duration_baseline_ratio
count                  5162.000000              5162.000000
mean                      3.864864                 2.600449
std                      12.918832                 4.913788
min                      -7.010000                 0.068456
25%                      -1.220000                 0.483406
50%                       0.125000                 1.053344
75%                       3.918750                 2.644452
max                     376.615000               104.422222

Missing values:
session_gap_minutes             6
prior_daily_session_count       0
prior_daily_usage_minutes       0
previous_median_duration       30
duration_baseline_deviation    30
duration_baseline_ratio        30
dtype: int64

In [87]:
# Check first session for each user
first_sessions = (
    df_features
    .groupby("user_id")
    .head(1)
)

print(
    first_sessions[
        [
            "user_id",
            "session_gap_minutes",
            "prior_daily_session_count",
            "prior_daily_usage_minutes",
            "previous_median_duration"
        ]
    ].to_string(index=False)
)

                             user_id  session_gap_minutes  prior_daily_session_count  prior_daily_usage_minutes  previous_median_duration
46b5fe4a-2c09-4006-bd5b-08bf12ece5e4                  NaN                          0                        0.0                       NaN
85bfc215-c24f-4814-aa00-6794f1a7278a                  NaN                          0                        0.0                       NaN
8cf97b0c-76c9-4d72-b617-759a955f969f                  NaN                          0                        0.0                       NaN
d5a62f7a-97c9-481c-83be-f0a06b70cad9                  NaN                          0                        0.0                       NaN
e7642be3-461d-4c8e-98cd-0eccc76764ec                  NaN                          0                        0.0                       NaN
f5e00193-6fb8-4767-ba5e-5c824dc24c89                  NaN                          0                        0.0                       NaN

In [93]:
# ============================================================
# TIMETABLE: PREPARE TIME INTERVALS
# ============================================================

day_to_number = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

timetable_df["day_of_week_num"] = (
    timetable_df["day"].map(day_to_number)
)

timetable_df["start_minute"] = (
    pd.to_datetime(
        timetable_df["start_time"],
        format="%H:%M"
    ).dt.hour * 60
    +
    pd.to_datetime(
        timetable_df["start_time"],
        format="%H:%M"
    ).dt.minute
)

timetable_df["end_minute"] = (
    pd.to_datetime(
        timetable_df["end_time"],
        format="%H:%M"
    ).dt.hour * 60
    +
    pd.to_datetime(
        timetable_df["end_time"],
        format="%H:%M"
    ).dt.minute
)

print(
    timetable_df[
        [
            "day",
            "start_time",
            "end_time",
            "day_of_week_num",
            "start_minute",
            "end_minute"
        ]
    ].to_string(index=False)
)

      day start_time end_time day_of_week_num  start_minute  end_minute
   Monday      08:15    10:15               0           495         615
   Monday      10:15    12:15               0           615         735
   Monday      13:15    14:15               0           795         855
   Monday      15:15    17:15               0           915        1035
  Tuesday      08:15    10:15               1           495         615
  Tuesday      10:15    11:15               1           615         675
  Tuesday      11:15    12:15               1           675         735
  Tuesday      13:15    15:15               1           795         915
Wednesday      08:15    10:15               2           495         615
Wednesday      11:15    12:15               2           675         735
Wednesday      13:15    15:15               2           795         915
Wednesday      15:15    17:15               2           915        1035
 Thursday      08:15    10:15               3           495         615
 Thursday      11:15    13:15               3           675         795
 Thursday      15:15    17:15               3           915        1035
   Friday      08:15    10:15               4           495         615
   Friday      14:15    17:15               4           855        1035

In [103]:
# ============================================================
# RECOMPUTE SCHEDULE CONFLICT FOR ALL CANONICAL SESSIONS
# ============================================================

def evaluate_schedule_conflict(timestamp, timetable):
    weekday = timestamp.weekday()
    minute_of_day = timestamp.hour * 60 + timestamp.minute

    day_events = timetable[
        timetable["day_of_week_num"] == weekday
    ]

    conflict = day_events[
        (day_events["start_minute"] <= minute_of_day) &
        (minute_of_day < day_events["end_minute"])
    ]

    return int(not conflict.empty)


df_features["is_schedule_conflict"] = (
    df_features["timestamp_local"]
    .apply(
        lambda timestamp:
        evaluate_schedule_conflict(timestamp, timetable_df)
    )
    .astype(int)
)

print("Rows:", len(df_features))

print("\nSchedule conflict values:")
print(
    df_features["is_schedule_conflict"]
    .value_counts(dropna=False)
)

print("\nMissing values:")
print(
    df_features["is_schedule_conflict"].isna().sum()
)

print("\nConflict percentage:")
print(
    df_features["is_schedule_conflict"].mean() * 100
)

Rows: 5192

Schedule conflict values:
is_schedule_conflict
0    3778
1    1414
Name: count, dtype: int64

Missing values:
0

Conflict percentage:
27.23420647149461

ASI SCORE AUDIT

In [107]:
day_score_columns = [
    "day_asi_score",
    "day_intensity_score",
    "day_fragmentation_score",
    "day_compulsion_score",
    "day_disruption_score"
]

print(
    df_features[day_score_columns].describe().T
)

                          count       mean        std  min   25%   50%   75%  \
day_asi_score            5192.0  50.623074  10.386384  5.0  46.0  52.0  58.0
day_intensity_score      5192.0  57.566448  15.540757  3.0  50.0  59.0  69.0
day_fragmentation_score  5192.0  71.307781  11.187171  3.0  68.0  74.0  78.0
day_compulsion_score     5192.0  46.759823  13.542484  1.0  39.0  49.0  56.0
day_disruption_score     5192.0  19.133282  13.007472  0.0   8.0  19.0  27.0

                          max
day_asi_score            74.0
day_intensity_score      95.0
day_fragmentation_score  92.0
day_compulsion_score     74.0
day_disruption_score     65.0

In [108]:
print("\nMissing values:")
print(
    df_features[day_score_columns].isna().sum()
)

Missing values:
day_asi_score              0
day_intensity_score        0
day_fragmentation_score    0
day_compulsion_score       0
day_disruption_score       0
dtype: int64

In [109]:
print("\nUnique values:")
for col in day_score_columns:
    print(
        f"{col}:",
        df_features[col].nunique(),
        "unique values"
    )

Unique values:
day_asi_score: 56 unique values
day_intensity_score: 77 unique values
day_fragmentation_score: 61 unique values
day_compulsion_score: 64 unique values
day_disruption_score: 48 unique values

In [110]:
example_user = df_features["user_id"].iloc[0]

print(
    df_features.loc[
        df_features["user_id"] == example_user,
        [
            "timestamp_local",
            "duration_minutes",
            "day_asi_score",
            "day_intensity_score",
            "day_fragmentation_score",
            "day_compulsion_score",
            "day_disruption_score"
        ]
    ]
    .head(30)
    .to_string(index=False)
)

                 timestamp_local  duration_minutes  day_asi_score  day_intensity_score  day_fragmentation_score  day_compulsion_score  day_disruption_score
2026-09-02 15:42:42.152000+03:00              8.43             40                   26                       69                    61                     0
2026-09-02 17:31:20.020000+03:00              0.62             40                   26                       69                    61                     0
2026-09-02 17:32:57.877000+03:00              2.61             40                   26                       69                    61                     0
2026-09-02 17:35:34.725000+03:00              0.72             40                   26                       69                    61                     0
2026-09-02 17:37:01.411000+03:00              0.64             40                   26                       69                    61                     0
2026-09-02 17:38:05.397000+03:00              1.26             40                   26                       69                    61                     0
2026-09-02 17:39:21.029000+03:00              0.93             40                   26                       69                    61                     0
2026-09-02 17:45:07.658000+03:00              0.90             40                   26                       69                    61                     0
2026-09-02 17:46:18.607000+03:00              2.19             40                   26                       69                    61                     0
2026-09-02 17:48:30.079000+03:00              1.19             40                   26                       69                    61                     0
2026-09-02 19:15:50.864000+03:00              2.98             40                   26                       69                    61                     0
2026-09-02 19:20:52.009000+03:00              3.63             40                   26                       69                    61                     0
2026-09-02 19:24:39.124000+03:00              2.74             40                   26                       69                    61                     0
2026-09-02 19:28:46.339000+03:00              2.86             40                   26                       69                    61                     0
2026-09-02 19:31:40.960000+03:00              1.73             40                   26                       69                    61                     0
2026-09-02 20:11:49.254000+03:00              2.77             40                   26                       69                    61                     0
2026-09-02 20:18:14.014000+03:00              1.01             40                   26                       69                    61                     0
2026-09-02 20:29:48.483000+03:00              3.59             40                   26                       69                    61                     0
2026-09-02 20:40:32.214000+03:00              0.95             40                   26                       69                    61                     0
2026-09-02 20:41:37.829000+03:00              2.65             40                   26                       69                    61                     0
2026-09-02 20:51:11.999000+03:00              2.21             40                   26                       69                    61                     0
2026-09-02 20:55:29.503000+03:00              0.71             40                   26                       69                    61                     0
2026-09-02 20:59:29.831000+03:00              3.64             40                   26                       69                    61                     0
2026-09-02 21:11:02.617000+03:00              6.33             40                   26                       69                    61                     0
2026-09-02 21:26:32.470000+03:00              1.15             40                   26                       69                    61                     0
2026-09-02 21:37:06.366000+03:00              0.96             40                   26                       69                    61                     0
2026-09-03 06:50:44.008000+03:00              0.95             37                   31                       67                    41                     2
2026-09-03 06:51:50.212000+03:00              0.82             37                   31                       67                    41                     2
2026-09-03 06:53:43.189000+03:00              0.57             37                   31                       67                    41                     2
2026-09-03 07:00:24.158000+03:00              0.78             37                   31                       67                    41                     2